Object.assign(COMPANIES, {
  AFFIN: {
    name: "Affin Bank Berhad",
    ticker: "AFFIN",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Commercial Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "3,200",
    founded: 1975,
    ceo: "Datuk Wan Razly Abdullah Wan Ali",
    price: 2.45,
    change: 0.03,
    changePct: 1.24,
    marketCap: "MYR 5.2B",
    peRatio: 12.8,
    divYield: "3.2%",
    beta: 1.15,
    revenue52w: "MYR 2.8B",
    kpis: [
      { label: "Total Revenue", value: "MYR 2.8B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 405M", sub: "FY24" },
      { label: "Total Assets", value: "MYR 98B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "1.8%", sub: "Gross NPL" },
      { label: "ROE", value: "8.2%", sub: "Return on equity" },
      { label: "CAR", value: "16.5%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.1, 2.2, 2.4, 2.6, 2.8, 3.0],
      netIncome: [0.28, 0.32, 0.35, 0.38, 0.405, 0.44],
      grossMargin: [42, 43, 44, 45, 46, 47],
      operatingMargin: [28, 29, 30, 31, 32, 33],
      netMargin: [13.3, 14.5, 14.6, 14.6, 14.5, 14.7],
    },
    segments: {
      labels: ["Retail Banking", "Corporate Banking", "Islamic Banking", "Investment Banking", "Others"],
      values: [35, 28, 22, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Affin Bank", "Alliance Bank", "AmBank", "Hong Leong Bank", "RHB Bank"],
      revenue: [2.8, 3.2, 5.8, 6.5, 8.2],
      margin: [14.5, 15.2, 16.8, 18.2, 17.5],
    },
    swot: {
      strengths: [
        "Strong capital adequacy ratio above regulatory minimum",
        "Growing Islamic banking franchise with dedicated subsidiary",
        "Strategic partnership with Bank of East Asia for regional expansion",
        "Focused digital transformation initiatives",
      ],
      weaknesses: [
        "Smaller scale limits competitive pricing power",
        "Higher NPL ratio compared to top-tier peers",
        "Limited regional presence outside Malaysia",
        "Dependence on domestic market concentration",
      ],
      opportunities: [
        "Expansion of SME and retail lending in underserved segments",
        "Digital banking and fintech partnerships",
        "Islamic finance growth in ASEAN",
        "Wealth management and fee-based income expansion",
      ],
      threats: [
        "Intense competition from larger banks",
        "Interest rate volatility affecting margins",
        "Economic slowdown impacting asset quality",
        "Regulatory compliance costs",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Affin Bank has delivered steady mid-single-digit revenue growth driven by loan expansion and improved fee income, though it remains a smaller player in the Malaysian banking landscape with limited scale advantages." },
      { tag: "strategy", tagLabel: "Strategy", text: "The bank is pursuing a focused strategy on retail and SME segments while strengthening its Islamic banking arm Affin Islamic, with ongoing digital transformation to improve operational efficiency." },
      { tag: "risk", tagLabel: "Risk", text: "Asset quality remains a key monitor with NPL ratio above industry average; the bank maintains adequate provisions and capital buffers to absorb potential credit stress." },
      { tag: "market", tagLabel: "Market", text: "As a smaller tier bank, Affin competes primarily in niche segments and faces pressure from larger banks with better pricing power and digital capabilities." },
    ],
    risks: [
      { name: "Credit Risk", level: 38, color: "var(--green)" },
      { name: "Market Risk", level: 42, color: "var(--cyan)" },
      { name: "Operational Risk", level: 48, color: "var(--cyan)" },
      { name: "Liquidity Risk", level: 35, color: "var(--green)" },
      { name: "Competitive Risk", level: 58, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Affin Bank offers a turnaround story with improving fundamentals and digital initiatives, but remains constrained by scale. Valuation is reasonable with decent dividend yield. Suitable for investors seeking exposure to smaller Malaysian banks with potential for gradual improvement.",
    },
  },

  CIMB: {
    name: "CIMB Group Holdings Berhad",
    ticker: "CIMB",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Universal Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "37,000",
    founded: 1924,
    ceo: "Dato' Abdul Rahman Ahmad",
    price: 7.85,
    change: 0.12,
    changePct: 1.55,
    marketCap: "MYR 78.5B",
    peRatio: 11.2,
    divYield: "4.5%",
    beta: 1.22,
    revenue52w: "MYR 22.5B",
    kpis: [
      { label: "Total Revenue", value: "MYR 22.5B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 7.0B", sub: "FY24" },
      { label: "Total Assets", value: "MYR 680B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "2.1%", sub: "Gross NPL" },
      { label: "ROE", value: "11.8%", sub: "Return on equity" },
      { label: "CAR", value: "17.2%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [18.2, 19.5, 20.8, 21.5, 22.5, 23.8],
      netIncome: [3.8, 5.2, 6.0, 6.5, 7.0, 7.5],
      grossMargin: [48, 50, 51, 52, 53, 54],
      operatingMargin: [35, 38, 39, 40, 41, 42],
      netMargin: [20.9, 26.7, 28.8, 30.2, 31.1, 31.5],
    },
    segments: {
      labels: ["Consumer Banking", "Commercial Banking", "Wholesale Banking", "Group Markets", "Others"],
      values: [35, 25, 22, 12, 6],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["CIMB", "Maybank", "Public Bank", "RHB Bank", "Hong Leong Bank"],
      revenue: [22.5, 32.5, 16.2, 8.2, 6.5],
      margin: [31.1, 28.5, 35.2, 17.5, 18.2],
    },
    swot: {
      strengths: [
        "Largest ASEAN universal bank with presence across 6 countries",
        "Leading investment banking franchise in ASEAN",
        "Strong wholesale and capital markets capabilities",
        "Diversified revenue streams across consumer, commercial and wholesale",
      ],
      weaknesses: [
        "Higher NPL ratio than Public Bank and Maybank",
        "Indonesia operations face cyclical volatility",
        "Complex organizational structure across multiple jurisdictions",
        "Regulatory scrutiny in some markets",
      ],
      opportunities: [
        "ASEAN digital banking and fintech expansion",
        "Wealth management and private banking growth",
        "Sustainable finance and ESG-linked products",
        "Regional capital markets and M&A advisory",
      ],
      threats: [
        "Geopolitical and currency risks in ASEAN operations",
        "Competition from digital banks and fintechs",
        "Economic slowdown in key markets",
        "Regulatory changes across multiple jurisdictions",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "CIMB has delivered consistent revenue and earnings growth, benefiting from its ASEAN footprint and recovery in Indonesia and Thailand operations post-pandemic." },
      { tag: "strategy", tagLabel: "Strategy", text: "The group's Forward 23+ strategy focuses on digital transformation, sustainable finance leadership, and strengthening core markets while optimizing capital allocation." },
      { tag: "risk", tagLabel: "Risk", text: "Regional diversification brings both opportunity and risk; Indonesia exposure requires monitoring given economic cycles, while capital adequacy remains strong." },
      { tag: "market", tagLabel: "Market", text: "As Malaysia's second-largest bank by assets, CIMB offers unique ASEAN exposure and investment banking leadership, trading at a discount to pure domestic peers." },
    ],
    risks: [
      { name: "Credit Risk", level: 45, color: "var(--cyan)" },
      { name: "Market Risk", level: 52, color: "var(--cyan)" },
      { name: "Operational Risk", level: 48, color: "var(--cyan)" },
      { name: "Geopolitical Risk", level: 58, color: "var(--amber)" },
      { name: "Currency Risk", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "CIMB offers compelling value as Malaysia's second-largest bank with unique ASEAN diversification. Strong investment banking franchise and improving asset quality support earnings growth. Attractive dividend yield and reasonable valuation make it a core holding for Malaysian banking exposure.",
    },
  },

  MAYBANK: {
    name: "Malayan Banking Berhad",
    ticker: "MAYBANK",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Universal Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "42,000",
    founded: 1960,
    ceo: "Datuk Khairussaleh Ramli",
    price: 10.25,
    change: 0.18,
    changePct: 1.79,
    marketCap: "MYR 122.5B",
    peRatio: 12.5,
    divYield: "5.2%",
    beta: 1.18,
    revenue52w: "MYR 32.5B",
    kpis: [
      { label: "Total Revenue", value: "MYR 32.5B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 9.3B", sub: "FY24" },
      { label: "Total Assets", value: "MYR 1.05T", sub: "As at FY24" },
      { label: "NPL Ratio", value: "1.6%", sub: "Gross NPL" },
      { label: "ROE", value: "12.5%", sub: "Return on equity" },
      { label: "CAR", value: "18.1%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [26.5, 28.2, 29.8, 31.0, 32.5, 34.0],
      netIncome: [5.2, 7.0, 8.2, 8.8, 9.3, 9.9],
      grossMargin: [45, 47, 48, 49, 50, 51],
      operatingMargin: [32, 35, 36, 37, 38, 39],
      netMargin: [19.6, 24.8, 27.5, 28.4, 28.6, 29.1],
    },
    segments: {
      labels: ["Community Financial Services", "Global Banking", "Islamic Banking", "Insurance", "Others"],
      values: [42, 28, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Maybank", "CIMB", "Public Bank", "RHB Bank", "Hong Leong Bank"],
      revenue: [32.5, 22.5, 16.2, 8.2, 6.5],
      margin: [28.6, 31.1, 35.2, 17.5, 18.2],
    },
    swot: {
      strengths: [
        "Largest bank in Malaysia and ASEAN by assets",
        "Extensive branch network and market leadership in retail",
        "Strong brand recognition and customer trust",
        "Leading Islamic banking franchise with Maybank Islamic",
      ],
      weaknesses: [
        "Large scale can limit agility and innovation speed",
        "Singapore operations face competitive pressure",
        "Legacy systems require ongoing digital investment",
        "Exposure to cyclical sectors in ASEAN",
      ],
      opportunities: [
        "Digital banking and MAE ecosystem expansion",
        "Wealth management and affluent segment growth",
        "Sustainable finance and green lending leadership",
        "ASEAN regional integration benefits",
      ],
      threats: [
        "Disruption from digital banks and fintechs",
        "Interest rate environment volatility",
        "Economic slowdown in key ASEAN markets",
        "Regulatory capital requirements",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Maybank continues to deliver steady growth as Malaysia's largest bank, with strong contributions from community financial services and improving regional operations." },
      { tag: "strategy", tagLabel: "Strategy", text: "The M25+ strategy emphasizes digital leadership through MAE, sustainable finance, and ASEAN connectivity while maintaining prudent risk management and capital discipline." },
      { tag: "risk", tagLabel: "Risk", text: "Strong asset quality with NPL ratio among the lowest in the industry; robust capital position and diversified funding support resilience through economic cycles." },
      { tag: "market", tagLabel: "Market", text: "As the dominant Malaysian bank with ASEAN presence, Maybank offers defensive characteristics with attractive dividend yield, suitable as a core portfolio holding." },
    ],
    risks: [
      { name: "Credit Risk", level: 38, color: "var(--green)" },
      { name: "Market Risk", level: 45, color: "var(--cyan)" },
      { name: "Operational Risk", level: 42, color: "var(--cyan)" },
      { name: "Regulatory Risk", level: 48, color: "var(--cyan)" },
      { name: "Competitive Risk", level: 52, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Maybank remains the preferred core holding in Malaysian banking. Market leadership, strong asset quality, and attractive dividend yield provide a compelling investment case. Digital initiatives and sustainable finance focus position the bank well for long-term growth.",
    },
  },

  PBBANK: {
    name: "Public Bank Berhad",
    ticker: "PBBANK",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Commercial Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "28,000",
    founded: 1966,
    ceo: "Tan Sri Datuk Seri Dr. Tay Ah Lek",
    price: 4.85,
    change: 0.05,
    changePct: 1.04,
    marketCap: "MYR 94.0B",
    peRatio: 14.2,
    divYield: "3.8%",
    beta: 1.05,
    revenue52w: "MYR 16.2B",
    kpis: [
      { label: "Total Revenue", value: "MYR 16.2B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 5.7B", sub: "FY24" },
      { label: "Total Assets", value: "MYR 520B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "0.4%", sub: "Gross NPL - industry best" },
      { label: "ROE", value: "12.2%", sub: "Return on equity" },
      { label: "CAR", value: "17.8%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [14.2, 14.8, 15.2, 15.7, 16.2, 16.8],
      netIncome: [4.5, 5.0, 5.3, 5.5, 5.7, 6.0],
      grossMargin: [52, 53, 54, 55, 56, 57],
      operatingMargin: [42, 43, 44, 45, 46, 47],
      netMargin: [31.7, 33.8, 34.9, 35.0, 35.2, 35.7],
    },
    segments: {
      labels: ["Retail Banking", "Commercial Banking", "Islamic Banking", "Investment", "Others"],
      values: [48, 28, 18, 4, 2],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Public Bank", "Maybank", "CIMB", "RHB Bank", "Hong Leong Bank"],
      revenue: [16.2, 32.5, 22.5, 8.2, 6.5],
      margin: [35.2, 28.6, 31.1, 17.5, 18.2],
    },
    swot: {
      strengths: [
        "Best-in-class asset quality with lowest NPL ratio in industry",
        "Highest net margin among Malaysian banks",
        "Strong retail franchise and customer loyalty",
        "Prudent risk management and conservative culture",
      ],
      weaknesses: [
        "Limited regional presence compared to Maybank and CIMB",
        "Slower digital innovation adoption",
        "Concentration in property and retail lending",
        "Smaller investment banking presence",
      ],
      opportunities: [
        "Digital banking and mobile app enhancement",
        "Wealth management and affluent segment",
        "SME lending expansion",
        "Vietnam and Cambodia operations growth",
      ],
      threats: [
        "Property market slowdown affecting mortgage growth",
        "Competition from digital banks",
        "Interest rate compression on margins",
        "Regulatory changes on consumer lending",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Public Bank delivers consistent mid-single-digit growth with industry-leading profitability metrics, driven by its focus on retail and SME lending with superior asset quality." },
      { tag: "strategy", tagLabel: "Strategy", text: "The bank maintains a conservative, relationship-driven approach with emphasis on sustainable growth, prudent lending, and operational efficiency rather than aggressive expansion." },
      { tag: "risk", tagLabel: "Risk", text: "Public Bank's 0.4% NPL ratio is the gold standard in Malaysian banking, reflecting rigorous credit underwriting and conservative risk appetite throughout economic cycles." },
      { tag: "market", tagLabel: "Market", text: "Trading at a premium valuation justified by superior asset quality and profitability, Public Bank appeals to quality-focused investors seeking defensive banking exposure." },
    ],
    risks: [
      { name: "Credit Risk", level: 22, color: "var(--green)" },
      { name: "Market Risk", level: 42, color: "var(--cyan)" },
      { name: "Operational Risk", level: 38, color: "var(--green)" },
      { name: "Concentration Risk", level: 52, color: "var(--cyan)" },
      { name: "Competitive Risk", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Public Bank remains the quality leader in Malaysian banking with unmatched asset quality and profitability. While growth may be more modest than peers, the premium is justified by lower risk and consistent returns. Ideal for income and quality-focused investors.",
    },
  },

  BKRAKYAT: {
    name: "Bank Rakyat",
    ticker: "BKRAKYAT",
    entityType: "statutory",
    sector: "Banking & Finance",
    industry: "Cooperative Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "12,500",
    founded: 1954,
    ceo: "Datuk Mohd Naziruddin Nasir",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Total Revenue", value: "MYR 8.5B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 1.2B", sub: "FY24" },
      { label: "Total Assets", value: "MYR 120B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "2.5%", sub: "Gross NPL" },
      { label: "Members", value: "10.2M", sub: "Cooperative members" },
      { label: "CAR", value: "15.2%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6.8, 7.2, 7.6, 8.0, 8.5, 9.0],
      netIncome: [0.9, 1.0, 1.1, 1.15, 1.2, 1.3],
      grossMargin: [38, 39, 40, 41, 42, 43],
      operatingMargin: [25, 26, 27, 28, 29, 30],
      netMargin: [13.2, 13.9, 14.5, 14.4, 14.1, 14.4],
    },
    segments: {
      labels: ["Personal Financing", "Housing Loans", "Consumer Loans", "Deposits & Savings", "Others"],
      values: [45, 25, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Bank Rakyat", "BSN", "Agrobank", "Bank Islam", "RHB Bank"],
      revenue: [8.5, 3.2, 4.5, 5.2, 8.2],
      margin: [14.1, 8.5, 12.2, 18.5, 17.5],
    },
    swot: {
      strengths: [
        "Largest cooperative bank in Malaysia with 10M+ members",
        "Strong personal financing franchise",
        "Extensive branch network in rural and semi-urban areas",
        "Government-backed cooperative structure",
      ],
      weaknesses: [
        "Higher NPL ratio than commercial banks",
        "Concentration in personal financing segment",
        "Limited digital capabilities",
        "Cooperative governance structure",
      ],
      opportunities: [
        "Digital transformation and mobile banking",
        "Expansion of housing and SME financing",
        "Financial inclusion in underserved areas",
        "Islamic banking product expansion",
      ],
      threats: [
        "Regulatory scrutiny on personal financing",
        "Economic downturn affecting consumer repayment",
        "Competition from digital lenders",
        "Interest rate and margin pressure",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Bank Rakyat has grown steadily as Malaysia's largest cooperative bank, serving members through personal financing and housing loans, with assets exceeding MYR 120 billion." },
      { tag: "strategy", tagLabel: "Strategy", text: "The bank focuses on member-centric cooperative banking, balancing financial inclusion with sustainable returns, while investing in digital channels to serve its large member base." },
      { tag: "risk", tagLabel: "Risk", text: "Personal financing concentration and higher NPL ratio require ongoing monitoring; the cooperative structure and government linkage provide stability during stress periods." },
      { tag: "market", tagLabel: "Market", text: "Bank Rakyat occupies a unique position bridging cooperative banking and consumer finance, serving a large member base often underserved by commercial banks." },
    ],
    risks: [
      { name: "Credit Risk", level: 55, color: "var(--amber)" },
      { name: "Operational Risk", level: 48, color: "var(--cyan)" },
      { name: "Regulatory Risk", level: 52, color: "var(--cyan)" },
      { name: "Concentration Risk", level: 58, color: "var(--amber)" },
      { name: "Reputation Risk", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Bank Rakyat plays a vital role in Malaysian financial inclusion as the largest cooperative bank. While not listed, it remains systemically important. Asset quality and digital transformation progress are key factors for its continued stability and member value.",
    },
  },

  BSN: {
    name: "Bank Simpanan Nasional",
    ticker: "BSN",
    entityType: "government",
    sector: "Banking & Finance",
    industry: "Savings Bank",
    hq: "Kuala Lumpur, Malaysia",
    employees: "8,500",
    founded: 1974,
    ceo: "Datuk Ahmad Lai bin Ahmad",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 3.2B",
    kpis: [
      { label: "Total Revenue", value: "MYR 3.2B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 272M", sub: "FY24" },
      { label: "Total Assets", value: "MYR 42B", sub: "As at FY24" },
      { label: "Savings Accounts", value: "12.5M", sub: "Account holders" },
      { label: "NPL Ratio", value: "3.2%", sub: "Gross NPL" },
      { label: "Branches", value: "382", sub: "Nationwide network" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.6, 2.8, 2.9, 3.0, 3.2, 3.4],
      netIncome: [0.18, 0.22, 0.24, 0.26, 0.272, 0.29],
      grossMargin: [32, 33, 34, 35, 36, 37],
      operatingMargin: [18, 19, 20, 21, 22, 23],
      netMargin: [6.9, 7.9, 8.3, 8.7, 8.5, 8.5],
    },
    segments: {
      labels: ["Savings", "Personal Financing", "Housing Loans", "Micro Financing", "Others"],
      values: [40, 25, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["BSN", "Bank Rakyat", "Agrobank", "Bank Islam", "Maybank"],
      revenue: [3.2, 8.5, 4.5, 5.2, 32.5],
      margin: [8.5, 14.1, 12.2, 18.5, 28.6],
    },
    swot: {
      strengths: [
        "Government-owned with implicit sovereign support",
        "Extensive reach in rural and underserved areas",
        "Focus on financial inclusion and savings culture",
        "Affordable housing and micro-financing programs",
      ],
      weaknesses: [
        "Lower profitability than commercial banks",
        "Legacy systems and operational efficiency",
        "Limited product sophistication",
        "Dependence on government policy direction",
      ],
      opportunities: [
        "Digital savings and payment solutions",
        "Government social welfare distribution",
        "Affordable housing financing expansion",
        "Financial literacy programs",
      ],
      threats: [
        "Competition from digital banks",
        "Economic stress affecting target segment",
        "Budget constraints on government support",
        "Regulatory compliance requirements",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "BSN has maintained steady growth as Malaysia's national savings bank, focusing on deposit mobilization and affordable financing for the mass market and civil servants." },
      { tag: "strategy", tagLabel: "Strategy", text: "The bank's mandate centers on financial inclusion, promoting savings culture and providing access to credit for underserved segments, aligned with government social objectives." },
      { tag: "risk", tagLabel: "Risk", text: "As a government entity, BSN benefits from sovereign support; asset quality in personal and micro-financing segments requires monitoring through economic cycles." },
      { tag: "market", tagLabel: "Market", text: "BSN occupies a unique developmental banking role, complementing commercial banks by serving segments that may not meet conventional banking criteria." },
    ],
    risks: [
      { name: "Credit Risk", level: 52, color: "var(--cyan)" },
      { name: "Operational Risk", level: 55, color: "var(--amber)" },
      { name: "Strategic Risk", level: 48, color: "var(--cyan)" },
      { name: "Funding Risk", level: 38, color: "var(--green)" },
      { name: "Reputation Risk", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "BSN continues to fulfill its developmental mandate as Malaysia's savings bank. Government ownership provides stability. Key focus areas include digital transformation and operational efficiency while maintaining financial inclusion objectives.",
    },
  },

  MBSB: {
    name: "Malaysia Building Society Berhad",
    ticker: "MBSB",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Development Finance / Housing",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,800",
    founded: 1950,
    ceo: "Datuk Nor Azam M. Taib",
    price: 0.92,
    change: -0.01,
    changePct: -1.08,
    marketCap: "MYR 6.8B",
    peRatio: 9.5,
    divYield: "2.2%",
    beta: 1.28,
    revenue52w: "MYR 3.5B",
    kpis: [
      { label: "Total Revenue", value: "MYR 3.5B", sub: "FY24 annual" },
      { label: "Net Income", value: "MYR 715M", sub: "FY24" },
      { label: "Total Assets", value: "MYR 52B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "2.8%", sub: "Gross NPL" },
      { label: "ROE", value: "10.5%", sub: "Return on equity" },
      { label: "CAR", value: "16.2%", sub: "Capital adequacy ratio" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.8, 3.0, 3.2, 3.3, 3.5, 3.7],
      netIncome: [0.45, 0.55, 0.62, 0.68, 0.715, 0.78],
      grossMargin: [40, 42, 43, 44, 45, 46],
      operatingMargin: [28, 30, 31, 32, 33, 34],
      netMargin: [16.1, 18.3, 19.4, 20.6, 20.4, 21.1],
    },
    segments: {
      labels: ["Retail Financing", "Corporate Financing", "Islamic Financing", "Investment", "Others"],
      values: [50, 25, 18, 4, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MBSB", "Bank Rakyat", "BSN", "Cagamas", "Maybank"],
      revenue: [3.5, 8.5, 3.2, 1.5, 32.5],
      margin: [20.4, 14.1, 8.5, 25.0, 28.6],
    },
    swot: {
      strengths: [
        "Specialized in retail and corporate financing",
        "Strong housing and property financing expertise",
        "Islamic banking capabilities through MBSB Bank",
        "Transformation from building society to full-fledged bank",
      ],
      weaknesses: [
        "Higher NPL ratio than top-tier banks",
        "Smaller scale limits competitive positioning",
        "Concentration in property-related lending",
        "Limited branch network",
      ],
      opportunities: [
        "Housing affordability financing programs",
        "SME and corporate financing growth",
        "Digital banking expansion",
        "Government housing initiatives partnership",
      ],
      threats: [
        "Property market volatility",
        "Interest rate sensitivity",
        "Competition from larger banks",
        "Regulatory capital requirements",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "MBSB has successfully transformed into a full-fledged Islamic bank, delivering improving profitability through retail and corporate financing growth post-merger with Asian Finance Bank." },
      { tag: "strategy", tagLabel: "Strategy", text: "The group focuses on sustainable financing growth, particularly in housing and retail segments, while strengthening its Islamic banking franchise and digital capabilities." },
      { tag: "risk", tagLabel: "Risk", text: "Asset quality has improved but remains above industry average; property sector exposure requires monitoring given market cyclicality." },
      { tag: "market", tagLabel: "Market", text: "MBSB offers a differentiated profile as a development finance-focused bank, trading at a discount to larger peers with potential for re-rating on sustained improvement." },
    ],
    risks: [
      { name: "Credit Risk", level: 52, color: "var(--cyan)" },
      { name: "Market Risk", level: 55, color: "var(--amber)" },
      { name: "Property Risk", level: 58, color: "var(--amber)" },
      { name: "Operational Risk", level: 48, color: "var(--cyan)" },
      { name: "Competitive Risk", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "MBSB presents a turnaround story with improving fundamentals post-bank transformation. Valuation appears reasonable but property sector exposure and competitive dynamics warrant caution. Suitable for investors seeking higher-risk, higher-potential banking exposure.",
    },
  },

  BNM: {
    name: "Bank Negara Malaysia",
    ticker: "BNM",
    entityType: "government",
    sector: "Banking & Finance",
    industry: "Central Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,400",
    founded: 1959,
    ceo: "Datuk Abdul Rasheed Ghaffour",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 18.5B",
    kpis: [
      { label: "Foreign Reserves", value: "MYR 480B", sub: "As at Dec 2024" },
      { label: "Policy Rate", value: "3.00%", sub: "Overnight Policy Rate" },
      { label: "Total Assets", value: "MYR 520B", sub: "Central bank balance sheet" },
      { label: "Currency in Circulation", value: "MYR 145B", sub: "Ringgit notes and coins" },
      { label: "Banking System NPL", value: "1.6%", sub: "Industry gross NPL" },
      { label: "Ringgit Stability", value: "Managed float", sub: "Exchange rate regime" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [14.2, 15.5, 16.8, 17.5, 18.5, 19.0],
      netIncome: [5.2, 6.0, 6.5, 6.8, 7.2, 7.5],
      grossMargin: [65, 66, 67, 68, 69, 70],
      operatingMargin: [55, 56, 57, 58, 59, 60],
      netMargin: [36.6, 38.7, 38.7, 38.9, 38.9, 39.5],
    },
    segments: {
      labels: ["Monetary Operations", "Foreign Reserves", "Currency Issue", "Financial Stability", "Others"],
      values: [35, 30, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["BNM", "MAS", "BSP", "BOT", "BI"],
      revenue: [18.5, 2.2, 8.5, 6.2, 12.5],
      margin: [38.9, 25.0, 35.0, 32.0, 28.0],
    },
    swot: {
      strengths: [
        "Strong foreign reserves of ~MYR 480B",
        "Credible monetary policy framework",
        "Effective financial sector supervision",
        "Sovereign mandate and independence",
      ],
      weaknesses: [
        "Limited tools in open economy with capital flows",
        "Ringgit volatility during risk-off episodes",
        "Balancing growth and inflation objectives",
        "Dependence on government fiscal coordination",
      ],
      opportunities: [
        "Digital currency and payment system innovation",
        "Sustainable finance regulatory leadership",
        "Regional financial cooperation",
        "Financial inclusion through regulatory sandbox",
      ],
      threats: [
        "Global monetary policy divergence",
        "Capital flow volatility",
        "Geopolitical and trade uncertainties",
        "Domestic fiscal sustainability",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "BNM manages Malaysia's monetary policy and financial stability, with foreign reserves providing substantial buffer against external shocks and supporting ringgit stability." },
      { tag: "strategy", tagLabel: "Strategy", text: "The central bank balances price stability, sustainable growth, and financial system resilience through the OPR framework, macroprudential tools, and proactive supervision." },
      { tag: "risk", tagLabel: "Risk", text: "Key risks include external sector vulnerability to capital flows and global monetary conditions; reserves adequacy and policy credibility remain strengths." },
      { tag: "market", tagLabel: "Market", text: "As Malaysia's central bank, BNM is the cornerstone of financial system stability, with its policy decisions directly impacting banking sector profitability and economic growth." },
    ],
    risks: [
      { name: "External Sector Risk", level: 55, color: "var(--amber)" },
      { name: "Monetary Policy Risk", level: 48, color: "var(--cyan)" },
      { name: "Financial Stability Risk", level: 42, color: "var(--cyan)" },
      { name: "Operational Risk", level: 35, color: "var(--green)" },
      { name: "Reputation Risk", level: 38, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Bank Negara Malaysia maintains a credible monetary policy framework and strong reserves position. As a non-investable government entity, the focus is on its effectiveness in supporting economic stability and the health of the financial sector it regulates.",
    },
  },

  PNB: {
    name: "Permodalan Nasional Berhad",
    ticker: "PNB",
    entityType: "statutory",
    sector: "GLICs",
    industry: "Asset Management / Investment",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,200",
    founded: 1978,
    ceo: "Ahmad Zulqarnain Onn",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 22.5B",
    kpis: [
      { label: "AUM", value: "MYR 370B", sub: "Total assets under management" },
      { label: "Unit Holders", value: "14.5M", sub: "ASB, ASN, ASW2020 etc." },
      { label: "Portfolio Return", value: "5.2%", sub: "FY24 gross return" },
      { label: "Equity Holdings", value: "MYR 280B", sub: "Listed equity portfolio" },
      { label: "Dividend Payout", value: "MYR 12.5B", sub: "FY24 to unit holders" },
      { label: "Market Share", value: "~12%", sub: "Bursa Malaysia market cap" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [18.5, 20.2, 21.0, 21.8, 22.5, 23.5],
      netIncome: [8.5, 9.2, 9.5, 9.8, 10.2, 10.5],
      grossMargin: [58, 59, 60, 61, 62, 63],
      operatingMargin: [48, 49, 50, 51, 52, 53],
      netMargin: [45.9, 45.5, 45.2, 45.0, 45.3, 44.7],
    },
    segments: {
      labels: ["ASB", "ASN/ASB Fixed Price", "Equity Funds", "Real Estate", "Others"],
      values: [45, 25, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["PNB", "EPF", "Khazanah", "KWAP", "LTAT"],
      revenue: [22.5, 65.0, 8.5, 12.0, 4.5],
      margin: [45.3, 42.0, 35.0, 38.0, 32.0],
    },
    swot: {
      strengths: [
        "Largest Bumiputera asset manager with MYR 370B AUM",
        "Manages iconic ASB and ASN unit trust funds",
        "Significant equity stakes in key Malaysian corporates",
        "Government-linked statutory body with policy mandate",
      ],
      weaknesses: [
        "Concentration in Malaysian equity market",
        "Fixed-price fund guarantees create liability",
        "Limited global diversification",
        "Policy objectives may conflict with pure returns",
      ],
      opportunities: [
        "Global asset diversification",
        "Sustainable and ESG investing",
        "Digital platform for unit holders",
        "Private equity and alternative investments",
      ],
      threats: [
        "Malaysian equity market volatility",
        "Low interest rate environment",
        "Unit holder redemption pressure",
        "Regulatory and governance scrutiny",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "PNB has grown to manage MYR 370 billion in assets, serving 14.5 million unit holders through ASB, ASN and other funds, with significant influence on Malaysian capital markets." },
      { tag: "strategy", tagLabel: "Strategy", text: "The institution balances Bumiputera wealth creation mandate with investment returns, maintaining large stakes in strategic companies while pursuing portfolio optimization." },
      { tag: "risk", tagLabel: "Risk", text: "Concentration in domestic equity and fixed-price fund structures create unique risk profiles; diversification efforts and governance improvements are ongoing priorities." },
      { tag: "market", tagLabel: "Market", text: "PNB is a dominant institutional investor in Malaysia, with holdings across banking, plantations, utilities and property that influence corporate governance and market dynamics." },
    ],
    risks: [
      { name: "Market Risk", level: 58, color: "var(--amber)" },
      { name: "Liquidity Risk", level: 52, color: "var(--cyan)" },
      { name: "Concentration Risk", level: 55, color: "var(--amber)" },
      { name: "Governance Risk", level: 48, color: "var(--cyan)" },
      { name: "Reputation Risk", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "PNB remains a cornerstone of Bumiputera wealth creation in Malaysia. As a statutory body, its performance directly impacts millions of unit holders. Diversification and governance improvements will be key to sustaining long-term value.",
    },
  },

  KHAZANAH: {
    name: "Khazanah Nasional Berhad",
    ticker: "KHAZANAH",
    entityType: "statutory",
    sector: "GLICs",
    industry: "Sovereign Wealth Fund",
    hq: "Kuala Lumpur, Malaysia",
    employees: "180",
    founded: 1993,
    ceo: "Datuk Amirul Feisal Wan Zahir",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Portfolio Value", value: "MYR 180B", sub: "Net assets attributable" },
      { label: "Realizable Asset Value", value: "MYR 136B", sub: "RAV as at FY23" },
      { label: "Debt", value: "MYR 48B", sub: "Total borrowings" },
      { label: "Dividend to Government", value: "MYR 1.5B", sub: "FY24" },
      { label: "5-Year CAGR", value: "6.2%", sub: "Portfolio return" },
      { label: "Strategic Companies", value: "50+", sub: "Investments" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6.5, 7.2, 7.8, 8.2, 8.5, 9.0],
      netIncome: [2.8, 3.2, 3.5, 3.8, 4.0, 4.2],
      grossMargin: [55, 56, 57, 58, 59, 60],
      operatingMargin: [45, 46, 47, 48, 49, 50],
      netMargin: [43.1, 44.4, 44.9, 46.3, 47.1, 46.7],
    },
    segments: {
      labels: ["Strategic Assets", "Financial Assets", "Real Estate", "Healthcare", "Others"],
      values: [40, 30, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Khazanah", "PNB", "EPF", "Temasek", "GIC"],
      revenue: [8.5, 22.5, 65.0, 45.0, 35.0],
      margin: [47.1, 45.3, 42.0, 38.0, 40.0],
    },
    swot: {
      strengths: [
        "Malaysia's sovereign wealth fund with MYR 180B portfolio",
        "Strategic stakes in key national companies",
        "Professional investment management",
        "Government mandate for long-term value creation",
      ],
      weaknesses: [
        "Past losses in some investments",
        "Political scrutiny of investment decisions",
        "Leverage reduces flexibility",
        "Concentration in domestic assets",
      ],
      opportunities: [
        "Global diversification",
        "Technology and healthcare investments",
        "Sustainable and impact investing",
        "Strategic asset optimization",
      ],
      threats: [
        "Global market volatility",
        "Political interference",
        "Currency and geopolitical risks",
        "Liquidity needs for debt servicing",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Khazanah has rebuilt its portfolio to approximately MYR 180 billion in net assets, with a focus on strategic Malaysian companies and selective global investments." },
      { tag: "strategy", tagLabel: "Strategy", text: "The fund pursues a dual mandate of commercial returns and strategic development, holding stakes in Axiata, CIMB, IHH Healthcare, Malaysia Airlines and other key assets." },
      { tag: "risk", tagLabel: "Risk", text: "Leverage and past restructuring have increased scrutiny; the fund has improved governance and transparency while managing portfolio concentration and liquidity." },
      { tag: "market", tagLabel: "Market", text: "As Malaysia's sovereign wealth fund, Khazanah influences corporate Malaysia through its strategic holdings and has increasingly focused on sustainable and responsible investing." },
    ],
    risks: [
      { name: "Market Risk", level: 55, color: "var(--amber)" },
      { name: "Political Risk", level: 58, color: "var(--amber)" },
      { name: "Liquidity Risk", level: 52, color: "var(--cyan)" },
      { name: "Concentration Risk", level: 55, color: "var(--amber)" },
      { name: "Governance Risk", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Khazanah continues to play a vital role as Malaysia's sovereign wealth fund. Portfolio restructuring and governance improvements have strengthened its position. Long-term performance will depend on strategic execution and maintaining independence.",
    },
  },

  TABUNGHAJI: {
    name: "Lembaga Tabung Haji",
    ticker: "TABUNGHAJI",
    entityType: "statutory",
    sector: "Plantation",
    industry: "Pilgrimage Fund / Investment",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,500",
    founded: 1963,
    ceo: "Datuk Seri Syed Hamadah Syed Othman",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 4.2B",
    kpis: [
      { label: "Total Assets", value: "MYR 82B", sub: "As at FY24" },
      { label: "Depositors", value: "9.5M", sub: "Hajj savers" },
      { label: "Hajj Quota", value: "31,600", sub: "Pilgrims per year" },
      { label: "Investment Return", value: "4.8%", sub: "FY24" },
      { label: "Dividend", value: "4.25%", sub: "FY24 hibah" },
      { label: "Net Asset Value", value: "MYR 78B", sub: "Depositors' funds" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [3.2, 3.5, 3.8, 4.0, 4.2, 4.5],
      netIncome: [0.8, 0.9, 1.0, 1.1, 1.2, 1.3],
      grossMargin: [42, 43, 44, 45, 46, 47],
      operatingMargin: [28, 29, 30, 31, 32, 33],
      netMargin: [25.0, 25.7, 26.3, 27.5, 28.6, 28.9],
    },
    segments: {
      labels: ["Deposits & Savings", "Equity Investments", "Real Estate", "Fixed Income", "Others"],
      values: [45, 25, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Tabung Haji", "BSN", "Bank Rakyat", "EPF", "PNB"],
      revenue: [4.2, 3.2, 8.5, 65.0, 22.5],
      margin: [28.6, 8.5, 14.1, 42.0, 45.3],
    },
    swot: {
      strengths: [
        "Unique mandate for Hajj pilgrimage savings",
        "9.5 million depositors and strong trust",
        "Government-backed statutory body",
        "Integrated Hajj services and travel",
      ],
      weaknesses: [
        "Past governance and investment issues",
        "Concentration in domestic assets",
        "Regulatory constraints on investments",
        "Operational complexity of Hajj services",
      ],
      opportunities: [
        "Digital savings and mobile platform",
        "Shariah-compliant investment expansion",
        "Hajj services improvement",
        "Financial literacy for depositors",
      ],
      threats: [
        "Investment underperformance vs expectations",
        "Regulatory and governance scrutiny",
        "Economic volatility affecting returns",
        "Reputation risk from past issues",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Tabung Haji has stabilized post-restructuring, managing MYR 82 billion in assets for 9.5 million depositors seeking to save for the Hajj pilgrimage." },
      { tag: "strategy", tagLabel: "Strategy", text: "The institution balances its dual mandate of safeguarding depositor funds and facilitating Hajj pilgrimage, with improved governance and more conservative investment approach." },
      { tag: "risk", tagLabel: "Risk", text: "Past investment losses led to government recapitalization; the institution has strengthened risk management and adopted more prudent investment guidelines." },
      { tag: "market", tagLabel: "Market", text: "Tabung Haji occupies a unique position in Malaysian Islamic finance, serving a social and religious purpose while managing substantial depositor funds." },
    ],
    risks: [
      { name: "Investment Risk", level: 55, color: "var(--amber)" },
      { name: "Governance Risk", level: 52, color: "var(--cyan)" },
      { name: "Reputation Risk", level: 58, color: "var(--amber)" },
      { name: "Operational Risk", level: 48, color: "var(--cyan)" },
      { name: "Liquidity Risk", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Tabung Haji has made progress in governance and financial stability following its restructuring. As a statutory body serving millions of Muslims, its continued prudent management is essential for depositor confidence and social stability.",
    },
  },
});
