Object.assign(COMPANIES, {
  TNB: {
    name: "Tenaga Nasional Berhad",
    ticker: "TNB",
    entityType: "public",
    sector: "Utilities",
    industry: "Electric Power Generation & Distribution",
    hq: "Kuala Lumpur, Malaysia",
    employees: "35,000",
    founded: 1990,
    ceo: "Dato' Seri Ir. Baharin Din",
    price: 14.20,
    change: 0.15,
    changePct: 1.07,
    marketCap: "MYR 90.2B",
    peRatio: 12.5,
    divYield: "4.2%",
    beta: 0.85,
    revenue52w: "MYR 56.2B",
    kpis: [
      { label: "Revenue", value: "MYR 56.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 4.8B", sub: "FY24" },
      { label: "Total Assets", value: "MYR 180B", sub: "FY24" },
      { label: "Grid Capacity", value: "28 GW", sub: "Installed" },
      { label: "Customers", value: "9.2M", sub: "Peninsular Malaysia" },
      { label: "ROE", value: "8.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [52000, 53000, 54000, 55200, 56200, 57800],
      netIncome: [4200, 4500, 3800, 4200, 4800, 5100],
      grossMargin: [18, 19, 17, 18, 19, 19],
      operatingMargin: [12, 13, 11, 12, 13, 13],
      netMargin: [8.1, 8.5, 7.0, 7.6, 8.5, 8.8],
    },
    segments: {
      labels: ["Generation", "Transmission", "Distribution", "Retail", "Others"],
      values: [35, 25, 28, 10, 2],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["TNB", "SESB", "Sarawak Energy", "TNB Renewables", "IPP Players"],
      revenue: [56200, 2800, 4500, 1200, 8000],
      margin: [8.5, 2.1, 5.2, 6.8, 4.5],
    },
    swot: {
      strengths: ["Monopoly over peninsular grid", "Strong cash flow from regulated assets", "Diversifying into renewables", "Government backing"],
      weaknesses: ["Heavy capex for grid upgrades", "Fuel cost volatility", "Regulatory lag in tariff adjustments"],
      opportunities: ["EV charging infrastructure", "Data center power demand", "ASEAN grid interconnection"],
      threats: ["Renewable disruption", "Fuel price spikes", "Regulatory intervention"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "TNB is investing MYR 20B+ in grid modernization and renewables; data center demand in Johor driving new capacity." },
      { tag: "strategy", tagLabel: "Strategy", text: "Pivoting to green energy while maintaining grid reliability; expanding EV charging network nationwide." },
      { tag: "risk", tagLabel: "Risk", text: "Fuel cost pass-through mechanism provides some protection; regulatory changes could impact returns." },
      { tag: "market", tagLabel: "Market", text: "Dominant utility with stable dividends; defensive play in volatile markets." },
    ],
    risks: [
      { name: "Regulatory", level: 35, color: "var(--green)" },
      { name: "Fuel Cost", level: 48, color: "var(--cyan)" },
      { name: "Capex", level: 52, color: "var(--cyan)" },
      { name: "Competition", level: 25, color: "var(--green)" },
      { name: "ESG", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "TNB remains the backbone of Malaysia's power sector with stable earnings and attractive yield. Grid upgrades and data center demand support medium-term growth. Regulatory clarity on ICPT mechanism is key.",
    },
  },
  AIRSELANGOR: {
    name: "Pengurusan Air Selangor Sdn Bhd",
    ticker: "AIRSELANGOR",
    entityType: "government",
    sector: "Utilities",
    industry: "Water Supply & Treatment",
    hq: "Shah Alam, Malaysia",
    employees: "4,200",
    founded: 2005,
    ceo: "Suhaimi Kamaralzaman",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 2.8B",
    kpis: [
      { label: "Revenue", value: "MYR 2.8B", sub: "FY24" },
      { label: "Customers", value: "7.8M", sub: "Selangor/KL" },
      { label: "Water Treated", value: "4.2B L/day", sub: "Capacity" },
      { label: "NRW", value: "28%", sub: "Non-revenue water" },
      { label: "Coverage", value: "99%", sub: "Selangor" },
      { label: "Plants", value: "33", sub: "Treatment plants" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2400, 2500, 2600, 2700, 2800, 2950],
      netIncome: [120, 130, 140, 150, 160, 175],
      grossMargin: [35, 36, 36, 37, 37, 38],
      operatingMargin: [8, 8.5, 9, 9.5, 10, 10.5],
      netMargin: [5.0, 5.2, 5.4, 5.6, 5.7, 5.9],
    },
    segments: {
      labels: ["Water Supply", "Sewerage", "Bulk Water", "Retail", "Others"],
      values: [65, 20, 10, 3, 2],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Air Selangor", "SPAN", "SAJ", "PBAPP", "Lembaga Air Perak"],
      revenue: [2800, 0, 450, 380, 320],
      margin: [5.7, 0, 4.2, 4.8, 3.5],
    },
    swot: {
      strengths: ["Monopoly in Selangor/KL", "Government ownership", "Large customer base", "Ongoing NRW reduction"],
      weaknesses: ["High NRW vs regional peers", "Aging infrastructure", "Limited tariff flexibility"],
      opportunities: ["RAS projects", "Smart metering", "Industrial water recycling"],
      threats: ["Climate/drought risk", "Pollution incidents", "Political interference"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "RAS2 and Langat 2 expansion to meet growing demand; NRW target of 25% by 2025." },
      { tag: "strategy", tagLabel: "Strategy", text: "Investing in digital meters and pipe replacement; exploring industrial reuse." },
      { tag: "risk", tagLabel: "Risk", text: "Drought and raw water quality events can disrupt supply; tariff reviews politically sensitive." },
      { tag: "market", tagLabel: "Market", text: "Essential service provider for Malaysia's most populous state; stable demand profile." },
    ],
    risks: [
      { name: "Regulatory", level: 42, color: "var(--cyan)" },
      { name: "Operational", level: 38, color: "var(--green)" },
      { name: "Climate", level: 58, color: "var(--amber)" },
      { name: "Funding", level: 45, color: "var(--cyan)" },
      { name: "Political", level: 50, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Air Selangor is critical infrastructure for Selangor and KL. NRW reduction and RAS projects support efficiency gains. Non-listed government entity with limited visibility.",
    },
  },
  GASMSIA: {
    name: "Gas Malaysia Berhad",
    ticker: "GASMSIA",
    entityType: "public",
    sector: "Utilities",
    industry: "Natural Gas Distribution",
    hq: "Shah Alam, Malaysia",
    employees: "1,100",
    founded: 1992,
    ceo: "Ahmad Hashimi Abdul Manap",
    price: 3.85,
    change: 0.08,
    changePct: 2.12,
    marketCap: "MYR 4.8B",
    peRatio: 14.2,
    divYield: "5.2%",
    beta: 0.72,
    revenue52w: "MYR 5.2B",
    kpis: [
      { label: "Revenue", value: "MYR 5.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 340M", sub: "FY24" },
      { label: "Gas Sold", value: "145 mmscfd", sub: "Volume" },
      { label: "Customers", value: "1,800+", sub: "Industrial/Commercial" },
      { label: "Pipeline", value: "2,200 km", sub: "Network" },
      { label: "ROE", value: "12.1%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4200, 4500, 4800, 5000, 5200, 5450],
      netIncome: [280, 300, 310, 320, 340, 360],
      grossMargin: [12, 12, 11, 11, 12, 12],
      operatingMargin: [8, 8.5, 8.2, 8.5, 9, 9.2],
      netMargin: [6.7, 6.7, 6.5, 6.4, 6.5, 6.6],
    },
    segments: {
      labels: ["Gas Distribution", "Retail", "Pipeline", "Metering", "Others"],
      values: [70, 15, 8, 4, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Gas Malaysia", "Petronas Gas", "SGD", "Sabah Gas", "Sarawak Gas"],
      revenue: [5200, 6200, 800, 350, 280],
      margin: [6.5, 35, 5.2, 4.1, 3.8],
    },
    swot: {
      strengths: ["Dominant peninsular gas distributor", "Stable regulated returns", "Growing industrial demand", "Strong dividend"],
      weaknesses: ["Gas price pass-through limits margin", "Concentration in Peninsular", "Transition risk to renewables"],
      opportunities: ["LNG/CNG expansion", "Industrial park growth", "Hydrogen blending"],
      threats: ["Renewable substitution", "Gas price volatility", "Regulatory changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Industrial demand in Johor and Selangor driving volume growth; LNG regas capacity expansion." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on reliability and customer retention; exploring hydrogen-ready infrastructure." },
      { tag: "risk", tagLabel: "Risk", text: "Regulated business with predictable cash flows; gas price volatility managed via pass-through." },
      { tag: "market", tagLabel: "Market", text: "Yield play with defensive characteristics; industrial recovery supports volume." },
    ],
    risks: [
      { name: "Regulatory", level: 38, color: "var(--green)" },
      { name: "Gas Price", level: 52, color: "var(--cyan)" },
      { name: "Demand", level: 42, color: "var(--cyan)" },
      { name: "Transition", level: 58, color: "var(--amber)" },
      { name: "Competition", level: 30, color: "var(--green)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Gas Malaysia offers attractive yield with stable earnings. Industrial gas demand remains robust. Transition risk to renewables is long-dated.",
    },
  },
  KUMH: {
    name: "Kelantan Utilities Mubaarakan Holdings Sdn. Bhd",
    ticker: "KUMH",
    entityType: "private",
    sector: "Utilities",
    industry: "Water Supply",
    hq: "Kota Bharu, Malaysia",
    employees: "850",
    founded: 2008,
    ceo: "Ahmad Fadzil Abdul Rahman",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 420M",
    kpis: [
      { label: "Revenue", value: "MYR 420M", sub: "FY24" },
      { label: "Customers", value: "650K", sub: "Kelantan" },
      { label: "Water Treated", value: "450 MLD", sub: "Capacity" },
      { label: "NRW", value: "35%", sub: "Non-revenue water" },
      { label: "Coverage", value: "92%", sub: "State" },
      { label: "Plants", value: "12", sub: "Treatment plants" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [350, 370, 385, 400, 420, 440],
      netIncome: [15, 18, 20, 22, 25, 28],
      grossMargin: [28, 29, 30, 30, 31, 31],
      operatingMargin: [6, 6.5, 6.8, 7, 7.2, 7.5],
      netMargin: [4.3, 4.9, 5.2, 5.5, 6.0, 6.4],
    },
    segments: {
      labels: ["Water Supply", "Bulk", "Retail", "Sewerage", "Others"],
      values: [75, 12, 8, 3, 2],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["KUMH", "SAINS", "Air Kelantan", "Lembaga Air", "State utilities"],
      revenue: [420, 0, 0, 0, 0],
      margin: [6.0, 0, 0, 0, 0],
    },
    swot: {
      strengths: ["Sole water operator in Kelantan", "State support", "Improving NRW", "Rural coverage expansion"],
      weaknesses: ["High NRW", "Limited funding", "Aging assets", "Flood-prone region"],
      opportunities: ["Federal grants", "NRW reduction programs", "Smart metering"],
      threats: ["Flood damage", "Raw water quality", "Political changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Rural coverage expansion and NRW reduction initiatives; federal funding for upgrades." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on operational efficiency and asset renewal; seeking federal support for capex." },
      { tag: "risk", tagLabel: "Risk", text: "Flood events in Kelantan can disrupt operations; limited financial flexibility as private entity." },
      { tag: "market", tagLabel: "Market", text: "Regional water utility serving Kelantan; smaller scale than Air Selangor." },
    ],
    risks: [
      { name: "Operational", level: 55, color: "var(--amber)" },
      { name: "Funding", level: 62, color: "var(--amber)" },
      { name: "Climate", level: 68, color: "var(--amber)" },
      { name: "Political", level: 50, color: "var(--cyan)" },
      { name: "Regulatory", level: 40, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "KUMH serves Kelantan's water needs with improving efficiency. Flood risk and funding constraints remain challenges. Non-listed private entity.",
    },
  },
  ALTEL: {
    name: "Altel Communications Sdn Bhd",
    ticker: "ALTEL",
    entityType: "private",
    sector: "Technology",
    industry: "Wireless Broadband & Telecommunications",
    hq: "Kuala Lumpur, Malaysia",
    employees: "320",
    founded: 2005,
    ceo: "Datuk Seri Dr. Nik Norzrul Thani",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 180M",
    kpis: [
      { label: "Revenue", value: "MYR 180M", sub: "FY24" },
      { label: "Subscribers", value: "85K", sub: "Wireless broadband" },
      { label: "Coverage", value: "Urban + Suburban", sub: "Peninsular" },
      { label: "Spectrum", value: "2.3 GHz", sub: "TD-LTE" },
      { label: "ARPU", value: "MYR 98", sub: "Monthly" },
      { label: "Churn", value: "4.2%", sub: "Monthly" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [140, 155, 165, 172, 180, 195],
      netIncome: [-15, -8, -5, 2, 8, 15],
      grossMargin: [35, 38, 40, 42, 44, 46],
      operatingMargin: [-8, -4, -2, 2, 5, 8],
      netMargin: [-10.7, -5.2, -3.0, 1.2, 4.4, 7.7],
    },
    segments: {
      labels: ["Wireless Broadband", "Enterprise", "Wholesale", "Devices", "Others"],
      values: [65, 20, 8, 5, 2],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Altel", "CelcomDigi", "Maxis", "Unifi", "Yes 4G"],
      revenue: [180, 12000, 9500, 4500, 350],
      margin: [4.4, 12, 18, 22, -5],
    },
    swot: {
      strengths: ["Niche wireless broadband focus", "2.3 GHz spectrum", "Flexible plans", "Enterprise solutions"],
      weaknesses: ["Small scale vs MNOs", "Limited coverage", "Brand awareness", "Capex constraints"],
      opportunities: ["Rural broadband", "FWA growth", "5G wholesale", "IoT"],
      threats: ["MNO competition", "Fiber expansion", "Spectrum costs", "Price war"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Altel targets underserved areas and FWA; 5G wholesale could open new revenue streams." },
      { tag: "strategy", tagLabel: "Strategy", text: "Differentiation through customer service and flexible plans; exploring enterprise IoT." },
      { tag: "risk", tagLabel: "Risk", text: "Competing against well-funded MNOs; spectrum renewal and capex pressure." },
      { tag: "market", tagLabel: "Market", text: "Niche player in Malaysian telecom; FWA and rural demand support relevance." },
    ],
    risks: [
      { name: "Competition", level: 72, color: "var(--red)" },
      { name: "Funding", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 45, color: "var(--cyan)" },
      { name: "Technology", level: 52, color: "var(--cyan)" },
      { name: "Market", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Altel is a niche wireless broadband provider with improving profitability. Scale remains a challenge against larger MNOs. Private entity with limited visibility.",
    },
  },
  TUNEPRO: {
    name: "TuneProtect Group Berhad",
    ticker: "TUNEPRO",
    entityType: "public",
    sector: "Technology",
    industry: "Digital Insurance / Insurtech",
    hq: "Kuala Lumpur, Malaysia",
    employees: "280",
    founded: 2013,
    ceo: "Rohit Nambiar",
    price: 0.42,
    change: 0.02,
    changePct: 5.0,
    marketCap: "MYR 520M",
    peRatio: 18.5,
    divYield: "2.4%",
    beta: 1.15,
    revenue52w: "MYR 380M",
    kpis: [
      { label: "Revenue", value: "MYR 380M", sub: "FY24" },
      { label: "Net Income", value: "MYR 28M", sub: "FY24" },
      { label: "GWP", value: "MYR 420M", sub: "Gross written premium" },
      { label: "Combined Ratio", value: "95%", sub: "FY24" },
      { label: "Digital Mix", value: "65%", sub: "Online sales" },
      { label: "ROE", value: "8.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [280, 300, 320, 350, 380, 420],
      netIncome: [15, 18, 20, 24, 28, 35],
      grossMargin: [22, 23, 24, 25, 26, 27],
      operatingMargin: [8, 9, 9.5, 10, 10.5, 11],
      netMargin: [5.4, 6.0, 6.3, 6.9, 7.4, 8.3],
    },
    segments: {
      labels: ["Travel", "General", "Life", "Takaful", "Others"],
      values: [40, 35, 15, 7, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["TuneProtect", "AIG", "Allianz", "Zurich", "MSIG"],
      revenue: [380, 1200, 1800, 950, 600],
      margin: [7.4, 6.2, 8.5, 7.8, 6.5],
    },
    swot: {
      strengths: ["Digital-first model", "AirAsia ecosystem", "Low-cost structure", "Travel insurance expertise"],
      weaknesses: ["Travel dependency", "Small scale", "Limited product breadth", "Brand recognition"],
      opportunities: ["Embedded insurance", "SME products", "Regional expansion", "Partnerships"],
      threats: ["Travel volatility", "Big tech entry", "Regulatory changes", "Price competition"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Travel recovery boosting GWP; expanding into general and life; embedded insurance partnerships." },
      { tag: "strategy", tagLabel: "Strategy", text: "Digital distribution and low-cost model; diversifying beyond travel." },
      { tag: "risk", tagLabel: "Risk", text: "Travel segment remains cyclical; underwriting discipline key." },
      { tag: "market", tagLabel: "Market", text: "Small-cap insurtech with digital edge; recovery play with growth optionality." },
    ],
    risks: [
      { name: "Travel", level: 62, color: "var(--amber)" },
      { name: "Competition", level: 55, color: "var(--amber)" },
      { name: "Regulatory", level: 42, color: "var(--cyan)" },
      { name: "Underwriting", level: 48, color: "var(--cyan)" },
      { name: "Scale", level: 58, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "TuneProtect benefits from travel recovery and digital distribution. Diversification into general insurance supports medium-term growth. Small cap with re-rating potential.",
    },
  },
  UNISEM: {
    name: "Unisem (M) Berhad",
    ticker: "UNISEM",
    entityType: "public",
    sector: "Technology",
    industry: "Semiconductor Packaging & Testing",
    hq: "Ipoh, Malaysia",
    employees: "8,500",
    founded: 1989,
    ceo: "John Chia",
    price: 4.25,
    change: 0.12,
    changePct: 2.9,
    marketCap: "MYR 6.8B",
    peRatio: 22.5,
    divYield: "1.8%",
    beta: 1.25,
    revenue52w: "MYR 1.85B",
    kpis: [
      { label: "Revenue", value: "MYR 1.85B", sub: "FY24" },
      { label: "Net Income", value: "MYR 302M", sub: "FY24" },
      { label: "Wafer Bumps", value: "High volume", sub: "Core product" },
      { label: "Capacity", value: "Expanding", sub: "Chengdu + Ipoh" },
      { label: "Export %", value: "92%", sub: "Of revenue" },
      { label: "ROE", value: "14.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1200, 1500, 1650, 1750, 1850, 2050],
      netIncome: [120, 220, 280, 290, 302, 350],
      grossMargin: [22, 28, 30, 30, 31, 31],
      operatingMargin: [12, 18, 20, 20, 20, 21],
      netMargin: [10.0, 14.7, 17.0, 16.6, 16.3, 17.1],
    },
    segments: {
      labels: ["Wafer Bumping", "Packaging", "Testing", "RF", "Others"],
      values: [45, 25, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Unisem", "Inari", "MPI", "ViTrox", "ASE"],
      revenue: [1850, 1200, 800, 650, 0],
      margin: [16.3, 18, 12, 25, 0],
    },
    swot: {
      strengths: ["Strong wafer bumping capability", "US/China customer base", "Chengdu + Ipoh footprint", "Automotive exposure"],
      weaknesses: ["Cyclical industry", "Concentration risk", "Capex intensive", "Currency exposure"],
      opportunities: ["EV/automotive growth", "AI chip packaging", "Capacity expansion", "Advanced packaging"],
      threats: ["Semiconductor cycle", "US-China tensions", "Competition", "Raw material costs"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Automotive and industrial demand driving growth; capacity expansion in Ipoh and Chengdu." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on wafer-level packaging and RF; diversifying customer base." },
      { tag: "risk", tagLabel: "Risk", text: "Semiconductor cycle and geopolitical risks; US export controls on China operations." },
      { tag: "market", tagLabel: "Market", text: "Key Malaysian semiconductor exporter; beneficiary of supply chain diversification." },
    ],
    risks: [
      { name: "Cycle", level: 65, color: "var(--amber)" },
      { name: "Geopolitical", level: 58, color: "var(--amber)" },
      { name: "Customer", level: 48, color: "var(--cyan)" },
      { name: "Currency", level: 42, color: "var(--cyan)" },
      { name: "Competition", level: 52, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Unisem is well-positioned in semiconductor packaging with automotive and industrial exposure. Cycle recovery and capacity expansion support earnings. Geopolitical risk on China ops to monitor.",
    },
  },
  VITROX: {
    name: "ViTrox Corporation Berhad",
    ticker: "VITROX",
    entityType: "public",
    sector: "Technology",
    industry: "Machine Vision & Semiconductor Test Equipment",
    hq: "Bayan Lepas, Malaysia",
    employees: "1,800",
    founded: 2000,
    ceo: "Chu Jenn Weng",
    price: 8.95,
    change: 0.35,
    changePct: 4.07,
    marketCap: "MYR 10.2B",
    peRatio: 58.5,
    divYield: "0.6%",
    beta: 1.35,
    revenue52w: "MYR 650M",
    kpis: [
      { label: "Revenue", value: "MYR 650M", sub: "FY24" },
      { label: "Net Income", value: "MYR 174M", sub: "FY24" },
      { label: "AOI Systems", value: "Core product", sub: "Automated optical inspection" },
      { label: "R&D %", value: "12%", sub: "Of revenue" },
      { label: "Export %", value: "95%", sub: "Of revenue" },
      { label: "ROE", value: "22.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [380, 480, 550, 600, 650, 780],
      netIncome: [85, 120, 150, 165, 174, 220],
      grossMargin: [55, 58, 60, 61, 62, 62],
      operatingMargin: [28, 32, 35, 36, 37, 38],
      netMargin: [22.4, 25.0, 27.3, 27.5, 26.8, 28.2],
    },
    segments: {
      labels: ["AOI", "MVS", "Bonding", "Software", "Others"],
      values: [55, 25, 12, 5, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["ViTrox", "Koh Young", "Camtek", "Nordson", "CyberOptics"],
      revenue: [650, 450, 380, 0, 0],
      margin: [26.8, 18, 22, 0, 0],
    },
    swot: {
      strengths: ["Leading AOI technology", "High margins", "Strong R&D", "Global customer base"],
      weaknesses: ["Premium valuation", "Semiconductor cycle", "Customer concentration", "Limited dividend"],
      opportunities: ["Advanced packaging", "EV electronics", "AI chip demand", "Expansion"],
      threats: ["Cycle downturn", "Competition", "Tech disruption", "Supply chain"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "High-growth tech darling; AOI demand from advanced packaging and EV electronics driving expansion." },
      { tag: "strategy", tagLabel: "Strategy", text: "R&D-led differentiation; expanding product range and geographic reach." },
      { tag: "risk", tagLabel: "Risk", text: "P/E ~60 reflects high expectations; semiconductor cycle could compress multiples." },
      { tag: "market", tagLabel: "Market", text: "Malaysia's premium tech stock; quality growth company with global competitiveness." },
    ],
    risks: [
      { name: "Valuation", level: 75, color: "var(--red)" },
      { name: "Cycle", level: 58, color: "var(--amber)" },
      { name: "Competition", level: 48, color: "var(--cyan)" },
      { name: "Customer", level: 45, color: "var(--cyan)" },
      { name: "Technology", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "ViTrox is a high-quality tech company with strong margins and growth. Valuation is demanding at P/E ~60; suitable for growth investors with long horizon. Cycle sensitivity to monitor.",
    },
  },
  SILTERRA: {
    name: "SilTerra Malaysia Sdn. Bhd",
    ticker: "SILTERRA",
    entityType: "private",
    sector: "Technology",
    industry: "Wafer Fabrication",
    hq: "Kulim, Malaysia",
    employees: "2,200",
    founded: 1995,
    ceo: "Firdaus Abdullah",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.2B",
    kpis: [
      { label: "Revenue", value: "MYR 1.2B", sub: "FY24" },
      { label: "Wafer Capacity", value: "40K wpm", sub: "8-inch equivalent" },
      { label: "Nodes", value: "0.13um-0.35um", sub: "Mature nodes" },
      { label: "Owner", value: "Dagang NeXchange", sub: "DNeX" },
      { label: "Export %", value: "88%", sub: "Of revenue" },
      { label: "Employees", value: "2,200", sub: "Kulim" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [650, 850, 1000, 1100, 1200, 1350],
      netIncome: [-80, 20, 80, 120, 150, 180],
      grossMargin: [15, 22, 25, 27, 28, 29],
      operatingMargin: [-12, 5, 12, 15, 17, 19],
      netMargin: [-12.3, 2.4, 8.0, 10.9, 12.5, 13.3],
    },
    segments: {
      labels: ["Logic", "Power", "Mixed Signal", "RF", "Others"],
      values: [40, 25, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["SilTerra", "Tower", "UMC", "GlobalFoundries", "SMIC"],
      revenue: [1200, 1200, 0, 0, 0],
      margin: [12.5, 15, 0, 0, 0],
    },
    swot: {
      strengths: ["Only Malaysian wafer fab", "Mature node demand", "DNeX ownership", "Power/RF expertise"],
      weaknesses: ["Mature nodes only", "Capex intensive", "Technology gap", "Customer concentration"],
      opportunities: ["Chip shortage tailwind", "Power/EV chips", "Supply chain diversification", "Expansion"],
      threats: ["China capacity", "Cycle downturn", "Tech obsolescence", "Funding"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Mature node demand from power, automotive, and industrial; DNeX investing in capacity." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on specialty processes; positioning for supply chain diversification." },
      { tag: "risk", tagLabel: "Risk", text: "Wafer fab is capital intensive; cycle and competition from China fabs." },
      { tag: "market", tagLabel: "Market", text: "Strategic asset for Malaysia's semiconductor ecosystem; mature node niche." },
    ],
    risks: [
      { name: "Cycle", level: 62, color: "var(--amber)" },
      { name: "Funding", level: 55, color: "var(--amber)" },
      { name: "Competition", level: 65, color: "var(--amber)" },
      { name: "Technology", level: 52, color: "var(--cyan)" },
      { name: "Customer", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "SilTerra is Malaysia's sole wafer fab with improving profitability under DNeX. Mature node demand supports utilization. Private entity; exposure via DNeX listed shares.",
    },
  },
  INFINEON_MY: {
    name: "Infineon Technologies (Malaysia) Sdn. Bhd",
    ticker: "INFINEON_MY",
    entityType: "private",
    sector: "Technology",
    industry: "Semiconductor Manufacturing",
    hq: "Kulim, Malaysia",
    employees: "9,500",
    founded: 1973,
    ceo: "Elke Eckstein",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Revenue", value: "~MYR 8.5B", sub: "Malaysia ops" },
      { label: "Employees", value: "9,500", sub: "Largest private employer" },
      { label: "Sites", value: "3", sub: "Kulim, Melaka, PG" },
      { label: "Products", value: "Power, Auto", sub: "Core segments" },
      { label: "Export %", value: "98%", sub: "Of output" },
      { label: "Parent", value: "Infineon AG", sub: "Germany" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [5200, 6200, 7200, 7800, 8500, 9200],
      netIncome: [450, 680, 950, 1050, 1150, 1250],
      grossMargin: [38, 42, 45, 46, 47, 47],
      operatingMargin: [18, 24, 28, 29, 30, 30],
      netMargin: [8.7, 11.0, 13.2, 13.5, 13.5, 13.6],
    },
    segments: {
      labels: ["Power", "Automotive", "Industrial", "Connected", "Others"],
      values: [45, 35, 12, 5, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Infineon MY", "ON Semi", "STMicro", "Rohm", "NXP"],
      revenue: [8500, 0, 0, 0, 0],
      margin: [13.5, 0, 0, 0, 0],
    },
    swot: {
      strengths: ["Major global semiconductor hub", "Power/auto leadership", "Parent backing", "Skilled workforce"],
      weaknesses: ["Subsidiary structure", "No standalone listing", "Cycle exposure", "Currency"],
      opportunities: ["EV/solar growth", "Malaysia expansion", "SiC capacity", "Industrial IoT"],
      threats: ["Cycle", "Geopolitics", "Competition", "Talent"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Infineon Malaysia is expanding Kulim for power and SiC; EV and renewable demand driving investment." },
      { tag: "strategy", tagLabel: "Strategy", text: "Key manufacturing base for Infineon AG; Malaysia benefits from FDI and jobs." },
      { tag: "risk", tagLabel: "Risk", text: "Subsidiary of German parent; no direct equity exposure; cycle and geopolitics." },
      { tag: "market", tagLabel: "Market", text: "Critical to Malaysia's E&E ecosystem; major employer and exporter." },
    ],
    risks: [
      { name: "Cycle", level: 55, color: "var(--amber)" },
      { name: "Geopolitical", level: 48, color: "var(--cyan)" },
      { name: "Parent", level: 35, color: "var(--green)" },
      { name: "Talent", level: 45, color: "var(--cyan)" },
      { name: "Competition", level: 50, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Infineon Malaysia is a major semiconductor manufacturing hub. Exposure via Infineon AG (IFX.DE). EV and power semiconductor growth supports long-term outlook.",
    },
  },
  IOI: {
    name: "IOI Corporation Berhad",
    ticker: "IOI",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Palm Oil & Property",
    hq: "Putrajaya, Malaysia",
    employees: "32,000",
    founded: 1982,
    ceo: "Dato' Lee Yeow Chor",
    price: 4.85,
    change: 0.10,
    changePct: 2.11,
    marketCap: "MYR 28.5B",
    peRatio: 18.2,
    divYield: "3.1%",
    beta: 1.05,
    revenue52w: "MYR 18.2B",
    kpis: [
      { label: "Revenue", value: "MYR 18.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 1.57B", sub: "FY24" },
      { label: "Planted Area", value: "230K ha", sub: "Malaysia + Indonesia" },
      { label: "CPO Output", value: "1.1M MT", sub: "FY24" },
      { label: "FFB Yield", value: "21.5 t/ha", sub: "Mature" },
      { label: "ROE", value: "11.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [15000, 18000, 19500, 17200, 18200, 19500],
      netIncome: [850, 1500, 1800, 1200, 1570, 1750],
      grossMargin: [18, 22, 24, 20, 22, 23],
      operatingMargin: [10, 14, 16, 11, 13, 14],
      netMargin: [5.7, 8.3, 9.2, 7.0, 8.6, 9.0],
    },
    segments: {
      labels: ["Plantation", "Refining", "Oleochemical", "Property", "Others"],
      values: [45, 25, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["IOI", "KLK", "SD Guthrie", "FGV", "Sime Darby Oils"],
      revenue: [18200, 25000, 15000, 12000, 8000],
      margin: [8.6, 7.2, 6.5, 4.2, 5.5],
    },
    swot: {
      strengths: ["Integrated value chain", "Strong refining/oleo", "Property earnings", "Sustainability focus"],
      weaknesses: ["CPO price exposure", "Indonesia competition", "Labor issues", "ESG scrutiny"],
      opportunities: ["Biodiesel demand", "Oleo growth", "Property development", "Downstream expansion"],
      threats: ["CPO volatility", "EU deforestation rules", "Labor shortage", "Weather"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Integrated model cushions CPO volatility; oleochemical and refining margins support earnings." },
      { tag: "strategy", tagLabel: "Strategy", text: "Vertical integration from plantation to oleo; property provides diversification." },
      { tag: "risk", tagLabel: "Risk", text: "CPO price and EUDR compliance; labor and ESG key focus areas." },
      { tag: "market", tagLabel: "Market", text: "Quality plantation stock with downstream strength; yield play with growth optionality." },
    ],
    risks: [
      { name: "CPO Price", level: 68, color: "var(--amber)" },
      { name: "ESG", level: 58, color: "var(--amber)" },
      { name: "Labor", level: 55, color: "var(--amber)" },
      { name: "Weather", level: 48, color: "var(--cyan)" },
      { name: "Regulatory", level: 52, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "IOI offers integrated plantation exposure with downstream and property diversification. CPO recovery supports earnings. ESG and EUDR compliance are monitored.",
    },
  },
  KLK: {
    name: "Kuala Lumpur Kepong Berhad",
    ticker: "KLK",
    entityType: "public",
    sector: "Plantation",
    industry: "Plantation & Oleochemicals",
    hq: "Kuala Lumpur, Malaysia",
    employees: "95,000",
    founded: 1906,
    ceo: "Lee Oi Hian",
    price: 22.50,
    change: 0.35,
    changePct: 1.58,
    marketCap: "MYR 24.2B",
    peRatio: 16.8,
    divYield: "2.8%",
    beta: 1.02,
    revenue52w: "MYR 25.0B",
    kpis: [
      { label: "Revenue", value: "MYR 25.0B", sub: "FY24" },
      { label: "Net Income", value: "MYR 1.44B", sub: "FY24" },
      { label: "Planted Area", value: "350K ha", sub: "Malaysia + Indonesia" },
      { label: "CPO Output", value: "1.4M MT", sub: "FY24" },
      { label: "Oleo Capacity", value: "2.5M MT", sub: "Global" },
      { label: "ROE", value: "9.8%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [18000, 22000, 26000, 23000, 25000, 26500],
      netIncome: [650, 1200, 1800, 1100, 1440, 1600],
      grossMargin: [16, 20, 22, 18, 20, 21],
      operatingMargin: [8, 12, 14, 10, 11, 12],
      netMargin: [3.6, 5.5, 6.9, 4.8, 5.8, 6.0],
    },
    segments: {
      labels: ["Plantation", "Oleochemical", "Refining", "Property", "Others"],
      values: [40, 30, 18, 7, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["KLK", "IOI", "SD Guthrie", "FGV", "Wilmar"],
      revenue: [25000, 18200, 15000, 12000, 0],
      margin: [5.8, 8.6, 6.5, 4.2, 0],
    },
    swot: {
      strengths: ["Large planted area", "Global oleo leader", "Diversified geography", "Long track record"],
      weaknesses: ["CPO dependency", "Oleo margin pressure", "Labor intensive", "ESG"],
      opportunities: ["Specialty oleo", "Biodiesel", "Indonesia expansion", "Sustainability premium"],
      threats: ["CPO volatility", "EUDR", "Competition", "Input costs"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Oleochemical segment provides downstream cushion; specialty products support margins." },
      { tag: "strategy", tagLabel: "Strategy", text: "Integrated plantation to oleo; global manufacturing footprint." },
      { tag: "risk", tagLabel: "Risk", text: "CPO and oleo margins cyclical; EUDR and labor challenges." },
      { tag: "market", tagLabel: "Market", text: "Blue-chip plantation with oleo diversification; defensive yield play." },
    ],
    risks: [
      { name: "CPO Price", level: 65, color: "var(--amber)" },
      { name: "Oleo Margin", level: 55, color: "var(--amber)" },
      { name: "ESG", level: 58, color: "var(--amber)" },
      { name: "Labor", level: 52, color: "var(--cyan)" },
      { name: "Regulatory", level: 50, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "KLK is a diversified plantation-oleo play with global reach. CPO recovery and oleo demand support outlook. Quality management and sustainability focus.",
    },
  },
  SDG: {
    name: "SD Guthrie Bhd",
    ticker: "SDG",
    entityType: "public",
    sector: "Plantation",
    industry: "Palm Oil Plantation",
    hq: "Shah Alam, Malaysia",
    employees: "110,000",
    founded: 2007,
    ceo: "Mohd Helmy Othman Basha",
    price: 4.15,
    change: 0.05,
    changePct: 1.22,
    marketCap: "MYR 32.8B",
    peRatio: 22.5,
    divYield: "2.4%",
    beta: 1.08,
    revenue52w: "MYR 15.2B",
    kpis: [
      { label: "Revenue", value: "MYR 15.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 1.46B", sub: "FY24" },
      { label: "Planted Area", value: "580K ha", sub: "World's largest" },
      { label: "CPO Output", value: "2.5M MT", sub: "FY24" },
      { label: "FFB Yield", value: "20.2 t/ha", sub: "Mature" },
      { label: "ROE", value: "8.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [14000, 16500, 18000, 14500, 15200, 16200],
      netIncome: [600, 1200, 1600, 900, 1460, 1580],
      grossMargin: [20, 24, 26, 22, 24, 25],
      operatingMargin: [12, 16, 18, 14, 16, 17],
      netMargin: [4.3, 7.3, 8.9, 6.2, 9.6, 9.8],
    },
    segments: {
      labels: ["Malaysia", "Indonesia", "Liberia", "Refining", "Others"],
      values: [45, 40, 5, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["SD Guthrie", "IOI", "KLK", "FGV", "Wilmar"],
      revenue: [15200, 18200, 25000, 12000, 0],
      margin: [9.6, 8.6, 5.8, 4.2, 0],
    },
    swot: {
      strengths: ["Largest planted area globally", "Strong sustainability", "Geographic diversification", "Downstream optionality"],
      weaknesses: ["Pure plantation exposure", "Labor intensive", "Liberia complexity", "Yield variability"],
      opportunities: ["Yield improvement", "Downstream expansion", "Carbon credits", "Traceability premium"],
      threats: ["EUDR compliance", "CPO volatility", "Labor shortage", "Weather/climate"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "World's largest palm oil company by planted area; yield improvement and sustainability leadership." },
      { tag: "strategy", tagLabel: "Strategy", text: "Traceability and ESG focus; positioning for EUDR compliance; downstream expansion." },
      { tag: "risk", tagLabel: "Risk", text: "EUDR and deforestation scrutiny; pure plantation = higher CPO exposure." },
      { tag: "market", tagLabel: "Market", text: "Pure-play plantation giant; sustainability leader with scale advantage." },
    ],
    risks: [
      { name: "CPO Price", level: 70, color: "var(--amber)" },
      { name: "EUDR", level: 62, color: "var(--amber)" },
      { name: "Labor", level: 58, color: "var(--amber)" },
      { name: "Weather", level: 52, color: "var(--cyan)" },
      { name: "Liberia", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "SD Guthrie is the world's largest palm oil company by planted area. Sustainability and traceability leadership support EUDR compliance. CPO recovery supports earnings.",
    },
  },
  GAMUDA: {
    name: "Gamuda Berhad",
    ticker: "GAMUDA",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Infrastructure & Construction",
    hq: "Petaling Jaya, Malaysia",
    employees: "8,500",
    founded: 1976,
    ceo: "Mohd Azhar Abdul Hamid",
    price: 5.95,
    change: 0.18,
    changePct: 3.12,
    marketCap: "MYR 30.5B",
    peRatio: 28.5,
    divYield: "1.8%",
    beta: 1.22,
    revenue52w: "MYR 8.2B",
    kpis: [
      { label: "Revenue", value: "MYR 8.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 1.07B", sub: "FY24" },
      { label: "Order Book", value: "MYR 28B", sub: "Construction" },
      { label: "MRT2/3", value: "Key projects", sub: "Rail" },
      { label: "Data Centers", value: "Expanding", sub: "Australia/MY" },
      { label: "ROE", value: "12.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [5200, 6200, 7200, 7800, 8200, 9200],
      netIncome: [450, 620, 850, 950, 1070, 1250],
      grossMargin: [18, 20, 22, 23, 24, 25],
      operatingMargin: [12, 14, 16, 17, 18, 19],
      netMargin: [8.7, 10.0, 11.8, 12.2, 13.0, 13.6],
    },
    segments: {
      labels: ["Construction", "Property", "Highway", "Water", "Others"],
      values: [55, 25, 10, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Gamuda", "IJM", "WCT", "Sunway", "MMC"],
      revenue: [8200, 5500, 2800, 6500, 4200],
      margin: [13.0, 8.5, 5.2, 9.8, 6.5],
    },
    swot: {
      strengths: ["MRT expertise", "Strong order book", "Australia expansion", "Data center construction"],
      weaknesses: ["Project execution risk", "Political exposure", "Property cycle", "Currency"],
      opportunities: ["MRT3", "Data centers", "Australia infrastructure", "ASEAN projects"],
      threats: ["Project delays", "Political changes", "Competition", "Cost inflation"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "MRT2/3 and data center construction in Australia driving growth; order book visibility strong." },
      { tag: "strategy", tagLabel: "Strategy", text: "Diversifying into data center construction; Australia as key growth market." },
      { tag: "risk", tagLabel: "Risk", text: "Large projects carry execution and political risk; property segment cyclical." },
      { tag: "market", tagLabel: "Market", text: "Premier infrastructure play; MRT and data center exposure support rerating." },
    ],
    risks: [
      { name: "Execution", level: 55, color: "var(--amber)" },
      { name: "Political", level: 58, color: "var(--amber)" },
      { name: "Property", level: 52, color: "var(--cyan)" },
      { name: "Competition", level: 45, color: "var(--cyan)" },
      { name: "Currency", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Gamuda is Malaysia's premier infrastructure contractor with MRT2/3 and data center exposure. Australia expansion diversifies geography. Order book supports earnings visibility.",
    },
  },
  SUNWAY: {
    name: "Sunway Berhad",
    ticker: "SUNWAY",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Diversified - Construction, Property, Healthcare, Education",
    hq: "Petaling Jaya, Malaysia",
    employees: "16,000",
    founded: 1974,
    ceo: "Tan Sri Jeffrey Cheah",
    price: 3.25,
    change: 0.06,
    changePct: 1.88,
    marketCap: "MYR 8.2B",
    peRatio: 15.5,
    divYield: "3.1%",
    beta: 1.05,
    revenue52w: "MYR 6.5B",
    kpis: [
      { label: "Revenue", value: "MYR 6.5B", sub: "FY24" },
      { label: "Net Income", value: "MYR 528M", sub: "FY24" },
      { label: "Order Book", value: "MYR 12B", sub: "Construction" },
      { label: "Property GDV", value: "MYR 8B", sub: "Unbilled" },
      { label: "Healthcare Beds", value: "1,200+", sub: "Sunway Medical" },
      { label: "ROE", value: "10.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4500, 5200, 5800, 6200, 6500, 7200],
      netIncome: [280, 350, 420, 480, 528, 600],
      grossMargin: [22, 24, 25, 26, 27, 27],
      operatingMargin: [12, 14, 15, 16, 16, 17],
      netMargin: [6.2, 6.7, 7.2, 7.7, 8.1, 8.3],
    },
    segments: {
      labels: ["Construction", "Property", "Healthcare", "Education", "Others"],
      values: [40, 30, 15, 8, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Sunway", "Gamuda", "IJM", "SP Setia", "KPJ Healthcare"],
      revenue: [6500, 8200, 5500, 3200, 2800],
      margin: [8.1, 13.0, 8.5, 6.2, 8.5],
    },
    swot: {
      strengths: ["Diversified model", "Healthcare growth", "Education brand", "Integrated township"],
      weaknesses: ["Property cycle", "Construction margins", "Debt level", "Execution"],
      opportunities: ["Healthcare expansion", "Data center", "Industrial property", "Education"],
      threats: ["Property slowdown", "Labor costs", "Competition", "Interest rates"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Healthcare and education provide recurring income; construction order book supports earnings." },
      { tag: "strategy", tagLabel: "Strategy", text: "Integrated township model; healthcare and education as growth engines." },
      { tag: "risk", tagLabel: "Risk", text: "Property segment cyclical; diversified model provides cushion." },
      { tag: "market", tagLabel: "Market", text: "Diversified conglomerate with defensive healthcare/education; yield and growth balance." },
    ],
    risks: [
      { name: "Property", level: 58, color: "var(--amber)" },
      { name: "Construction", level: 50, color: "var(--cyan)" },
      { name: "Debt", level: 48, color: "var(--cyan)" },
      { name: "Execution", level: 45, color: "var(--cyan)" },
      { name: "Competition", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Sunway offers diversified exposure to construction, property, healthcare, and education. Healthcare expansion and recurring income support valuation. Attractive yield.",
    },
  },
  SIME: {
    name: "Sime Darby Berhad",
    ticker: "SIME",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Industrial Equipment, Motors, Logistics",
    hq: "Kuala Lumpur, Malaysia",
    employees: "22,000",
    founded: 1910,
    ceo: "Datuk Jeffri Salim Davidson",
    price: 2.85,
    change: 0.04,
    changePct: 1.42,
    marketCap: "MYR 18.5B",
    peRatio: 12.8,
    divYield: "4.2%",
    beta: 1.02,
    revenue52w: "MYR 58B",
    kpis: [
      { label: "Revenue", value: "MYR 58B", sub: "FY24" },
      { label: "Net Income", value: "MYR 1.45B", sub: "FY24" },
      { label: "Industrial", value: "Caterpillar dealer", sub: "Core" },
      { label: "Motors", value: "BMW, Ford, etc", sub: "Dealerships" },
      { label: "Logistics", value: "Weifield", sub: "Growing" },
      { label: "ROE", value: "9.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [38000, 45000, 52000, 55000, 58000, 62000],
      netIncome: [800, 1100, 1300, 1350, 1450, 1600],
      grossMargin: [12, 13, 13, 14, 14, 14],
      operatingMargin: [4, 5, 5.5, 5.5, 5.8, 6.0],
      netMargin: [2.1, 2.4, 2.5, 2.5, 2.5, 2.6],
    },
    segments: {
      labels: ["Industrial", "Motors", "Logistics", "Healthcare", "Others"],
      values: [45, 35, 12, 5, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Sime Darby", "Boustead", "UMW", "DRB-HICOM", "Cycle & Carriage"],
      revenue: [58000, 8000, 12000, 15000, 6500],
      margin: [2.5, 3.2, 4.5, 2.8, 5.2],
    },
    swot: {
      strengths: ["Caterpillar franchise", "Regional footprint", "Diversified", "Strong brands"],
      weaknesses: ["Low margins", "Cyclical", "Complex structure", "Motors competition"],
      opportunities: ["Mining/construction cycle", "EV dealerships", "Logistics growth", "Healthcare"],
      threats: ["Economic slowdown", "EV disruption", "Competition", "Currency"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Industrial segment benefits from mining and construction; motors facing EV transition." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on industrial and logistics; motors adapting to EV shift." },
      { tag: "risk", tagLabel: "Risk", text: "Cyclical exposure to mining and construction; thin margins." },
      { tag: "market", tagLabel: "Market", text: "Large conglomerate with industrial focus; yield play with cyclical upside." },
    ],
    risks: [
      { name: "Cycle", level: 58, color: "var(--amber)" },
      { name: "Motors", level: 55, color: "var(--amber)" },
      { name: "Margin", level: 48, color: "var(--cyan)" },
      { name: "Competition", level: 45, color: "var(--cyan)" },
      { name: "Currency", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Sime Darby offers diversified industrial and motors exposure. Caterpillar franchise and mining cycle support industrial. Attractive yield for large cap.",
    },
  },
  DRB: {
    name: "DRB-HICOM Berhad",
    ticker: "DRB",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Automotive, Services, Property",
    hq: "Shah Alam, Malaysia",
    employees: "65,000",
    founded: 1980,
    ceo: "Dato' Sri Syed Faisal Albar",
    price: 1.42,
    change: 0.02,
    changePct: 1.43,
    marketCap: "MYR 2.8B",
    peRatio: 18.5,
    divYield: "1.4%",
    beta: 1.15,
    revenue52w: "MYR 15.2B",
    kpis: [
      { label: "Revenue", value: "MYR 15.2B", sub: "FY24" },
      { label: "Net Income", value: "MYR 151M", sub: "FY24" },
      { label: "Proton Stake", value: "50.1%", sub: "Via subsidiary" },
      { label: "Honda Dealer", value: "Key", sub: "Motors" },
      { label: "Services", value: "POS, banking", sub: "Diversified" },
      { label: "ROE", value: "4.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [12000, 13500, 14200, 14800, 15200, 16500],
      netIncome: [-120, 80, 120, 135, 151, 200],
      grossMargin: [8, 10, 11, 11, 12, 12],
      operatingMargin: [2, 4, 5, 5, 5.5, 6],
      netMargin: [-1.0, 0.6, 0.8, 0.9, 1.0, 1.2],
    },
    segments: {
      labels: ["Automotive", "Services", "Property", "Logistics", "Others"],
      values: [55, 25, 10, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["DRB-HICOM", "Sime Darby", "UMW", "Bermaz", "Tan Chong"],
      revenue: [15200, 58000, 12000, 4500, 3500],
      margin: [1.0, 2.5, 4.5, 8.5, 2.2],
    },
    swot: {
      strengths: ["Proton ownership", "Honda franchise", "Diversified services", "Geely partnership"],
      weaknesses: ["Thin margins", "Proton turnaround", "Debt", "Execution"],
      opportunities: ["Proton X50/90 success", "EV transition", "Services growth", "Property"],
      threats: ["Competition", "EV disruption", "Economic slowdown", "Proton execution"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Proton recovery under Geely; X50 and X90 driving volume. Honda dealership stable." },
      { tag: "strategy", tagLabel: "Strategy", text: "Proton as growth engine; services and property provide diversification." },
      { tag: "risk", tagLabel: "Risk", text: "Proton execution and EV transition; thin group margins." },
      { tag: "market", tagLabel: "Market", text: "Proton play with diversified backing; turnaround story with execution risk." },
    ],
    risks: [
      { name: "Proton", level: 62, color: "var(--amber)" },
      { name: "Margin", level: 58, color: "var(--amber)" },
      { name: "Competition", level: 55, color: "var(--amber)" },
      { name: "Debt", level: 52, color: "var(--cyan)" },
      { name: "EV", level: 50, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "DRB-HICOM is a Proton play with Geely partnership driving recovery. Thin margins and execution risk. Suitable for turnaround investors.",
    },
  },
  PROTON: {
    name: "Proton Holdings Berhad",
    ticker: "PROTON",
    entityType: "private",
    sector: "Automotive",
    industry: "Automotive Manufacturing",
    hq: "Shah Alam, Malaysia",
    employees: "12,000",
    founded: 1983,
    ceo: "Li Chunrong",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Revenue", value: "~MYR 8.5B", sub: "FY24" },
      { label: "Vehicle Sales", value: "145K units", sub: "FY24" },
      { label: "Market Share", value: "21%", sub: "Malaysia TIV" },
      { label: "X50/X90", value: "Key models", sub: "Geely platform" },
      { label: "Owners", value: "DRB 50.1%, Geely 49.9%", sub: "JV" },
      { label: "Export", value: "Growing", sub: "ASEAN" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4200, 5800, 7200, 8000, 8500, 9500],
      netIncome: [-350, 50, 180, 250, 320, 400],
      grossMargin: [5, 12, 15, 16, 17, 18],
      operatingMargin: [-8, 2, 5, 6, 7, 8],
      netMargin: [-8.3, 0.9, 2.5, 3.1, 3.8, 4.2],
    },
    segments: {
      labels: ["X50", "X70", "X90", "Saga", "Others"],
      values: [35, 20, 15, 25, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Proton", "Perodua", "Toyota", "Honda", "Mazda"],
      revenue: [8500, 12000, 8500, 4200, 1800],
      margin: [3.8, 8.5, 6.2, 5.5, 4.2],
    },
    swot: {
      strengths: ["Geely technology", "X50/X90 success", "National brand", "EV roadmap"],
      weaknesses: ["Legacy perception", "Dependence on Geely", "Export limited", "Cost structure"],
      opportunities: ["EV models", "ASEAN export", "Smart car", "Hybrid expansion"],
      threats: ["Perodua competition", "EV transition", "Import competition", "Cost inflation"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Proton recovery driven by Geely platforms; X50 segment leader. EV and hybrid roadmap." },
      { tag: "strategy", tagLabel: "Strategy", text: "Geely partnership for technology; local assembly with global platforms." },
      { tag: "risk", tagLabel: "Risk", text: "Perodua dominance; EV transition and competition." },
      { tag: "market", tagLabel: "Market", text: "National car maker with renewed relevance; exposure via DRB-HICOM." },
    ],
    risks: [
      { name: "Competition", level: 65, color: "var(--amber)" },
      { name: "Execution", level: 52, color: "var(--cyan)" },
      { name: "EV", level: 55, color: "var(--amber)" },
      { name: "Geely", level: 45, color: "var(--cyan)" },
      { name: "Cost", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Proton has staged a strong recovery under Geely. X50 and X90 driving volume. EV transition and Perodua competition remain key. No direct listing; exposure via DRB.",
    },
  },
  NCT: {
    name: "NCT Group",
    ticker: "NCT",
    entityType: "private",
    sector: "Conglomerates",
    industry: "Industrial & Trading",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,200",
    founded: 1985,
    ceo: "Dato' Seri Yap Ngan Choy",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 680M",
    kpis: [
      { label: "Revenue", value: "~MYR 680M", sub: "FY24" },
      { label: "Segments", value: "Trading, Property", sub: "Diversified" },
      { label: "Employees", value: "1,200", sub: "Group" },
      { label: "Property", value: "Developments", sub: "Selangor" },
      { label: "Trading", value: "Industrial", sub: "Core" },
      { label: "Scale", value: "Mid-tier", sub: "Private" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [520, 560, 600, 640, 680, 720],
      netIncome: [25, 32, 38, 42, 48, 55],
      grossMargin: [18, 19, 20, 20, 21, 21],
      operatingMargin: [6, 7, 7.5, 8, 8.5, 9],
      netMargin: [4.8, 5.7, 6.3, 6.6, 7.1, 7.6],
    },
    segments: {
      labels: ["Trading", "Property", "Manufacturing", "Services", "Others"],
      values: [45, 30, 12, 8, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["NCT", "Boustead", "Kumpulan Fima", "Kumpulan Perangsang", "Smaller industrials"],
      revenue: [680, 8000, 650, 420, 0],
      margin: [7.1, 3.2, 5.5, 4.2, 0],
    },
    swot: {
      strengths: ["Diversified", "Property exposure", "Established", "Flexible"],
      weaknesses: ["Small scale", "Limited visibility", "Concentration", "Funding"],
      opportunities: ["Property cycle", "Trading growth", "Partnerships", "Expansion"],
      threats: ["Competition", "Economic slowdown", "Property market", "Scale"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Mid-tier industrial group with property and trading; organic growth focus." },
      { tag: "strategy", tagLabel: "Strategy", text: "Diversified model across trading, property, and services." },
      { tag: "risk", tagLabel: "Risk", text: "Private entity with limited disclosure; smaller scale limits options." },
      { tag: "market", tagLabel: "Market", text: "Smaller industrial conglomerate; private with no public market exposure." },
    ],
    risks: [
      { name: "Scale", level: 58, color: "var(--amber)" },
      { name: "Property", level: 55, color: "var(--amber)" },
      { name: "Visibility", level: 50, color: "var(--cyan)" },
      { name: "Competition", level: 52, color: "var(--cyan)" },
      { name: "Economic", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "NCT is a smaller private industrial group with diversified operations. Limited public information. No listed exposure.",
    },
  },
});
