Object.assign(COMPANIES, {
  GENTING: {
    name: "Genting Berhad",
    ticker: "GENTING",
    entityType: "public",
    sector: "Conglomerates",
    industry: "Leisure, Hospitality & Plantations",
    hq: "Kuala Lumpur, Malaysia",
    employees: "55,000",
    founded: 1965,
    ceo: "Tan Kong Han",
    price: 4.95,
    change: 0.12,
    changePct: 2.48,
    marketCap: "MYR 14.9B",
    peRatio: 18,
    divYield: "2.0%",
    beta: 1.25,
    revenue52w: "MYR 27.7B",
    kpis: [
      { label: "Revenue", value: "MYR 27.7B", sub: "+2% YoY FY24" },
      { label: "Net Income", value: "MYR 2.0B", sub: "FY24" },
      { label: "Resort Visitors", value: "25M+", sub: "Annual" },
      { label: "Hotel Rooms", value: "10,000+", sub: "Across properties" },
      { label: "Theme Park Visits", value: "8M+", sub: "Genting Highlands" },
      { label: "Plantations", value: "120K ha", sub: "Oil palm estate" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [12.8, 15.2, 20.5, 27.1, 27.7, 29.0],
      netIncome: [-0.8, 0.5, 1.2, 2.3, 2.0, 2.2],
      grossMargin: [42, 45, 48, 50, 51, 52],
      operatingMargin: [8, 12, 15, 18, 20, 22],
      netMargin: [-5, 1, 3, 4, 4, 4],
    },
    segments: {
      labels: ["Leisure & Hospitality", "Plantation", "Power", "Oil & Gas", "Others"],
      values: [55, 18, 12, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Genting", "Berjaya", "Sunway", "YTL", "Sime Darby"],
      revenue: [27.7, 8.2, 12.5, 15.5, 45.2],
      margin: [4, 3, 8, 6, 5],
    },
    swot: {
      strengths: [
        "Resorts World Genting as dominant integrated resort in Malaysia",
        "Strong international presence in Singapore, US, UK",
        "Diversified portfolio across leisure, hospitality, plantations",
        "Brand recognition and loyal customer base",
      ],
      weaknesses: [
        "High debt levels from expansion",
        "Sensitivity to gaming regulations",
        "COVID-19 exposed tourism dependency",
        "Plantation margins under pressure",
      ],
      opportunities: [
        "Post-pandemic tourism recovery in Asia",
        "Japan IR development potential",
        "Digital and online gaming expansion",
        "Premium hospitality segment growth",
      ],
      threats: [
        "Regulatory changes in gaming",
        "Competition from regional integrated resorts",
        "Economic slowdown affecting discretionary spend",
        "Environmental scrutiny on plantations",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Recovery in leisure and hospitality driving revenue; Resorts World Genting visitation back to pre-pandemic levels with strong Singapore and regional demand." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on integrated resort model; expanding non-gaming revenue; Japan IR project under evaluation; digital transformation in operations." },
      { tag: "risk", tagLabel: "Risk", text: "Regulatory risk in gaming; debt servicing; forex exposure from international operations; plantation commodity price volatility." },
      { tag: "market", tagLabel: "Market", text: "Leading leisure conglomerate in Malaysia; competitive position in Singapore via Resorts World Sentosa; US and UK operations add geographic diversification." },
    ],
    risks: [
      { name: "Regulatory", level: 45, color: "var(--amber)" },
      { name: "Debt", level: 55, color: "var(--amber)" },
      { name: "Tourism Demand", level: 30, color: "var(--green)" },
      { name: "Commodity Prices", level: 40, color: "var(--cyan)" },
      { name: "Competition", level: 50, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Solid recovery trajectory with strong leisure demand; valuation fair; monitor debt and regulatory developments.",
    },
  },

  ALBUKHARY: {
    name: "Albukhary Group",
    ticker: "ALBUKHARY",
    entityType: "private",
    sector: "Conglomerates",
    industry: "Diversified - Automotive, Property, Philanthropy",
    hq: "Kuala Lumpur, Malaysia",
    employees: "5,000",
    founded: 1985,
    ceo: "Tan Sri Syed Mokhtar Albukhary",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 15B",
    kpis: [
      { label: "Group Revenue", value: "MYR 15B", sub: "Consolidated" },
      { label: "Companies", value: "50+", sub: "Portfolio companies" },
      { label: "Port Operations", value: "12M TEU", sub: "MMC-Port Klang" },
      { label: "Property", value: "MYR 3B+", sub: "Developments" },
      { label: "Philanthropy", value: "MYR 500M+", sub: "Albukhary Foundation" },
      { label: "Employees", value: "5,000+", sub: "Group-wide" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [12.5, 13.2, 14.0, 14.5, 15.0, 15.8],
      netIncome: [0.4, 0.5, 0.55, 0.6, 0.65, 0.7],
      grossMargin: [25, 26, 27, 27, 28, 28],
      operatingMargin: [8, 9, 9, 10, 10, 10],
      netMargin: [3, 4, 4, 4, 4, 4],
    },
    segments: {
      labels: ["Ports & Logistics", "Automotive", "Property", "Energy", "Others"],
      values: [40, 25, 15, 12, 8],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Albukhary", "Sime Darby", "DRB-HICOM", "MMC", "YTL"],
      revenue: [15.0, 45.2, 12.8, 8.5, 15.5],
      margin: [4, 5, 2, 6, 6],
    },
    swot: {
      strengths: [
        "One of Malaysia's largest Bumiputera conglomerates",
        "Controlling stakes in MMC Corp, DRB-HICOM",
        "Strategic port assets via Port Klang",
        "Strong philanthropic brand via Albukhary Foundation",
      ],
      weaknesses: [
        "Complex group structure",
        "Some subsidiaries under financial stress",
        "Limited transparency as private entity",
        "Dependency on government contracts",
      ],
      opportunities: [
        "Logistics and port expansion in ASEAN",
        "EV transition in automotive",
        "Property development in growth corridors",
        "Renewable energy investments",
      ],
      threats: [
        "Political and policy changes",
        "Competition in ports and logistics",
        "Automotive industry disruption",
        "Economic slowdown",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Steady growth across port operations and logistics; MMC Port Holdings IPO planned at $6.2B valuation; MMC and DRB-HICOM stakes provide diversified exposure to infrastructure and automotive." },
      { tag: "strategy", tagLabel: "Strategy", text: "Bumiputera conglomerate model; strategic stakes in listed entities; philanthropy as brand differentiator; focus on infrastructure and logistics." },
      { tag: "risk", tagLabel: "Risk", text: "Political exposure; complex cross-holdings; some subsidiaries with debt challenges; regulatory changes in automotive." },
      { tag: "market", tagLabel: "Market", text: "Key player in Malaysian ports via MMC; significant automotive presence via DRB-HICOM; influential in Bumiputera business landscape." },
    ],
    risks: [
      { name: "Political", level: 55, color: "var(--amber)" },
      { name: "Debt", level: 50, color: "var(--amber)" },
      { name: "Governance", level: 45, color: "var(--amber)" },
      { name: "Competition", level: 40, color: "var(--cyan)" },
      { name: "Economic", level: 35, color: "var(--green)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--cyan)",
      text: "Diversified conglomerate with strategic assets; monitor subsidiary performance and policy environment.",
    },
  },

  CCCC_MY: {
    name: "China Communications Construction Company (Malaysia)",
    ticker: "CCCC_MY",
    entityType: "private",
    sector: "Infra",
    industry: "Infrastructure & Construction",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,500",
    founded: 2016,
    ceo: "Wang Tongzhou",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Revenue", value: "MYR 8.5B", sub: "Malaysia projects" },
      { label: "Project Value", value: "MYR 50B+", sub: "ECRL & others" },
      { label: "ECRL Contract", value: "RM44B", sub: "93% complete (Feb 2026)" },
      { label: "Infrastructure Projects", value: "15+", sub: "Active" },
      { label: "Employees", value: "2,500", sub: "Malaysia ops" },
      { label: "China Partnership", value: "CCCC", sub: "Parent SOE" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4.2, 5.5, 6.8, 7.5, 8.5, 9.5],
      netIncome: [0.15, 0.2, 0.25, 0.28, 0.32, 0.38],
      grossMargin: [12, 13, 14, 14, 15, 15],
      operatingMargin: [5, 5, 6, 6, 6, 7],
      netMargin: [4, 4, 4, 4, 4, 4],
    },
    segments: {
      labels: ["Rail", "Highways", "Ports", "Buildings", "Others"],
      values: [65, 15, 8, 7, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["CCCC MY", "Gamuda", "IJM", "WCT", "MMC"],
      revenue: [8.5, 4.2, 5.5, 2.8, 8.5],
      margin: [4, 8, 6, 5, 6],
    },
    swot: {
      strengths: [
        "ECRL as flagship project - largest rail in Malaysia",
        "Parent CCCC is world-leading infrastructure SOE",
        "Strong execution capability and financing access",
        "Belt and Road alignment",
      ],
      weaknesses: [
        "Perception of China dependency",
        "Limited local content in some projects",
        "Political sensitivity",
        "Single major project concentration",
      ],
      opportunities: [
        "More infrastructure projects under NIMP",
        "Rail and transit expansion",
        "East Coast development corridor",
        "Regional connectivity projects",
      ],
      threats: [
        "Geopolitical tensions",
        "Contract renegotiation risk",
        "Local contractor preference policies",
        "Funding and cost overruns",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "ECRL 93% complete (Feb 2026); target commercial operations Jan 2027; construction driving revenue; strong pipeline from Malaysia-China infrastructure cooperation." },
      { tag: "strategy", tagLabel: "Strategy", text: "ECRL as anchor; pursue additional rail and highway projects; localisation and JV partnerships; align with government infrastructure agenda." },
      { tag: "risk", tagLabel: "Risk", text: "Geopolitical risk; contract and payment timing; local content requirements; cost escalation on long-duration projects." },
      { tag: "market", tagLabel: "Market", text: "Key China contractor in Malaysia; ECRL transforms East Coast connectivity; significant player in Malaysia infrastructure build-out." },
    ],
    risks: [
      { name: "Geopolitical", level: 60, color: "var(--amber)" },
      { name: "Contract", level: 40, color: "var(--cyan)" },
      { name: "Execution", level: 35, color: "var(--green)" },
      { name: "Political", level: 55, color: "var(--amber)" },
      { name: "Cost", level: 45, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Positive",
      ratingColor: "var(--green)",
      text: "ECRL execution on track; strong project pipeline; monitor geopolitical and policy developments.",
    },
  },

  PAYNET: {
    name: "Payments Network Malaysia Sdn Bhd",
    ticker: "PAYNET",
    entityType: "private",
    sector: "Banking & Finance",
    industry: "Payment Infrastructure",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,200",
    founded: 2017,
    ceo: "Farhan Ahmad",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.5B",
    kpis: [
      { label: "Transaction Volume", value: "6B+", sub: "2024 target" },
      { label: "DuitNow Users", value: "25M+", sub: "Registered" },
      { label: "FPX Transactions", value: "500M+", sub: "Annual" },
      { label: "ATMs Managed", value: "12,000+", sub: "Network" },
      { label: "RPP Adoption", value: "85%+", sub: "Banks" },
      { label: "Real-time Payments", value: "24/7", sub: "DuitNow" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0.9, 1.0, 1.2, 1.35, 1.5, 1.7],
      netIncome: [0.15, 0.18, 0.22, 0.26, 0.30, 0.35],
      grossMargin: [65, 68, 70, 72, 73, 74],
      operatingMargin: [25, 28, 30, 32, 33, 34],
      netMargin: [17, 18, 18, 19, 20, 21],
    },
    segments: {
      labels: ["FPX", "DuitNow", "ATM", "JomPAY", "Others"],
      values: [35, 30, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["PayNet", "Visa", "Mastercard", "Boost", "Touch 'n Go"],
      revenue: [1.5, 0.8, 0.6, 0.4, 0.5],
      margin: [20, 45, 40, 15, 18],
    },
    swot: {
      strengths: [
        "National payment infrastructure monopoly",
        "DuitNow as real-time payment backbone",
        "FPX dominant for online bank transfers",
        "Bank-owned, regulatory alignment",
      ],
      weaknesses: [
        "Dependency on bank participation",
        "Competition from card schemes and e-wallets",
        "Innovation pace vs fintechs",
        "Revenue model under pressure",
      ],
      opportunities: [
        "QR payment standardisation",
        "Cross-border linkages (e.g. Thailand)",
        "Open banking and API expansion",
        "B2B and government payments",
      ],
      threats: [
        "E-wallet bypass of traditional rails",
        "Big tech payment initiatives",
        "Regulatory changes",
        "Cyber security",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "DuitNow adoption accelerating; FPX remains core for e-commerce; real-time payments becoming norm; cross-border expansion underway." },
      { tag: "strategy", tagLabel: "Strategy", text: "National payment rail operator; DuitNow as centrepiece; QR standardisation; open banking and API strategy; regional connectivity." },
      { tag: "risk", tagLabel: "Risk", text: "Disintermediation by e-wallets; regulatory changes; cyber and operational risk; revenue pressure from fee competition." },
      { tag: "market", tagLabel: "Market", text: "Critical national infrastructure; backbone for bank-based payments; competing with card schemes and e-wallets for transaction share." },
    ],
    risks: [
      { name: "Competition", level: 55, color: "var(--amber)" },
      { name: "Cyber", level: 50, color: "var(--amber)" },
      { name: "Regulatory", level: 35, color: "var(--green)" },
      { name: "Technology", level: 40, color: "var(--cyan)" },
      { name: "Revenue", level: 45, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--cyan)",
      text: "Essential infrastructure with growing DuitNow adoption; monitor e-wallet competition and open banking evolution.",
    },
  },

  SPEEDMART: {
    name: "99 Speedmart Retail Holdings Berhad",
    ticker: "SPEEDMART",
    entityType: "public",
    sector: "Retail",
    industry: "Convenience Retail",
    hq: "Klang, Malaysia",
    employees: "15,000",
    founded: 1987,
    ceo: "Lee Thiam Wah",
    price: 1.88,
    change: 0.05,
    changePct: 2.78,
    marketCap: "MYR 15.2B",
    peRatio: 45,
    divYield: "0.8%",
    beta: 0.72,
    revenue52w: "MYR 13.5B",
    kpis: [
      { label: "Revenue", value: "MYR 13.5B", sub: "FY24" },
      { label: "Net Income", value: "MYR 340M", sub: "FY24" },
      { label: "Store Count", value: "2,700+", sub: "Nationwide" },
      { label: "Daily Transactions", value: "3M+", sub: "Average" },
      { label: "SSSG", value: "5.2%", sub: "FY24" },
      { label: "Distribution Centers", value: "8", sub: "National" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6.8, 7.5, 8.2, 9.21, 9.98, 11.0],
      netIncome: [0.28, 0.32, 0.36, 0.40, 0.49, 0.56],
      grossMargin: [22, 23, 23, 24, 24, 24],
      operatingMargin: [4, 4, 4, 5, 5, 5],
      netMargin: [2, 2, 2, 2, 3, 3],
    },
    segments: {
      labels: ["FMCG", "Fresh", "Beverages", "Snacks", "Others"],
      values: [45, 20, 15, 12, 8],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["99 Speedmart", "7-Eleven", "KK Super Mart", "MyNews", "FamilyMart"],
      revenue: [9.98, 2.5, 1.8, 0.6, 0.4],
      margin: [3, 2, 4, 2, 1],
    },
    swot: {
      strengths: [
        "Malaysia's largest mini-market chain",
        "Strong store network and density",
        "Efficient supply chain and distribution",
        "Value positioning resonates with mass market",
      ],
      weaknesses: [
        "High PE valuation post-IPO",
        "Low dividend yield",
        "Concentration in Peninsular Malaysia",
        "Margin pressure from competition",
      ],
      opportunities: [
        "Store expansion in East Malaysia",
        "Private label expansion",
        "Fresh and chilled category growth",
        "Digital and loyalty initiatives",
      ],
      threats: [
        "Competition from 7-Eleven, KK",
        "E-commerce and quick commerce",
        "Rising costs and inflation",
        "Saturation in urban areas",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Revenue grew 8.3% to RM9.98B in FY24; net profit up 22.5% to RM490M. Opened 252 new stores reaching 2,778 outlets. Total transactions grew 12.6% to 465.5M." },
      { tag: "strategy", tagLabel: "Strategy", text: "Density and convenience model; value-for-money positioning; vertical integration in distribution; private label to boost margins." },
      { tag: "risk", tagLabel: "Risk", text: "Valuation premium; competition intensifying; inflation and cost pressure; execution risk in new regions." },
      { tag: "market", tagLabel: "Market", text: "Dominant mini-market player; 7-Eleven and KK Super Mart as main competitors; convenience retail growing with urbanisation." },
    ],
    risks: [
      { name: "Valuation", level: 65, color: "var(--amber)" },
      { name: "Competition", level: 50, color: "var(--amber)" },
      { name: "Cost", level: 45, color: "var(--amber)" },
      { name: "Execution", level: 30, color: "var(--green)" },
      { name: "Demand", level: 25, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Strong franchise and growth; valuation full; suitable for long-term growth investors.",
    },
  },

  GHAZANAH_SABAH: {
    name: "Qhazanah Sabah Berhad",
    ticker: "GHAZANAH_SABAH",
    entityType: "statutory",
    sector: "Government",
    industry: "State Investment & Development",
    hq: "Kota Kinabalu, Malaysia",
    employees: "500",
    founded: 1995,
    ceo: "Tuan Haji Mohamad Damshal Awang Damit",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 2.2B",
    kpis: [
      { label: "AUM", value: "MYR 4.5B", sub: "Portfolio value" },
      { label: "Portfolio Value", value: "MYR 4.5B", sub: "Total assets" },
      { label: "Investments", value: "40+", sub: "Companies & projects" },
      { label: "Dividend to State", value: "MYR 180M", sub: "FY24" },
      { label: "Sectors Invested", value: "8", sub: "Diversified" },
      { label: "Staff", value: "500", sub: "Employees" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1.6, 1.8, 2.0, 2.1, 2.2, 2.4],
      netIncome: [0.12, 0.14, 0.16, 0.17, 0.18, 0.20],
      grossMargin: [35, 36, 37, 38, 38, 39],
      operatingMargin: [12, 13, 14, 14, 15, 15],
      netMargin: [8, 8, 8, 8, 8, 8],
    },
    segments: {
      labels: ["Ports", "Telecom", "Transport", "Energy", "Property", "Medical"],
      values: [25, 22, 18, 15, 12, 8],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444", "#8b5cf6"],
    },
    competitors: {
      labels: ["Ghazanah Sabah", "Khazanah", "PNB", "KWAP", "EPF"],
      revenue: [2.2, 8.5, 25.0, 15.0, 60.0],
      margin: [8, 10, 12, 8, 6],
    },
    swot: {
      strengths: [
        "Sabah state sovereign investment arm",
        "Manages state assets and strategic investments",
        "Diversified portfolio across sectors",
        "Contribution to state revenue",
      ],
      weaknesses: [
        "Limited scale vs federal entities",
        "Dependency on state budget and policy",
        "Some underperforming assets",
        "Governance and transparency challenges",
      ],
      opportunities: [
        "Sabah development corridor projects",
        "Tourism and agriculture investment",
        "Renewable energy in Sabah",
        "Borneo connectivity initiatives",
      ],
      threats: [
        "Political changes in state government",
        "Economic volatility in Sabah",
        "Competition for capital",
        "Asset quality and returns",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Steady portfolio growth; focus on Sabah development; dividend contributions support state budget; property and utilities key drivers." },
      { tag: "strategy", tagLabel: "Strategy", text: "State investment and asset management; strategic stakes in Sabah enterprises; development of state assets; alignment with Sabah development plans." },
      { tag: "risk", tagLabel: "Risk", text: "Political and policy risk; asset concentration; governance; limited liquidity in some investments." },
      { tag: "market", tagLabel: "Market", text: "Key Sabah state investment entity; complements federal Khazanah; focused on Sabah economic development." },
    ],
    risks: [
      { name: "Political", level: 60, color: "var(--amber)" },
      { name: "Governance", level: 50, color: "var(--amber)" },
      { name: "Returns", level: 45, color: "var(--amber)" },
      { name: "Concentration", level: 40, color: "var(--cyan)" },
      { name: "Economic", level: 35, color: "var(--green)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--cyan)",
      text: "Important state investment vehicle; monitor political developments and portfolio performance.",
    },
  },

  TERENGGANU_INC: {
    name: "Terengganu Incorporated Sdn Bhd",
    ticker: "TERENGGANU_INC",
    entityType: "statutory",
    sector: "Government",
    industry: "State Investment & Development",
    hq: "Kuala Terengganu, Malaysia",
    employees: "300",
    founded: 1965,
    ceo: "Dato' Burhanuddin Hilmi Mohamed",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.75B",
    kpis: [
      { label: "Revenue", value: "MYR 1.75B", sub: "+15% YoY FY24" },
      { label: "Net Income", value: "MYR 42.2M", sub: "Turnaround from loss" },
      { label: "Total Assets", value: "MYR 3.85B", sub: "Portfolio value" },
      { label: "Oil Royalty", value: "MYR 800M", sub: "Annual contribution" },
      { label: "Investments", value: "30+", sub: "Companies & projects" },
      { label: "Subsidiaries", value: "25+", sub: "Group companies" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1.2, 1.3, 1.4, 1.52, 1.75, 1.8],
      netIncome: [-0.02, 0.01, 0.015, -0.006, 0.042, 0.06],
      grossMargin: [32, 33, 34, 35, 35, 36],
      operatingMargin: [10, 11, 11, 12, 12, 12],
      netMargin: [7, 7, 8, 8, 8, 8],
    },
    segments: {
      labels: ["Plantations", "Oil & Gas", "Healthcare", "Property", "Others"],
      values: [36, 23, 20, 12, 9],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Terengganu Inc", "Khazanah", "PNB", "Petronas", "State entities"],
      revenue: [1.8, 8.5, 25.0, 350.0, 2.0],
      margin: [8, 10, 12, 15, 7],
    },
    swot: {
      strengths: [
        "Terengganu state investment arm",
        "Oil royalty provides stable revenue base",
        "Long history since 1965",
        "Strategic assets in oil & gas, property",
      ],
      weaknesses: [
        "Oil dependency for revenue",
        "Limited diversification",
        "Smaller scale vs federal entities",
        "Governance and transparency",
      ],
      opportunities: [
        "Renewable energy transition",
        "Terengganu tourism development",
        "Industrial park expansion",
        "Oil & gas downstream",
      ],
      threats: [
        "Oil price volatility",
        "Political changes",
        "Oil production decline",
        "Competition for investment",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Revenue grew 15% to RM1.75B in FY24; profit tripled with PBT of RM81.7M and PAT of RM42.2M, a significant turnaround from prior year loss." },
      { tag: "strategy", tagLabel: "Strategy", text: "State asset management; oil royalty deployment; strategic investments in Terengganu; alignment with state development agenda." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price and production risk; political risk; concentration in oil; governance and transparency." },
      { tag: "market", tagLabel: "Market", text: "Key Terengganu state entity; oil royalty management; invests in state development and strategic sectors." },
    ],
    risks: [
      { name: "Oil Price", level: 55, color: "var(--amber)" },
      { name: "Political", level: 55, color: "var(--amber)" },
      { name: "Concentration", level: 50, color: "var(--amber)" },
      { name: "Governance", level: 45, color: "var(--amber)" },
      { name: "Diversification", level: 40, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--cyan)",
      text: "Oil royalty provides stability; diversification efforts ongoing; monitor oil sector and political developments.",
    },
  },
});
