const COMPANIES = {
  AAPL: {
    name: "Apple Inc.",
    ticker: "AAPL",
    entityType: "public",
    sector: "Technology",
    industry: "Consumer Electronics",
    hq: "Cupertino, CA",
    employees: "164,000",
    founded: 1976,
    ceo: "Tim Cook",
    price: 237.42,
    change: +2.34,
    changePct: +1.02,
    marketCap: "$3.62T",
    peRatio: 38.2,
    divYield: "0.44%",
    beta: 1.24,
    revenue52w: "$395.8B",
    kpis: [
      { label: "Revenue (TTM)", value: "$395.8B", sub: "+8.2% YoY" },
      { label: "Net Income", value: "$101.2B", sub: "25.6% margin" },
      { label: "Free Cash Flow", value: "$112.4B", sub: "+11.3% YoY" },
      { label: "Gross Margin", value: "46.2%", sub: "+140bps YoY" },
      { label: "R&D Spend", value: "$30.6B", sub: "7.7% of revenue" },
      { label: "Debt / Equity", value: "1.87", sub: "$111B total debt" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [274.5, 365.8, 394.3, 383.3, 395.8, 418.0],
      netIncome: [57.4, 94.7, 99.8, 97.0, 101.2, 108.5],
      grossMargin: [38.2, 41.8, 43.3, 44.1, 46.2, 47.0],
      operatingMargin: [24.1, 29.8, 30.3, 29.8, 30.7, 31.2],
      netMargin: [20.9, 25.9, 25.3, 25.3, 25.6, 26.0],
    },
    segments: {
      labels: ["iPhone", "Services", "Mac", "iPad", "Wearables"],
      values: [52, 24, 10, 7, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Apple", "Samsung", "Microsoft", "Google", "Huawei"],
      revenue: [395.8, 211.6, 236.6, 328.2, 99.5],
      margin: [25.6, 10.2, 35.3, 26.4, 5.8],
    },
    swot: {
      strengths: [
        "Unmatched brand loyalty and ecosystem lock-in",
        "Industry-leading gross margins in hardware",
        "Services segment growing at 16% CAGR",
        "Massive cash flow generation ($112B FCF)",
      ],
      weaknesses: [
        "Heavy dependence on iPhone (52% of revenue)",
        "Premium pricing limits TAM in emerging markets",
        "Ongoing regulatory scrutiny on App Store fees",
        "Limited presence in enterprise AI/cloud",
      ],
      opportunities: [
        "Apple Vision Pro creating new spatial computing category",
        "Generative AI integration across product lineup",
        "India market expansion (manufacturing + retail)",
        "Healthcare and automotive technology adjacencies",
      ],
      threats: [
        "Antitrust regulation in EU and US markets",
        "China geopolitical risk and supply chain concentration",
        "Samsung & Huawei competing aggressively on foldables",
        "Services revenue growth deceleration risk",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Services revenue has grown from $53B to $96B in 4 years, now representing 24% of total revenue. Apple Intelligence features could accelerate subscription growth." },
      { tag: "strategy", tagLabel: "Strategy", text: "Vision Pro marks Apple's first new product category since Apple Watch. Early enterprise adoption in healthcare and manufacturing signals long-term potential." },
      { tag: "risk", tagLabel: "Risk", text: "EU Digital Markets Act could force sideloading and alternative payment systems, potentially reducing App Store revenue by 10-15% in European markets." },
      { tag: "market", tagLabel: "Market", text: "India is now Apple's fastest-growing market with 33% YoY growth. Local manufacturing incentives and expanding middle class create a multi-year growth runway." },
    ],
    risks: [
      { name: "Regulatory Risk", level: 72, color: "var(--amber)" },
      { name: "Supply Chain Risk", level: 58, color: "var(--amber)" },
      { name: "Market Concentration", level: 65, color: "var(--amber)" },
      { name: "Innovation Risk", level: 35, color: "var(--green)" },
      { name: "Currency Exposure", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Outperform",
      ratingColor: "var(--green)",
      text: "Apple's transition toward a services-first model, combined with its silicon advantage and ecosystem stickiness, positions the company for sustained earnings growth. The ramp of Apple Intelligence features across the product line should drive a meaningful iPhone upgrade cycle in FY25-26. Key monitor: regulatory developments in the EU and China demand trajectory.",
    },
  },

  MSFT: {
    name: "Microsoft Corporation",
    ticker: "MSFT",
    entityType: "public",
    sector: "Technology",
    industry: "Software & Cloud",
    hq: "Redmond, WA",
    employees: "228,000",
    founded: 1975,
    ceo: "Satya Nadella",
    price: 452.18,
    change: +5.67,
    changePct: +1.27,
    marketCap: "$3.37T",
    peRatio: 36.8,
    divYield: "0.70%",
    beta: 0.89,
    revenue52w: "$236.6B",
    kpis: [
      { label: "Revenue (TTM)", value: "$236.6B", sub: "+16.4% YoY" },
      { label: "Net Income", value: "$83.5B", sub: "35.3% margin" },
      { label: "Free Cash Flow", value: "$74.1B", sub: "+24.7% YoY" },
      { label: "Gross Margin", value: "69.4%", sub: "+130bps YoY" },
      { label: "Azure Growth", value: "+29%", sub: "vs +26% prior Q" },
      { label: "Debt / Equity", value: "0.42", sub: "$47B total debt" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [143.0, 168.1, 198.3, 211.9, 236.6, 272.0],
      netIncome: [44.3, 61.3, 72.7, 72.4, 83.5, 97.0],
      grossMargin: [67.8, 68.9, 68.4, 68.9, 69.4, 70.1],
      operatingMargin: [37.0, 41.6, 42.1, 41.2, 44.6, 45.8],
      netMargin: [31.0, 36.5, 36.7, 34.2, 35.3, 35.7],
    },
    segments: {
      labels: ["Intelligent Cloud", "Productivity & Business", "More Personal Computing"],
      values: [44, 33, 23],
      colors: ["#6366f1", "#06b6d4", "#22c55e"],
    },
    competitors: {
      labels: ["Microsoft", "Amazon (AWS)", "Google Cloud", "Oracle", "Salesforce"],
      revenue: [236.6, 105.0, 41.2, 53.8, 34.9],
      margin: [35.3, 6.2, 26.4, 22.4, 11.8],
    },
    swot: {
      strengths: [
        "Azure is #2 cloud with accelerating AI workloads",
        "Copilot AI integrated across entire product suite",
        "Highest operating margin among mega-cap tech",
        "Enterprise relationships spanning 95% of Fortune 500",
      ],
      weaknesses: [
        "Azure still trails AWS in market share",
        "Gaming (Xbox) margins below corporate average",
        "Heavy CapEx requirements for AI infrastructure",
        "Activision integration execution risk",
      ],
      opportunities: [
        "AI monetization via Copilot ($30/user/month premium)",
        "Sovereign cloud expansion for government contracts",
        "LinkedIn data moat for enterprise AI features",
        "Healthcare and vertical cloud solutions",
      ],
      threats: [
        "AWS and GCP competing fiercely for AI workloads",
        "Open-source AI models reducing vendor lock-in",
        "EU regulatory scrutiny on Teams bundling",
        "Rising energy costs impacting data center economics",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Azure AI services revenue run rate exceeded $10B, growing over 100% YoY. Microsoft is the clear enterprise AI platform leader with OpenAI partnership." },
      { tag: "strategy", tagLabel: "Strategy", text: "Copilot strategy monetizes AI across Office 365, GitHub, Dynamics 365, and Security. Early data shows 70% of pilot enterprises converting to paid Copilot seats." },
      { tag: "risk", tagLabel: "Risk", text: "Massive AI infrastructure CapEx ($50B+ annually) creates earnings headwind if AI monetization timelines extend beyond market expectations." },
      { tag: "market", tagLabel: "Market", text: "Enterprise cloud spending is accelerating again after 2023 optimization cycle. Microsoft is winning disproportionate share of incremental AI-driven workloads." },
    ],
    risks: [
      { name: "CapEx / ROI Risk", level: 65, color: "var(--amber)" },
      { name: "Competitive Risk", level: 55, color: "var(--cyan)" },
      { name: "Regulatory Risk", level: 48, color: "var(--cyan)" },
      { name: "Integration Risk", level: 40, color: "var(--green)" },
      { name: "Talent Retention", level: 35, color: "var(--green)" },
    ],
    outlook: {
      rating: "Strong Buy",
      ratingColor: "var(--green)",
      text: "Microsoft is the best-positioned mega-cap for the AI era, with monetization levers across cloud, productivity, and developer tools. Azure's accelerating growth and Copilot adoption trajectory support a premium multiple. Key monitor: AI CapEx returns and competitive dynamics with AWS.",
    },
  },

  GOOGL: {
    name: "Alphabet Inc.",
    ticker: "GOOGL",
    entityType: "public",
    sector: "Technology",
    industry: "Internet & Digital Advertising",
    hq: "Mountain View, CA",
    employees: "182,500",
    founded: 1998,
    ceo: "Sundar Pichai",
    price: 178.35,
    change: -1.22,
    changePct: -0.68,
    marketCap: "$2.18T",
    peRatio: 24.6,
    divYield: "0.50%",
    beta: 1.06,
    revenue52w: "$328.2B",
    kpis: [
      { label: "Revenue (TTM)", value: "$328.2B", sub: "+14.3% YoY" },
      { label: "Net Income", value: "$86.6B", sub: "26.4% margin" },
      { label: "Free Cash Flow", value: "$69.8B", sub: "+32.1% YoY" },
      { label: "Gross Margin", value: "57.5%", sub: "+180bps YoY" },
      { label: "Cloud Revenue", value: "$41.2B", sub: "+28% YoY" },
      { label: "Debt / Equity", value: "0.05", sub: "$14B total debt" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [182.5, 257.6, 282.8, 307.4, 328.2, 368.0],
      netIncome: [40.3, 76.0, 59.9, 73.8, 86.6, 98.0],
      grossMargin: [53.6, 56.9, 55.4, 56.1, 57.5, 58.2],
      operatingMargin: [22.6, 30.6, 26.5, 27.4, 31.5, 32.8],
      netMargin: [22.1, 29.5, 21.2, 24.0, 26.4, 26.6],
    },
    segments: {
      labels: ["Search & Ads", "YouTube", "Google Cloud", "Subscriptions", "Other Bets"],
      values: [57, 11, 13, 15, 4],
      colors: ["#6366f1", "#ef4444", "#06b6d4", "#22c55e", "#f59e0b"],
    },
    competitors: {
      labels: ["Alphabet", "Meta", "Amazon (Ads)", "Microsoft (Ads)", "Snap/Pinterest"],
      revenue: [328.2, 160.0, 52.0, 18.3, 9.8],
      margin: [26.4, 34.5, 8.0, 35.3, 2.1],
    },
    swot: {
      strengths: [
        "Dominant 90%+ search market share globally",
        "YouTube is #1 video platform (2.5B+ monthly users)",
        "DeepMind/Gemini leadership in AI research",
        "Minimal debt with $100B+ cash reserves",
      ],
      weaknesses: [
        "Over-reliance on advertising (77% of revenue)",
        "Google Cloud still #3 behind AWS and Azure",
        "Other Bets portfolio burning $4B+ annually",
        "Organizational complexity and slower execution pace",
      ],
      opportunities: [
        "AI Overviews monetization in Search",
        "Google Cloud AI winning enterprise workloads",
        "Waymo autonomous driving approaching profitability",
        "YouTube Shorts monetization gap vs long-form",
      ],
      threats: [
        "DOJ antitrust ruling threatening default search deals",
        "AI chatbots disrupting traditional search behavior",
        "TikTok competing for younger demographics",
        "Privacy regulations impacting ad targeting precision",
      ],
    },
    insights: [
      { tag: "risk", tagLabel: "Risk", text: "The DOJ antitrust ruling could force changes to Google's default search agreements (worth ~$26B/yr from Apple alone). Potential remedies range from behavioral to structural." },
      { tag: "growth", tagLabel: "Growth", text: "Google Cloud reached profitability and is growing 28% YoY, driven by Vertex AI platform adoption. The segment is on track for $50B+ revenue by FY26." },
      { tag: "strategy", tagLabel: "Strategy", text: "Gemini model integration across Search, Workspace, and Cloud creates a unified AI strategy. Cost efficiency improvements have expanded operating margins by 400bps in 2 years." },
      { tag: "market", tagLabel: "Market", text: "YouTube's combined ad + subscription revenue exceeds $50B annually, making it larger than Netflix. Connected TV ad share is growing rapidly." },
    ],
    risks: [
      { name: "Antitrust / Legal Risk", level: 85, color: "var(--red)" },
      { name: "AI Disruption Risk", level: 60, color: "var(--amber)" },
      { name: "Ad Market Cyclicality", level: 50, color: "var(--cyan)" },
      { name: "Privacy Regulation", level: 55, color: "var(--amber)" },
      { name: "Other Bets Drag", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Outperform",
      ratingColor: "var(--green)",
      text: "Alphabet trades at a significant valuation discount to peers despite accelerating revenue growth and expanding margins. The antitrust overhang creates uncertainty but also limits downside expectations. Cloud profitability inflection and AI monetization in Search provide multiple catalysts. Key monitor: DOJ remedy outcome and Search AI cannibalization trends.",
    },
  },

  AMZN: {
    name: "Amazon.com Inc.",
    ticker: "AMZN",
    entityType: "public",
    sector: "Technology",
    industry: "E-Commerce & Cloud",
    hq: "Seattle, WA",
    employees: "1,525,000",
    founded: 1994,
    ceo: "Andy Jassy",
    price: 212.80,
    change: +3.45,
    changePct: +1.65,
    marketCap: "$2.22T",
    peRatio: 42.1,
    divYield: "0.00%",
    beta: 1.15,
    revenue52w: "$620.1B",
    kpis: [
      { label: "Revenue (TTM)", value: "$620.1B", sub: "+12.5% YoY" },
      { label: "Net Income", value: "$44.4B", sub: "7.2% margin" },
      { label: "Free Cash Flow", value: "$38.5B", sub: "+85% YoY" },
      { label: "AWS Revenue", value: "$105.0B", sub: "+19% YoY" },
      { label: "Prime Members", value: "230M+", sub: "Global subscribers" },
      { label: "Debt / Equity", value: "0.58", sub: "$67B total debt" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [386.1, 469.8, 514.0, 574.8, 620.1, 690.0],
      netIncome: [21.3, 33.4, -2.7, 30.4, 44.4, 55.0],
      grossMargin: [39.6, 42.0, 43.8, 46.6, 49.2, 50.5],
      operatingMargin: [5.9, 5.3, 2.4, 6.4, 10.8, 12.0],
      netMargin: [5.5, 7.1, -0.5, 5.3, 7.2, 8.0],
    },
    segments: {
      labels: ["Online Stores", "AWS", "Third-Party Seller", "Advertising", "Subscriptions"],
      values: [38, 17, 24, 9, 7],
      colors: ["#f59e0b", "#6366f1", "#22c55e", "#06b6d4", "#ef4444"],
    },
    competitors: {
      labels: ["Amazon", "Walmart", "Microsoft (Cloud)", "Alibaba", "Shopify"],
      revenue: [620.1, 648.1, 236.6, 130.3, 8.9],
      margin: [7.2, 2.8, 35.3, 6.8, 12.5],
    },
    swot: {
      strengths: [
        "AWS dominates with 31% cloud market share",
        "Unmatched logistics infrastructure globally",
        "Advertising business growing at 24% ($52B run rate)",
        "230M+ Prime members drive recurring revenue",
      ],
      weaknesses: [
        "Razor-thin retail margins vs high-margin peers",
        "Massive workforce creates labor cost exposure",
        "International e-commerce operations still unprofitable",
        "Antitrust scrutiny on marketplace practices",
      ],
      opportunities: [
        "AWS AI services (Bedrock, Trainium) gaining traction",
        "Healthcare disruption via One Medical and pharmacy",
        "Grocery market penetration through Whole Foods + delivery",
        "Advertising monetization across Prime Video",
      ],
      threats: [
        "Temu and Shein disrupting low-cost e-commerce",
        "Azure and GCP gaining cloud market share",
        "Union organizing across fulfillment centers",
        "Regulatory action on marketplace dominance",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Amazon's advertising business is now a $52B annual run rate, making it the 3rd largest ad platform. Prime Video ads launched in 2024 add a new high-margin monetization lever." },
      { tag: "strategy", tagLabel: "Strategy", text: "AWS custom silicon (Graviton, Trainium) delivers 40% better price-performance, attracting cost-conscious AI workloads away from NVIDIA-dependent competitors." },
      { tag: "risk", tagLabel: "Risk", text: "Operating margins expanded from 2.4% to 10.8% in two years, but sustainability depends on continued efficiency gains and AWS growth outpacing retail cost inflation." },
      { tag: "market", tagLabel: "Market", text: "Same-day delivery coverage now reaches 90% of US Prime members. Logistics cost per unit has declined 20% since 2022, widening competitive moat." },
    ],
    risks: [
      { name: "Competitive Risk", level: 62, color: "var(--amber)" },
      { name: "Margin Sustainability", level: 55, color: "var(--amber)" },
      { name: "Labor / Regulatory", level: 58, color: "var(--amber)" },
      { name: "Cloud Competition", level: 50, color: "var(--cyan)" },
      { name: "International Losses", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Outperform",
      ratingColor: "var(--green)",
      text: "Amazon's margin expansion story has legs — advertising, AWS AI services, and logistics efficiency are all high-margin growth vectors. The company is in the early innings of monetizing its infrastructure advantages. Key monitor: AWS growth re-acceleration and retail margin trajectory amid competitive pricing pressure from Temu/Shein.",
    },
  },

  NVDA: {
    name: "NVIDIA Corporation",
    ticker: "NVDA",
    entityType: "public",
    sector: "Technology",
    industry: "Semiconductors",
    hq: "Santa Clara, CA",
    employees: "32,000",
    founded: 1993,
    ceo: "Jensen Huang",
    price: 142.56,
    change: +6.78,
    changePct: +4.99,
    marketCap: "$3.48T",
    peRatio: 55.4,
    divYield: "0.03%",
    beta: 1.68,
    revenue52w: "$130.5B",
    kpis: [
      { label: "Revenue (TTM)", value: "$130.5B", sub: "+122% YoY" },
      { label: "Net Income", value: "$72.9B", sub: "55.9% margin" },
      { label: "Free Cash Flow", value: "$60.9B", sub: "+148% YoY" },
      { label: "Gross Margin", value: "74.6%", sub: "-100bps QoQ" },
      { label: "Data Center Rev", value: "$115.2B", sub: "88% of revenue" },
      { label: "Debt / Equity", value: "0.17", sub: "$8.5B total debt" },
    ],
    financials: {
      years: ["FY21", "FY22", "FY23", "FY24", "FY25", "FY26E"],
      revenue: [16.7, 26.9, 27.0, 60.9, 130.5, 195.0],
      netIncome: [4.3, 9.8, 4.4, 29.8, 72.9, 105.0],
      grossMargin: [62.3, 64.9, 56.9, 72.7, 74.6, 73.5],
      operatingMargin: [27.2, 37.3, 15.6, 54.1, 62.4, 61.0],
      netMargin: [25.6, 36.2, 16.2, 48.8, 55.9, 53.8],
    },
    segments: {
      labels: ["Data Center", "Gaming", "Auto", "Pro Visualization", "OEM"],
      values: [88, 6, 3, 2, 1],
      colors: ["#22c55e", "#6366f1", "#06b6d4", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["NVIDIA", "AMD", "Intel", "Broadcom", "Qualcomm"],
      revenue: [130.5, 25.8, 54.2, 51.6, 42.3],
      margin: [55.9, 5.2, -16.4, 30.1, 24.8],
    },
    swot: {
      strengths: [
        "90%+ share of AI training GPU market",
        "CUDA ecosystem creates massive switching costs",
        "Best-in-class 74.6% gross margins in semis",
        "Full-stack platform (chips + networking + software)",
      ],
      weaknesses: [
        "Extreme customer concentration (hyperscalers)",
        "Data center = 88% of revenue (single segment risk)",
        "US-China export controls limit China TAM",
        "Supply-constrained — cannot meet full demand",
      ],
      opportunities: [
        "Blackwell GPU ramp driving next upgrade cycle",
        "Sovereign AI infrastructure ($50B+ opportunity)",
        "Enterprise AI adoption still in early innings",
        "Automotive and robotics emerging growth vectors",
      ],
      threats: [
        "Hyperscalers developing custom AI accelerators",
        "AMD MI300X gaining share in inference workloads",
        "AI spending bubble risk if ROI timelines extend",
        "Geopolitical risk of expanded export restrictions",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "NVIDIA's revenue has grown 7.8x in 3 years driven by insatiable AI infrastructure demand. Blackwell GPU generation is ramping with $12B+ in Q1 bookings alone." },
      { tag: "risk", tagLabel: "Risk", text: "Customer concentration is a key risk — top 4 hyperscalers represent ~50% of data center revenue. Custom silicon efforts by Google (TPU), Amazon (Trainium), and Meta could erode share." },
      { tag: "strategy", tagLabel: "Strategy", text: "NVIDIA's strategy has evolved from chip supplier to full-stack AI platform — CUDA, cuDNN, TensorRT, and NIM microservices create deep ecosystem lock-in beyond hardware." },
      { tag: "market", tagLabel: "Market", text: "Sovereign AI is a $50B+ opportunity as 40+ nations invest in domestic AI infrastructure. NVIDIA has secured partnerships with UAE, India, Japan, and France." },
    ],
    risks: [
      { name: "Concentration Risk", level: 78, color: "var(--red)" },
      { name: "Custom Silicon Threat", level: 65, color: "var(--amber)" },
      { name: "Valuation Risk", level: 70, color: "var(--amber)" },
      { name: "Geopolitical / Export", level: 62, color: "var(--amber)" },
      { name: "Cyclicality", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Outperform",
      ratingColor: "var(--green)",
      text: "NVIDIA remains the essential infrastructure pick for the AI era. Blackwell demand visibility is strong through 2026, and the software platform strategy adds durable competitive advantages. Valuation is demanding but supported by extraordinary growth. Key monitor: hyperscaler CapEx trajectories and custom silicon adoption rates.",
    },
  },

  META: {
    name: "Meta Platforms Inc.",
    ticker: "META",
    entityType: "public",
    sector: "Technology",
    industry: "Social Media & Advertising",
    hq: "Menlo Park, CA",
    employees: "72,400",
    founded: 2004,
    ceo: "Mark Zuckerberg",
    price: 628.40,
    change: -4.12,
    changePct: -0.65,
    marketCap: "$1.58T",
    peRatio: 28.3,
    divYield: "0.32%",
    beta: 1.22,
    revenue52w: "$160.0B",
    kpis: [
      { label: "Revenue (TTM)", value: "$160.0B", sub: "+22.1% YoY" },
      { label: "Net Income", value: "$55.2B", sub: "34.5% margin" },
      { label: "Free Cash Flow", value: "$48.3B", sub: "+25.6% YoY" },
      { label: "Daily Active People", value: "3.27B", sub: "+5% YoY" },
      { label: "ARPU", value: "$48.85", sub: "+17% YoY" },
      { label: "Reality Labs Loss", value: "-$16.1B", sub: "Annual operating loss" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [85.9, 117.9, 116.6, 134.9, 160.0, 188.0],
      netIncome: [29.1, 39.4, 23.2, 39.1, 55.2, 66.0],
      grossMargin: [80.6, 80.8, 78.4, 80.7, 81.5, 82.0],
      operatingMargin: [38.0, 39.6, 24.8, 34.7, 41.4, 42.5],
      netMargin: [33.9, 33.4, 19.9, 29.0, 34.5, 35.1],
    },
    segments: {
      labels: ["Facebook", "Instagram", "WhatsApp", "Messenger", "Reality Labs"],
      values: [38, 35, 10, 7, 10],
      colors: ["#6366f1", "#ef4444", "#22c55e", "#06b6d4", "#f59e0b"],
    },
    competitors: {
      labels: ["Meta", "Alphabet (Ads)", "TikTok (est.)", "Snap", "Pinterest"],
      revenue: [160.0, 265.0, 35.0, 5.4, 3.6],
      margin: [34.5, 26.4, 15.0, -2.5, 10.2],
    },
    swot: {
      strengths: [
        "3.27B daily active users across family of apps",
        "Industry-best ad targeting via AI recommendation engine",
        "Reels growth closing gap with TikTok engagement",
        "81.5% gross margins — best among mega-cap tech",
      ],
      weaknesses: [
        "98% revenue dependence on advertising",
        "Reality Labs losing $16B annually with unclear path",
        "Brand perception challenges around data privacy",
        "Limited enterprise/B2B revenue diversification",
      ],
      opportunities: [
        "Business messaging monetization on WhatsApp",
        "AI-powered ad creation tools expanding SMB TAM",
        "Meta AI assistant driving engagement and data",
        "Threads growing as X/Twitter alternative",
      ],
      threats: [
        "TikTok competition for youth engagement",
        "Privacy regulation reducing targeting effectiveness",
        "Apple ATT framework limiting iOS ad measurement",
        "Regulatory pressure on data collection practices",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Reels now generates over $10B annually with improving engagement-to-monetization ratio. AI-recommended content drives 30% of all time spent on Instagram and Facebook." },
      { tag: "strategy", tagLabel: "Strategy", text: "Llama open-source AI models serve a dual purpose — building developer ecosystem moat while reducing dependency on external AI providers. Meta AI has 600M+ monthly active users." },
      { tag: "risk", tagLabel: "Risk", text: "Reality Labs has accumulated $50B+ in operating losses since 2020. While the metaverse thesis remains unproven commercially, AR glasses (Orion) show more near-term promise." },
      { tag: "market", tagLabel: "Market", text: "Meta's AI ad tools have expanded SMB advertiser base by 25% — automated creative generation and Advantage+ campaigns lower the barrier to effective digital advertising." },
    ],
    risks: [
      { name: "Revenue Concentration", level: 72, color: "var(--amber)" },
      { name: "Reality Labs Losses", level: 68, color: "var(--amber)" },
      { name: "Privacy / Regulatory", level: 65, color: "var(--amber)" },
      { name: "TikTok Competition", level: 55, color: "var(--cyan)" },
      { name: "Brand Perception", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Outperform",
      ratingColor: "var(--green)",
      text: "Meta's 'Year of Efficiency' transformation has been extraordinary — operating margins rebounded from 25% to 41% while revenue growth reaccelerated. The AI-driven ad engine is the best in the industry. Reality Labs remains the key debate, but core business strength justifies current valuation. Key monitor: WhatsApp monetization progress and Reality Labs loss trajectory.",
    },
  },

  CDB: {
    name: "CelcomDigi Berhad",
    ticker: "CDB",
    entityType: "public",
    sector: "Telecommunications",
    industry: "Integrated Telecom",
    hq: "Kuala Lumpur, Malaysia",
    employees: "12,800",
    founded: 2022,
    ceo: "Datuk Idham Nawawi",
    price: 3.85,
    change: +0.05,
    changePct: +1.32,
    marketCap: "MYR 45.3B",
    peRatio: 32.4,
    divYield: "3.2%",
    beta: 0.72,
    revenue52w: "MYR 13.2B",
    kpis: [
      { label: "Revenue (TTM)", value: "MYR 13.2B", sub: "+4.8% YoY" },
      { label: "EBITDA", value: "MYR 6.1B", sub: "46.2% margin" },
      { label: "Net Income", value: "MYR 1.4B", sub: "10.6% margin" },
      { label: "Subscribers", value: "20.5M", sub: "#1 in Malaysia" },
      { label: "ARPU", value: "MYR 42", sub: "+5.2% YoY" },
      { label: "Net Debt/EBITDA", value: "2.1x", sub: "MYR 12.8B net debt" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [11.0, 11.2, 12.0, 12.6, 13.2, 14.0],
      netIncome: [1.8, 1.6, 0.8, 1.1, 1.4, 1.7],
      grossMargin: [62.0, 60.5, 58.2, 59.8, 61.4, 62.5],
      operatingMargin: [22.0, 20.5, 15.2, 18.4, 20.8, 22.0],
      netMargin: [16.4, 14.3, 6.7, 8.7, 10.6, 12.1],
    },
    segments: {
      labels: ["Mobile Postpaid", "Mobile Prepaid", "Home Fiber", "Enterprise", "Digital Services"],
      values: [35, 30, 12, 15, 8],
      colors: ["#6366f1", "#22c55e", "#06b6d4", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["CelcomDigi", "Maxis", "U Mobile", "TM", "YTL Comms"],
      revenue: [13.2, 9.8, 3.5, 12.4, 1.8],
      margin: [10.6, 14.2, 2.8, 11.5, 8.4],
    },
    swot: {
      strengths: [
        "#1 mobile operator in Malaysia by subscribers (20.5M)",
        "Merger synergies delivering MYR 800M+ annual savings",
        "Extensive 4G/5G dual network with widest coverage",
        "Strong enterprise division with government contracts",
      ],
      weaknesses: [
        "Integration complexity post Celcom-Digi merger",
        "Higher leverage (2.1x Net Debt/EBITDA) vs peers",
        "Prepaid ARPU erosion from competitive pressure",
        "Legacy IT systems still under consolidation",
      ],
      opportunities: [
        "5G monetization via enterprise and fixed wireless",
        "Digital services (fintech, cloud) as new revenue streams",
        "ARPU uplift from postpaid migration and bundling",
        "Southeast Asia expansion leveraging Telenor relationship",
      ],
      threats: [
        "Aggressive pricing by U Mobile and new MVNOs",
        "Regulatory risk from spectrum reallocation and JENDELA",
        "Rising energy costs impacting tower operations",
        "OTT substitution reducing voice and SMS revenue",
      ],
    },
    insights: [
      { tag: "strategy", tagLabel: "Strategy", text: "The Celcom-Digi merger has yielded MYR 800M+ in run-rate synergies, ahead of the MYR 700M target. Network consolidation is 65% complete with full integration expected by mid-2025." },
      { tag: "growth", tagLabel: "Growth", text: "Home Fiber segment is growing at 28% YoY, reaching 650K subscribers. CelcomDigi is leveraging its mobile base to cross-sell converged packages at 15% attach rates." },
      { tag: "market", tagLabel: "Market", text: "Malaysia's 5G rollout presents a MYR 4B incremental revenue opportunity by 2028. CelcomDigi's dual network gives it the best position to capture enterprise 5G workloads." },
      { tag: "risk", tagLabel: "Risk", text: "Prepaid segment faces structural decline as OTT messaging cannibalizes voice/SMS. CelcomDigi is mitigating through data monetization and prepaid-to-postpaid migration programs." },
    ],
    risks: [
      { name: "Integration Execution", level: 55, color: "var(--amber)" },
      { name: "Competitive Pressure", level: 62, color: "var(--amber)" },
      { name: "Leverage Risk", level: 50, color: "var(--cyan)" },
      { name: "Regulatory Risk", level: 45, color: "var(--cyan)" },
      { name: "Technology Disruption", level: 38, color: "var(--green)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "CelcomDigi is the clear market leader in Malaysia's telecom space following a well-executed merger integration. Synergy realization is running ahead of plan, supporting margin expansion toward 22%+ operating margin. 5G monetization and converged bundling offer medium-term upside. Key monitor: merger synergy sustainability, competitive pricing dynamics, and regulatory developments around spectrum.",
    },
  },

  TSLA: {
    name: "Tesla Inc.",
    ticker: "TSLA",
    entityType: "public",
    sector: "Automotive",
    industry: "Electric Vehicles & Energy",
    hq: "Austin, TX",
    employees: "140,500",
    founded: 2003,
    ceo: "Elon Musk",
    price: 342.15,
    change: +12.34,
    changePct: +3.74,
    marketCap: "$1.10T",
    peRatio: 95.2,
    divYield: "0.00%",
    beta: 2.05,
    revenue52w: "$97.7B",
    kpis: [
      { label: "Revenue (TTM)", value: "$97.7B", sub: "+1.2% YoY" },
      { label: "Net Income", value: "$7.1B", sub: "7.3% margin" },
      { label: "Free Cash Flow", value: "$4.4B", sub: "-25% YoY" },
      { label: "Deliveries (TTM)", value: "1.79M", sub: "-1.1% YoY" },
      { label: "Energy Storage", value: "$10.4B", sub: "+67% YoY" },
      { label: "Gross Margin (Auto)", value: "16.3%", sub: "-380bps YoY" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [31.5, 53.8, 81.5, 96.8, 97.7, 112.0],
      netIncome: [0.7, 5.5, 12.6, 15.0, 7.1, 9.5],
      grossMargin: [21.0, 25.3, 25.6, 18.2, 17.8, 19.0],
      operatingMargin: [6.3, 12.1, 16.8, 9.2, 7.2, 8.5],
      netMargin: [2.2, 10.3, 15.4, 15.5, 7.3, 8.5],
    },
    segments: {
      labels: ["Auto Sales", "Auto Leasing", "Energy", "Services", "Regulatory Credits"],
      values: [64, 5, 11, 13, 7],
      colors: ["#ef4444", "#f59e0b", "#22c55e", "#06b6d4", "#6366f1"],
    },
    competitors: {
      labels: ["Tesla", "BYD", "Toyota", "VW Group", "Hyundai-Kia"],
      revenue: [97.7, 84.9, 274.4, 293.8, 154.3],
      margin: [7.3, 5.2, 8.9, 5.4, 6.7],
    },
    swot: {
      strengths: [
        "Leading EV brand with global charging network",
        "Best-in-class manufacturing efficiency (cost per vehicle)",
        "Energy storage business growing 67% with high margins",
        "Full self-driving software as high-margin monetization lever",
      ],
      weaknesses: [
        "Vehicle delivery growth has stalled (-1.1% YoY)",
        "Gross margins compressed from price cuts globally",
        "CEO distraction across multiple ventures",
        "Aging model lineup (Model 3/Y dominate sales)",
      ],
      opportunities: [
        "Robotaxi service launch could redefine valuation",
        "Energy storage market projected to grow 10x by 2030",
        "Affordable $25K model expanding total addressable market",
        "Optimus humanoid robot potential long-term optionality",
      ],
      threats: [
        "BYD and Chinese EV makers competing aggressively on price",
        "Legacy automakers ramping EV portfolios",
        "Brand perception issues in key European/Chinese markets",
        "Regulatory risk around autonomous driving claims",
      ],
    },
    insights: [
      { tag: "risk", tagLabel: "Risk", text: "Tesla's auto gross margin has declined from 25.6% to 16.3% over two years due to aggressive price cuts. Volume growth has not offset margin compression, pressuring profitability." },
      { tag: "growth", tagLabel: "Growth", text: "Energy storage deployed 31 GWh in FY24 (+67% YoY) with improving margins. This segment could contribute $20B+ in revenue by FY27 and become Tesla's highest-margin business." },
      { tag: "strategy", tagLabel: "Strategy", text: "FSD (Full Self-Driving) v13 shows significant improvement in autonomous capability. If robotaxi launches successfully, it fundamentally changes Tesla's unit economics and TAM." },
      { tag: "market", tagLabel: "Market", text: "BYD has overtaken Tesla in total global vehicle sales (including hybrids) and is expanding aggressively into Southeast Asia and Europe with 30-40% price advantages." },
    ],
    risks: [
      { name: "Margin Pressure", level: 75, color: "var(--red)" },
      { name: "Competitive Risk", level: 72, color: "var(--red)" },
      { name: "Valuation Risk", level: 80, color: "var(--red)" },
      { name: "Execution Risk (FSD)", level: 68, color: "var(--amber)" },
      { name: "CEO / Governance", level: 60, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Tesla's investment case has shifted from pure EV growth to a complex bet on robotaxi, energy, and AI. Core auto business faces margin headwinds and intensifying competition from BYD and Chinese OEMs. Energy storage and FSD optionality justify a premium, but current valuation implies flawless execution on multiple moonshots. Key monitor: FSD regulatory approvals, affordable model launch timeline, and China market share trends.",
    },
  },
};
