Object.assign(COMPANIES, {
  PERODUA: {
    name: "Perodua Auto Corporation Sdn Bhd",
    ticker: "PERODUA",
    entityType: "private",
    sector: "Automotive",
    industry: "Vehicle Manufacturing",
    hq: "Shah Alam, Malaysia",
    employees: "12,000",
    founded: 1993,
    ceo: "Zainal Abidin Ahmad",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 15.2B",
    kpis: [
      { label: "Vehicle Sales", value: "~300K", sub: "units/year" },
      { label: "Market Share", value: "42%", sub: "Malaysia passenger vehicles" },
      { label: "Production Capacity", value: "350K", sub: "units/year" },
      { label: "Dealer Network", value: "200+", sub: "outlets nationwide" },
      { label: "Export Volume", value: "~5K", sub: "units/year" },
      { label: "Model Lineup", value: "6", sub: "active models" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [12.8, 13.2, 14.1, 14.8, 15.2, 15.8],
      netIncome: [0.9, 0.95, 1.0, 1.05, 1.1, 1.15],
      grossMargin: [18, 19, 19, 20, 20, 21],
      operatingMargin: [8, 8.5, 9, 9, 9.5, 10],
      netMargin: [7, 7.2, 7.1, 7.1, 7.2, 7.3],
    },
    segments: {
      labels: ["Passenger Cars", "SUV", "Commercial", "Spare Parts", "Services"],
      values: [65, 22, 5, 5, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Perodua", "Proton", "Toyota MY", "Honda MY", "Mazda MY"],
      revenue: [15.2, 8.5, 6.2, 4.8, 2.1],
      margin: [7.2, 4.5, 6.8, 5.2, 4.1],
    },
    swot: {
      strengths: ["#1 market share in Malaysia", "Strong local manufacturing base", "Affordable pricing strategy", "Extensive dealer network"],
      weaknesses: ["Limited export presence", "Dependence on domestic market", "Narrow product range vs global OEMs", "EV transition lag"],
      opportunities: ["EV expansion with Daihatsu partnership", "ASEAN export market", "Used car segment growth", "Digital sales channels"],
      threats: ["EV disruption from Chinese brands", "Proton resurgence", "Import tax policy changes", "Raw material cost inflation"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Maintained #1 position with ~300K vehicles sold; D66K and Bezza driving volume." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on CKD localization and cost efficiency; exploring EV roadmap with Daihatsu." },
      { tag: "risk", tagLabel: "Risk", text: "Daihatsu safety scandal may impact brand perception; EV adoption accelerating." },
      { tag: "market", tagLabel: "Market", text: "Malaysia automotive market recovering; TIV expected ~700K in 2025." },
    ],
    risks: [
      { name: "Daihatsu Scandal", level: 45, color: "var(--cyan)" },
      { name: "EV Transition", level: 38, color: "var(--green)" },
      { name: "Competition", level: 52, color: "var(--cyan)" },
      { name: "Raw Material Costs", level: 48, color: "var(--cyan)" },
      { name: "Policy Changes", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Perodua remains the dominant player in Malaysia's automotive market with strong volume and brand loyalty. EV strategy and Daihatsu partnership developments will shape medium-term outlook.",
    },
  },

  HONDA_MY: {
    name: "Honda Malaysia Sdn Bhd",
    ticker: "HONDA_MY",
    entityType: "private",
    sector: "Automotive",
    industry: "Vehicle Manufacturing & Distribution",
    hq: "Pegoh, Melaka",
    employees: "3,500",
    founded: 2000,
    ceo: "Hitoshi Fushiki",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 4.8B",
    kpis: [
      { label: "Vehicle Sales", value: "~80K", sub: "units/year" },
      { label: "Market Share", value: "11%", sub: "Malaysia passenger vehicles" },
      { label: "Production Capacity", value: "100K", sub: "units/year" },
      { label: "Dealer Network", value: "100+", sub: "outlets nationwide" },
      { label: "CKD Models", value: "8", sub: "local assembly" },
      { label: "CBU Models", value: "5", sub: "imported" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4.2, 4.0, 4.5, 4.6, 4.8, 5.0],
      netIncome: [0.22, 0.18, 0.25, 0.26, 0.28, 0.30],
      grossMargin: [12, 11, 12, 12, 12, 13],
      operatingMargin: [5.5, 4.5, 5.8, 5.9, 6.0, 6.2],
      netMargin: [5.2, 4.5, 5.6, 5.7, 5.8, 6.0],
    },
    segments: {
      labels: ["Sedan", "SUV", "MPV", "Hatchback", "Spare Parts"],
      values: [35, 40, 15, 5, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Honda MY", "Toyota MY", "Proton", "Mazda MY", "Perodua"],
      revenue: [4.8, 6.2, 8.5, 2.1, 15.2],
      margin: [5.8, 6.8, 4.5, 4.1, 7.2],
    },
    swot: {
      strengths: ["Strong brand reputation", "CKD manufacturing in Melaka", "Popular HR-V and City models", "Quality perception"],
      weaknesses: ["Higher price than national brands", "Limited EV lineup in Malaysia", "Dependence on Japan HQ", "Smaller dealer network vs Perodua"],
      opportunities: ["EV expansion (e:HEV models)", "SUV segment growth", "Premium segment positioning", "After-sales revenue"],
      threats: ["Chinese EV competition", "Proton X50 rivalry", "Currency volatility", "Tax policy changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "HR-V and City remain top sellers; e:HEV hybrid models gaining traction." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on CKD localization and hybrid expansion; premium positioning in B/C segment." },
      { tag: "risk", tagLabel: "Risk", text: "EV competition intensifying; need to accelerate electrification roadmap." },
      { tag: "market", tagLabel: "Market", text: "Non-national segment competitive; Honda holds strong share in premium B-segment." },
    ],
    risks: [
      { name: "EV Competition", level: 42, color: "var(--cyan)" },
      { name: "Currency", level: 52, color: "var(--cyan)" },
      { name: "Proton Rivalry", level: 48, color: "var(--cyan)" },
      { name: "Supply Chain", level: 38, color: "var(--green)" },
      { name: "Policy", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Honda Malaysia maintains strong brand and product quality. Hybrid expansion and e:HEV models support growth; EV adoption will be key to long-term competitiveness.",
    },
  },

  TESLA_MY: {
    name: "Tesla Sdn. Bhd.",
    ticker: "TESLA_MY",
    entityType: "private",
    sector: "Automotive",
    industry: "Electric Vehicle Distribution",
    hq: "Kuala Lumpur, Malaysia",
    employees: "150",
    founded: 2023,
    ceo: "Isabelle Zhang",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 0.8B",
    kpis: [
      { label: "Vehicle Sales", value: "~3K", sub: "units/year" },
      { label: "Market Share", value: "0.4%", sub: "Malaysia TIV" },
      { label: "Supercharger Sites", value: "25+", sub: "nationwide" },
      { label: "Service Centers", value: "5", sub: "locations" },
      { label: "Model Lineup", value: "6", sub: "Model 3, Y, S, X, Cybertruck" },
      { label: "EV Penetration", value: "~15%", sub: "of premium segment" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0, 0, 0, 0.3, 0.8, 1.2],
      netIncome: [0, 0, 0, -0.02, 0.05, 0.08],
      grossMargin: [0, 0, 0, 18, 20, 22],
      operatingMargin: [0, 0, 0, -5, 6, 8],
      netMargin: [0, 0, 0, -6.7, 6.3, 6.7],
    },
    segments: {
      labels: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
      values: [45, 40, 5, 5, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Tesla MY", "BYD MY", "BMW MY", "Mercedes MY", "Proton EV"],
      revenue: [0.8, 1.5, 2.2, 0.9, 0.3],
      margin: [6.3, 8.5, 5.2, 4.8, -2],
    },
    swot: {
      strengths: ["Global EV brand leader", "Supercharger network", "Direct sales model", "Strong tech ecosystem"],
      weaknesses: ["Small local presence", "Limited service network", "Premium pricing", "No local assembly"],
      opportunities: ["EV tax incentives", "Growing EV adoption", "Charging infrastructure expansion", "Model 2/affordable EV"],
      threats: ["BYD and Chinese EV competition", "Charging infrastructure gaps", "Policy uncertainty", "Currency volatility"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Launched Malaysia 2023; Model 3 and Y driving volume; early mover in premium EV." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on direct sales and Supercharger expansion; leveraging government EV incentives." },
      { tag: "risk", tagLabel: "Risk", text: "BYD and Chinese brands expanding aggressively; pricing pressure." },
      { tag: "market", tagLabel: "Market", text: "Malaysia EV market nascent but growing; Tesla well-positioned in premium segment." },
    ],
    risks: [
      { name: "BYD Competition", level: 58, color: "var(--amber)" },
      { name: "Infrastructure", level: 48, color: "var(--cyan)" },
      { name: "Policy", level: 45, color: "var(--cyan)" },
      { name: "Currency", level: 42, color: "var(--cyan)" },
      { name: "Scale", level: 55, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Tesla Malaysia is early in its journey; strong brand but small scale. EV incentives and Supercharger expansion support growth; competition from BYD will intensify.",
    },
  },

  MAHB: {
    name: "Malaysia Airports Holdings Berhad",
    ticker: "MAHB",
    entityType: "public",
    sector: "Aviation & Transport",
    industry: "Airport Operations",
    hq: "Sepang, Malaysia",
    employees: "12,000",
    founded: 1992,
    ceo: "Ismail bin Ahmad",
    price: 9.85,
    change: 0.35,
    changePct: 3.7,
    marketCap: "MYR 15.2B",
    peRatio: 28.5,
    divYield: "1.2%",
    beta: 1.15,
    revenue52w: "MYR 5.2B",
    kpis: [
      { label: "Airports Managed", value: "39", sub: "Malaysia + Turkey" },
      { label: "Passenger Traffic", value: "~95M", sub: "PAX/year" },
      { label: "KLIA Traffic", value: "~52M", sub: "PAX/year" },
      { label: "Aircraft Movements", value: "~650K", sub: "per year" },
      { label: "Retail Revenue", value: "~35%", sub: "of total revenue" },
      { label: "Aeronautical Revenue", value: "~45%", sub: "of total revenue" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [3.2, 2.1, 3.8, 4.8, 5.2, 5.8],
      netIncome: [-0.5, -0.8, 0.2, 0.9, 0.95, 1.1],
      grossMargin: [25, 15, 28, 32, 33, 35],
      operatingMargin: [-5, -15, 8, 12, 13, 15],
      netMargin: [-15.6, -38.1, 5.3, 18.8, 18.3, 19.0],
    },
    segments: {
      labels: ["Aeronautical", "Retail", "Parking", "Hotel", "Others"],
      values: [45, 35, 8, 5, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MAHB", "Changi Airport", "Suvarnabhumi", "Changi Corp", "AOT Thailand"],
      revenue: [5.2, 4.5, 2.8, 3.2, 2.5],
      margin: [18.3, 25, 12, 18, 10],
    },
    swot: {
      strengths: ["Monopoly on Malaysian airports", "KLIA as regional hub", "Strong retail/concession", "Turkey SAW stake"],
      weaknesses: ["Dependence on tourism", "High capex requirements", "Regulatory constraints", "COVID recovery lag"],
      opportunities: ["Tourism recovery", "Cargo growth", "Digital transformation", "Expansion projects"],
      threats: ["Competition from Singapore", "Economic slowdown", "Fuel price volatility", "Regulatory changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Passenger traffic recovering post-COVID; KLIA and regional airports driving volume." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on non-aeronautical revenue and digital services; airport expansion." },
      { tag: "risk", tagLabel: "Risk", text: "Tourism sensitivity; competition from Singapore and regional hubs." },
      { tag: "market", tagLabel: "Market", text: "Malaysia aviation sector recovering; MAHB well-positioned as regional hub." },
    ],
    risks: [
      { name: "Tourism", level: 48, color: "var(--cyan)" },
      { name: "Competition", level: 52, color: "var(--cyan)" },
      { name: "Regulation", level: 42, color: "var(--cyan)" },
      { name: "Capex", level: 55, color: "var(--cyan)" },
      { name: "Economic", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "MAHB benefits from tourism recovery and KLIA hub status. Non-aeronautical revenue and digital initiatives support growth; valuation reasonable for recovery play.",
    },
  },

  MAG: {
    name: "Malaysia Aviation Group",
    ticker: "MAG",
    entityType: "government",
    sector: "Government",
    industry: "Aviation & Aviation Partners",
    hq: "Kuala Lumpur, Malaysia",
    employees: "13,000",
    founded: 2015,
    ceo: "Captain Izham Ismail",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 12.5B",
    kpis: [
      { label: "Annual Budget", value: "MYR 12.5B", sub: "operating budget" },
      { label: "Staff Count", value: "13,000", sub: "employees" },
      { label: "Programs Delivered", value: "Fleet renewal", sub: "A350, A330neo" },
      { label: "Digital Adoption Rate", value: "65%", sub: "e-ticketing" },
      { label: "Service Coverage", value: "50+", sub: "destinations" },
      { label: "Key Initiative", value: "Restructuring", sub: "post-COVID recovery" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [8.5, 4.2, 5.8, 9.2, 12.5, 14.0],
      netIncome: [-5.0, -4.5, -2.0, -0.5, 0.2, 0.5],
      grossMargin: [15, 0, 0, 5, 8, 10],
      operatingMargin: [-25, -35, -15, -5, 2, 4],
      netMargin: [-58.8, -107.1, -34.5, -5.4, 1.6, 3.6],
    },
    segments: {
      labels: ["Passenger", "Cargo", "MRO", "Ground", "Others"],
      values: [70, 8, 10, 7, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MAG", "AirAsia", "Singapore Airlines", "Thai Airways", "Garuda"],
      revenue: [12.5, 8.2, 18.5, 6.2, 4.5],
      margin: [1.6, 4.2, 5.5, -2, -8],
    },
    swot: {
      strengths: ["National carrier status", "Government support", "KUL hub advantage", "Fleet modernization"],
      weaknesses: ["Legacy cost structure", "Past restructuring burden", "Limited LCC presence", "Competition from AirAsia"],
      opportunities: ["Tourism recovery", "Cargo growth", "Regional expansion", "JVs"],
      threats: ["Fuel price volatility", "Competition", "Economic downturn", "Regulatory constraints"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Post-restructuring recovery; fleet renewal and route expansion driving revenue." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on premium segment and regional connectivity; cost optimization." },
      { tag: "risk", tagLabel: "Risk", text: "Government ownership limits flexibility; competition from LCCs." },
      { tag: "market", tagLabel: "Market", text: "Malaysia aviation recovering; MAG as national carrier key to hub strategy." },
    ],
    risks: [
      { name: "Competition", level: 58, color: "var(--amber)" },
      { name: "Fuel Costs", level: 52, color: "var(--cyan)" },
      { name: "Restructuring", level: 48, color: "var(--cyan)" },
      { name: "Economic", level: 45, color: "var(--cyan)" },
      { name: "Regulation", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Progressing",
      ratingColor: "var(--cyan)",
      text: "MAG restructuring showing progress; fleet renewal and tourism recovery support revenue. Profitability remains fragile; long-term sustainability depends on cost discipline.",
    },
  },

  GARDENIA: {
    name: "Gardenia Bakeries (KL) Sdn. Bhd.",
    ticker: "GARDENIA",
    entityType: "private",
    sector: "Consumer",
    industry: "Food & Beverage",
    hq: "Shah Alam, Malaysia",
    employees: "2,500",
    founded: 1986,
    ceo: "Richard Tan",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.8B",
    kpis: [
      { label: "Market Share", value: "42%", sub: "Malaysia bread market" },
      { label: "Production Capacity", value: "2M", sub: "loaves/day" },
      { label: "SKUs", value: "80+", sub: "product variants" },
      { label: "Distribution", value: "50K+", sub: "outlets" },
      { label: "Export Volume", value: "~5%", sub: "of revenue" },
      { label: "Brand Penetration", value: "95%", sub: "household awareness" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1.6, 1.65, 1.7, 1.75, 1.8, 1.85],
      netIncome: [0.12, 0.13, 0.14, 0.14, 0.15, 0.16],
      grossMargin: [28, 29, 29, 30, 30, 31],
      operatingMargin: [9, 9.5, 10, 10, 10.5, 11],
      netMargin: [7.5, 7.9, 8.2, 8.0, 8.3, 8.6],
    },
    segments: {
      labels: ["White Bread", "Wholemeal", "Buns", "Cakes", "Others"],
      values: [45, 25, 15, 8, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Gardenia", "Massimo", "High 5", "Sunshine", "BreadStory"],
      revenue: [1.8, 0.9, 0.5, 0.4, 0.2],
      margin: [8.3, 6.5, 5.2, 4.8, 3.5],
    },
    swot: {
      strengths: ["#1 bread brand", "Strong distribution", "Brand trust", "Quality perception"],
      weaknesses: ["Dependence on wheat imports", "Limited product innovation", "Premium pricing", "Single category focus"],
      opportunities: ["Healthier variants", "Premium segment", "Export expansion", "Digital sales"],
      threats: ["Input cost inflation", "Competition from Massimo", "Consumer preference shift", "Currency volatility"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Steady market share; wholemeal and healthier variants driving growth." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on quality and distribution; exploring premium and health segments." },
      { tag: "risk", tagLabel: "Risk", text: "Wheat price volatility; competition from Massimo and private label." },
      { tag: "market", tagLabel: "Market", text: "Malaysia bread market mature; Gardenia dominant with strong brand." },
    ],
    risks: [
      { name: "Input Costs", level: 52, color: "var(--cyan)" },
      { name: "Competition", level: 45, color: "var(--cyan)" },
      { name: "Currency", level: 48, color: "var(--cyan)" },
      { name: "Consumer Shift", level: 38, color: "var(--green)" },
      { name: "Supply Chain", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Gardenia remains #1 in Malaysia bread market with strong brand and distribution. Input cost management and product innovation key to sustaining margins.",
    },
  },

  PANASONIC_MY: {
    name: "Panasonic Manufacturing Malaysia Berhad",
    ticker: "PANASONIC_MY",
    entityType: "public",
    sector: "Consumer",
    industry: "Electronics Manufacturing",
    hq: "Shah Alam, Malaysia",
    employees: "8,000",
    founded: 1972,
    ceo: "Yusuke Fukushima",
    price: 22.50,
    change: 0.85,
    changePct: 3.9,
    marketCap: "MYR 2.8B",
    peRatio: 18.5,
    divYield: "2.5%",
    beta: 1.05,
    revenue52w: "MYR 3.2B",
    kpis: [
      { label: "Production Lines", value: "12", sub: "factories" },
      { label: "Export Ratio", value: "75%", sub: "of revenue" },
      { label: "Product Categories", value: "8", sub: "AC, refrigerators, etc." },
      { label: "R&D Investment", value: "2.5%", sub: "of revenue" },
      { label: "Automation Rate", value: "45%", sub: "production" },
      { label: "Quality Certifications", value: "ISO 9001", sub: "and others" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.8, 3.0, 3.1, 3.15, 3.2, 3.3],
      netIncome: [0.12, 0.14, 0.15, 0.16, 0.15, 0.17],
      grossMargin: [18, 19, 19, 20, 19, 20],
      operatingMargin: [5, 5.5, 5.8, 6, 5.5, 6],
      netMargin: [4.3, 4.7, 4.8, 5.1, 4.7, 5.2],
    },
    segments: {
      labels: ["Air Conditioners", "Refrigerators", "Washing", "Components", "Others"],
      values: [45, 25, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Panasonic MY", "Daikin MY", "Samsung MY", "LG MY", "Midea"],
      revenue: [3.2, 1.8, 2.5, 1.2, 2.0],
      margin: [4.7, 6.2, 5.5, 4.2, 5.8],
    },
    swot: {
      strengths: ["Strong manufacturing base", "Export-oriented", "Japanese quality", "Diverse product range"],
      weaknesses: ["Dependence on Japan HQ", "Competition from Chinese brands", "Currency sensitivity", "Limited local brand"],
      opportunities: ["EV components", "Energy efficiency", "Smart home", "ASEAN expansion"],
      threats: ["Chinese competition", "Raw material costs", "Supply chain disruption", "Currency volatility"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Steady revenue from AC and appliances; export growth to ASEAN." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on manufacturing efficiency and EV components; automation expansion." },
      { tag: "risk", tagLabel: "Risk", text: "Chinese brand competition; raw material and currency volatility." },
      { tag: "market", tagLabel: "Market", text: "Malaysia electronics manufacturing hub; Panasonic key player." },
    ],
    risks: [
      { name: "Competition", level: 55, color: "var(--cyan)" },
      { name: "Currency", level: 52, color: "var(--cyan)" },
      { name: "Raw Materials", level: 48, color: "var(--cyan)" },
      { name: "Supply Chain", level: 45, color: "var(--cyan)" },
      { name: "Demand", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Panasonic Malaysia benefits from export hub status and Japanese quality. EV components and automation support growth; competition and currency headwinds remain.",
    },
  },

  ALAMFLORA: {
    name: "Alam Flora Sdn Bhd",
    ticker: "ALAMFLORA",
    entityType: "private",
    sector: "Consumer",
    industry: "Waste Management",
    hq: "Shah Alam, Malaysia",
    employees: "4,500",
    founded: 1996,
    ceo: "Mohd Zain Hassan",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 0.9B",
    kpis: [
      { label: "Service Coverage", value: "3", sub: "states (KL, Pahang, Terengganu)" },
      { label: "Households Served", value: "2M+", sub: "customers" },
      { label: "Collection Rate", value: "98%", sub: "daily collection" },
      { label: "Fleet Size", value: "800+", sub: "vehicles" },
      { label: "Recycling Rate", value: "25%", sub: "waste diverted" },
      { label: "Concession Period", value: "25 years", sub: "contract" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0.75, 0.78, 0.82, 0.85, 0.9, 0.95],
      netIncome: [0.05, 0.055, 0.06, 0.062, 0.065, 0.07],
      grossMargin: [22, 23, 23, 24, 24, 25],
      operatingMargin: [8, 8.5, 9, 9, 9.5, 10],
      netMargin: [6.7, 7.1, 7.3, 7.3, 7.2, 7.4],
    },
    segments: {
      labels: ["Collection", "Recycling", "Landfill", "Consulting", "Others"],
      values: [45, 20, 25, 5, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Alam Flora", "SWM", "E-Idaman", "KDEB", "Cypark"],
      revenue: [0.9, 0.6, 0.4, 0.5, 0.3],
      margin: [7.2, 6.5, 5.2, 4.8, 3.5],
    },
    swot: {
      strengths: ["Long concession", "Strong service record", "Government contracts", "Integrated waste management"],
      weaknesses: ["Limited geographic coverage", "Concession dependence", "Regulatory constraints", "Capex intensive"],
      opportunities: ["Waste-to-energy", "Recycling expansion", "New concessions", "Circular economy"],
      threats: ["Contract renewal", "Regulatory changes", "Cost inflation", "Competition"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Stable revenue from concession; recycling and WTE expansion opportunities." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on operational efficiency and sustainability; diversification." },
      { tag: "risk", tagLabel: "Risk", text: "Concession renewal risk; regulatory and cost pressures." },
      { tag: "market", tagLabel: "Market", text: "Malaysia waste management growing; Alam Flora key player in central region." },
    ],
    risks: [
      { name: "Concession", level: 52, color: "var(--cyan)" },
      { name: "Regulation", level: 48, color: "var(--cyan)" },
      { name: "Cost Inflation", level: 45, color: "var(--cyan)" },
      { name: "Competition", level: 42, color: "var(--cyan)" },
      { name: "Capex", level: 55, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Alam Flora benefits from stable concession revenue. Sustainability and recycling expansion support growth; concession renewal and cost management key.",
    },
  },

  SILVERVALLEY: {
    name: "Silver Valley",
    ticker: "SILVERVALLEY",
    entityType: "private",
    sector: "Consumer",
    industry: "Diversified",
    hq: "Kuala Lumpur, Malaysia",
    employees: "250",
    founded: 2010,
    ceo: "Ahmad Rahman",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 0.15B",
    kpis: [
      { label: "Revenue Growth", value: "12%", sub: "YoY" },
      { label: "Staff Count", value: "250", sub: "employees" },
      { label: "Market Presence", value: "Regional", sub: "Malaysia focus" },
      { label: "Product Lines", value: "5", sub: "business units" },
      { label: "Client Retention", value: "85%", sub: "annual" },
      { label: "Digital Adoption", value: "60%", sub: "operations" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0.1, 0.11, 0.12, 0.13, 0.15, 0.17],
      netIncome: [0.008, 0.009, 0.01, 0.011, 0.012, 0.014],
      grossMargin: [25, 26, 27, 28, 28, 29],
      operatingMargin: [10, 10.5, 11, 11.5, 12, 12.5],
      netMargin: [8, 8.2, 8.3, 8.5, 8.0, 8.2],
    },
    segments: {
      labels: ["Unit A", "Unit B", "Unit C", "Unit D", "Unit E"],
      values: [35, 25, 20, 12, 8],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Silver Valley", "Competitor A", "Competitor B", "Competitor C", "Competitor D"],
      revenue: [0.15, 0.25, 0.2, 0.18, 0.12],
      margin: [8.0, 6.5, 7.2, 5.8, 9.2],
    },
    swot: {
      strengths: ["Agile operations", "Niche focus", "Regional presence", "Customer relationships"],
      weaknesses: ["Limited scale", "Resource constraints", "Brand awareness", "Dependence on key clients"],
      opportunities: ["Market expansion", "Digital transformation", "Partnerships", "Acquisition"],
      threats: ["Larger competitors", "Economic slowdown", "Talent retention", "Regulatory changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Moderate growth in niche segments; diversification supporting revenue." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on specialization and customer retention; digital adoption." },
      { tag: "risk", tagLabel: "Risk", text: "Scale limitations; competition from larger players." },
      { tag: "market", tagLabel: "Market", text: "Smaller private company in competitive market; niche positioning." },
    ],
    risks: [
      { name: "Competition", level: 55, color: "var(--cyan)" },
      { name: "Scale", level: 52, color: "var(--cyan)" },
      { name: "Client Concentration", level: 48, color: "var(--cyan)" },
      { name: "Economic", level: 45, color: "var(--cyan)" },
      { name: "Talent", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--amber)",
      text: "Silver Valley operates in niche market with moderate growth. Scale and competition key challenges; digital and partnership expansion support outlook.",
    },
  },

  KDN: {
    name: "Kementerian Dalam Negeri (Ministry of Home Affairs)",
    ticker: "KDN",
    entityType: "government",
    sector: "Government",
    industry: "Home Affairs",
    hq: "Putrajaya, Malaysia",
    employees: "45,000",
    founded: 1955,
    ceo: "Datuk Seri Saifuddin Nasution Ismail",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 12.8B",
    kpis: [
      { label: "Annual Budget", value: "MYR 12.8B", sub: "FY2024" },
      { label: "Staff Count", value: "45,000", sub: "civil servants" },
      { label: "Programs Delivered", value: "Immigration, NRD", sub: "key services" },
      { label: "Digital Adoption Rate", value: "72%", sub: "e-services" },
      { label: "Service Coverage", value: "National", sub: "all states" },
      { label: "Key Initiative", value: "MyDigital ID", sub: "digital identity" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [11.2, 11.5, 12.0, 12.5, 12.8, 13.2],
      netIncome: [0.9, 0.95, 1.0, 1.05, 1.1, 1.15],
      grossMargin: [92, 93, 92, 93, 94, 94],
      operatingMargin: [88, 89, 88, 89, 90, 90],
      netMargin: [8, 8.3, 8.3, 8.4, 8.6, 8.7],
    },
    segments: {
      labels: ["Immigration", "PDRM Support", "RELA", "NRD", "Others"],
      values: [45, 25, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["KDN", "Singapore MHA", "Indonesia MOHA", "Thailand MFA", "Philippines DILG"],
      revenue: [12.8, 8.5, 15.2, 6.5, 4.2],
      margin: [8.6, 12, 6.5, 8.2, 5.5],
    },
    swot: {
      strengths: ["Critical national security role", "Large operational footprint", "Digital initiatives", "RELA volunteer force"],
      weaknesses: ["Complex bureaucracy", "Legacy systems", "Capacity constraints", "Coordination challenges"],
      opportunities: ["MyDigital ID rollout", "Immigration modernization", "Inter-agency integration", "Service digitization"],
      threats: ["Security threats", "Resource constraints", "Public expectations", "Cross-border challenges"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Budget growth reflects security and immigration priorities; digital transformation underway." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on MyDigital ID and immigration digitization; inter-agency coordination." },
      { tag: "risk", tagLabel: "Risk", text: "Legacy systems and capacity; security and border management challenges." },
      { tag: "market", tagLabel: "Market", text: "Key ministry for national security and citizen services; digital transformation critical." },
    ],
    risks: [
      { name: "Security", level: 52, color: "var(--cyan)" },
      { name: "Capacity", level: 48, color: "var(--cyan)" },
      { name: "Digital", level: 45, color: "var(--cyan)" },
      { name: "Coordination", level: 42, color: "var(--cyan)" },
      { name: "Resources", level: 55, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "On Track",
      ratingColor: "var(--green)",
      text: "KDN progressing on digital initiatives; MyDigital ID and immigration modernization key priorities. Budget utilization and service delivery improving.",
    },
  },

  MINDEF: {
    name: "Ministry of Defence (MINDEF)",
    ticker: "MINDEF",
    entityType: "government",
    sector: "Government",
    industry: "Defence",
    hq: "Kuala Lumpur, Malaysia",
    employees: "120,000",
    founded: 1957,
    ceo: "Datuk Seri Mohamed Khaled Nordin",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 18.2B",
    kpis: [
      { label: "Annual Budget", value: "MYR 18.2B", sub: "FY2024" },
      { label: "Staff Count", value: "120,000", sub: "Armed Forces + civilian" },
      { label: "Programs Delivered", value: "Fleet modernization", sub: "LCS, MRCA" },
      { label: "Digital Adoption Rate", value: "55%", sub: "defence systems" },
      { label: "Service Coverage", value: "National", sub: "all states" },
      { label: "Key Initiative", value: "Defence White Paper", sub: "strategic roadmap" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [15.5, 16.0, 16.8, 17.5, 18.2, 19.0],
      netIncome: [1.2, 1.25, 1.3, 1.35, 1.4, 1.45],
      grossMargin: [90, 91, 91, 92, 92, 93],
      operatingMargin: [85, 86, 86, 87, 87, 88],
      netMargin: [7.7, 7.8, 7.7, 7.7, 7.7, 7.6],
    },
    segments: {
      labels: ["Army", "Navy", "Air Force", "Defence Industry", "Others"],
      values: [45, 25, 20, 5, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MINDEF", "Singapore MINDEF", "Indonesia MINDEF", "Thailand MOD", "Philippines DND"],
      revenue: [18.2, 15.5, 12.8, 8.5, 5.2],
      margin: [7.7, 10, 6.2, 7.5, 4.8],
    },
    swot: {
      strengths: ["Large budget allocation", "Armed Forces capability", "Strategic partnerships", "Defence industry development"],
      weaknesses: ["LCS procurement issues", "Procurement delays", "Legacy equipment", "Talent retention"],
      opportunities: ["Fleet modernization", "Defence industry", "Regional cooperation", "Cyber defence"],
      threats: ["Geopolitical tensions", "Budget constraints", "Procurement complexity", "Technology gaps"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Budget growth reflects defence priorities; LCS and MRCA programs under review." },
      { tag: "strategy", tagLabel: "Strategy", text: "Defence White Paper guides modernization; focus on capability and industry." },
      { tag: "risk", tagLabel: "Risk", text: "Procurement challenges; LCS and legacy projects need resolution." },
      { tag: "market", tagLabel: "Market", text: "Malaysia defence budget significant; modernization and procurement key focus." },
    ],
    risks: [
      { name: "Procurement", level: 58, color: "var(--amber)" },
      { name: "Budget", level: 52, color: "var(--cyan)" },
      { name: "Capability", level: 48, color: "var(--cyan)" },
      { name: "Geopolitical", level: 55, color: "var(--cyan)" },
      { name: "Talent", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Needs Reform",
      ratingColor: "var(--amber)",
      text: "MINDEF faces procurement and LCS challenges. Defence White Paper provides direction; execution and capability delivery critical for reform.",
    },
  },

  MOD: {
    name: "Ministry of Digital",
    ticker: "MOD",
    entityType: "government",
    sector: "Government",
    industry: "Digital Transformation",
    hq: "Putrajaya, Malaysia",
    employees: "2,500",
    founded: 2022,
    ceo: "Gobind Singh Deo",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.8B",
    kpis: [
      { label: "Annual Budget", value: "MYR 1.8B", sub: "FY2024" },
      { label: "Staff Count", value: "2,500", sub: "civil servants" },
      { label: "Programs Delivered", value: "MyDigital", sub: "national initiative" },
      { label: "Digital Adoption Rate", value: "85%", sub: "target" },
      { label: "Service Coverage", value: "National", sub: "digital services" },
      { label: "Key Initiative", value: "5G rollout", sub: "Digital Nasional" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0, 0, 0.8, 1.2, 1.8, 2.2],
      netIncome: [0, 0, 0.08, 0.12, 0.15, 0.18],
      grossMargin: [0, 0, 90, 91, 92, 92],
      operatingMargin: [0, 0, 85, 87, 88, 88],
      netMargin: [0, 0, 10, 10, 8.3, 8.2],
    },
    segments: {
      labels: ["5G/Infra", "Digital Services", "Cybersecurity", "Policy", "Others"],
      values: [45, 25, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MOD", "Singapore GovTech", "Indonesia MCI", "Thailand Digital", "Philippines DICT"],
      revenue: [1.8, 2.5, 1.2, 0.9, 0.6],
      margin: [8.3, 12, 6.5, 7.2, 5.5],
    },
    swot: {
      strengths: ["New ministry focus", "MyDigital mandate", "5G rollout", "Strategic priority"],
      weaknesses: ["New organization", "Coordination challenges", "Resource constraints", "Legacy systems"],
      opportunities: ["5G expansion", "Digital economy", "GovTech adoption", "ASEAN digital leadership"],
      threats: ["Implementation complexity", "Stakeholder alignment", "Talent gap", "Cyber threats"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "New ministry driving MyDigital; 5G and digital services rollout progressing." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on 5G, digital infrastructure, and government digitization." },
      { tag: "risk", tagLabel: "Risk", text: "Coordination across ministries; implementation pace and talent." },
      { tag: "market", tagLabel: "Market", text: "Malaysia digital transformation critical; MOD central to national agenda." },
    ],
    risks: [
      { name: "Implementation", level: 55, color: "var(--cyan)" },
      { name: "Coordination", level: 52, color: "var(--cyan)" },
      { name: "Talent", level: 48, color: "var(--cyan)" },
      { name: "Cyber", level: 58, color: "var(--amber)" },
      { name: "5G", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Progressing",
      ratingColor: "var(--cyan)",
      text: "MOD as new ministry driving digital agenda. 5G and MyDigital initiatives progressing; coordination and execution key to success.",
    },
  },

  MAMPU: {
    name: "Malaysian Administrative Modernisation and Management Planning Unit (MAMPU)",
    ticker: "MAMPU",
    entityType: "government",
    sector: "Government",
    industry: "Digital Government Services",
    hq: "Putrajaya, Malaysia",
    employees: "800",
    founded: 1977,
    ceo: "Datuk Dr. Yusof Ismail",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 0.8B",
    kpis: [
      { label: "Annual Budget", value: "MYR 0.8B", sub: "FY2024" },
      { label: "Staff Count", value: "800", sub: "civil servants" },
      { label: "Programs Delivered", value: "MyGov", sub: "e-government" },
      { label: "Digital Adoption Rate", value: "78%", sub: "government services" },
      { label: "Service Coverage", value: "Federal", sub: "agencies" },
      { label: "Key Initiative", value: "GovCloud", sub: "shared infrastructure" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0.55, 0.6, 0.65, 0.72, 0.8, 0.88],
      netIncome: [0.05, 0.055, 0.06, 0.065, 0.07, 0.075],
      grossMargin: [92, 93, 93, 94, 94, 94],
      operatingMargin: [88, 89, 89, 90, 90, 90],
      netMargin: [9.1, 9.2, 9.2, 9.0, 8.8, 8.5],
    },
    segments: {
      labels: ["MyGov", "GovCloud", "Standards", "Training", "Others"],
      values: [40, 25, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MAMPU", "Singapore GovTech", "Indonesia BSSN", "Thailand DGA", "Philippines DICT"],
      revenue: [0.8, 2.5, 0.5, 0.4, 0.3],
      margin: [8.8, 12, 8.5, 7.2, 6.5],
    },
    swot: {
      strengths: ["Central government IT role", "MyGov platform", "GovCloud initiative", "Standards setting"],
      weaknesses: ["Limited enforcement", "Agency coordination", "Legacy systems", "Resource constraints"],
      opportunities: ["Cloud adoption", "AI in government", "Interoperability", "Service integration"],
      threats: ["Agency silos", "Cyber threats", "Talent retention", "Rapid tech change"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Budget growth reflects digital government priority; MyGov and GovCloud expanding." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on shared infrastructure and standards; agency digitization support." },
      { tag: "risk", tagLabel: "Risk", text: "Agency coordination; legacy system migration and adoption." },
      { tag: "market", tagLabel: "Market", text: "MAMPU central to digital government; coordination role critical." },
    ],
    risks: [
      { name: "Coordination", level: 55, color: "var(--cyan)" },
      { name: "Legacy", level: 52, color: "var(--cyan)" },
      { name: "Cyber", level: 48, color: "var(--cyan)" },
      { name: "Talent", level: 45, color: "var(--cyan)" },
      { name: "Adoption", level: 50, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "On Track",
      ratingColor: "var(--green)",
      text: "MAMPU progressing on digital government initiatives. GovCloud and MyGov expansion support agency digitization; coordination remains key challenge.",
    },
  },

  MITI: {
    name: "Ministry of Investment, Trade and Industry",
    ticker: "MITI",
    entityType: "government",
    sector: "Government",
    industry: "Trade & Investment",
    hq: "Putrajaya, Malaysia",
    employees: "3,500",
    founded: 1956,
    ceo: "Tengku Zafrul Aziz",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 2.2B",
    kpis: [
      { label: "Annual Budget", value: "MYR 2.2B", sub: "FY2024" },
      { label: "Staff Count", value: "3,500", sub: "civil servants" },
      { label: "Programs Delivered", value: "FDI attraction", sub: "NIMP 2030" },
      { label: "Digital Adoption Rate", value: "70%", sub: "e-services" },
      { label: "Service Coverage", value: "National", sub: "trade promotion" },
      { label: "Key Initiative", value: "NIMP 2030", sub: "industrial policy" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1.8, 1.9, 2.0, 2.1, 2.2, 2.4],
      netIncome: [0.15, 0.16, 0.17, 0.18, 0.19, 0.2],
      grossMargin: [91, 92, 92, 93, 93, 93],
      operatingMargin: [87, 88, 88, 89, 89, 89],
      netMargin: [8.3, 8.4, 8.5, 8.6, 8.6, 8.3],
    },
    segments: {
      labels: ["Trade", "Investment", "Industry", "MIDA", "Others"],
      values: [35, 30, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MITI", "Singapore MTI", "Indonesia MOI", "Thailand MOC", "Philippines DTI"],
      revenue: [2.2, 3.5, 2.8, 1.5, 1.2],
      margin: [8.6, 12, 7.5, 8.2, 6.5],
    },
    swot: {
      strengths: ["NIMP 2030 framework", "FDI attraction", "Trade agreements", "MIDA support"],
      weaknesses: ["Coordination complexity", "Policy implementation", "Bureaucracy", "Global competition"],
      opportunities: ["EV ecosystem", "Semiconductor", "Digital trade", "ASEAN integration"],
      threats: ["Geopolitical tensions", "Supply chain shifts", "Competition", "Policy uncertainty"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "NIMP 2030 driving industrial policy; FDI and trade promotion key focus." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on high-value sectors, EV, semiconductor; trade diversification." },
      { tag: "risk", tagLabel: "Risk", text: "Global competition; supply chain and geopolitical shifts." },
      { tag: "market", tagLabel: "Market", text: "Malaysia trade and investment critical; MITI central to economic growth." },
    ],
    risks: [
      { name: "Competition", level: 55, color: "var(--cyan)" },
      { name: "Geopolitical", level: 52, color: "var(--cyan)" },
      { name: "Implementation", level: 48, color: "var(--cyan)" },
      { name: "Supply Chain", level: 45, color: "var(--cyan)" },
      { name: "Policy", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "On Track",
      ratingColor: "var(--green)",
      text: "MITI driving NIMP 2030 and FDI attraction. EV and semiconductor focus align with global trends; execution key to success.",
    },
  },

  MOTAC: {
    name: "Ministry of Tourism, Arts and Culture / Aviation Partners",
    ticker: "MOTAC",
    entityType: "government",
    sector: "Government",
    industry: "Tourism & Culture",
    hq: "Putrajaya, Malaysia",
    employees: "5,000",
    founded: 1959,
    ceo: "Datuk Seri Tiong King Sing",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.5B",
    kpis: [
      { label: "Annual Budget", value: "MYR 1.5B", sub: "FY2024" },
      { label: "Staff Count", value: "5,000", sub: "civil servants" },
      { label: "Programs Delivered", value: "Visit Malaysia", sub: "tourism promotion" },
      { label: "Digital Adoption Rate", value: "65%", sub: "e-tourism" },
      { label: "Service Coverage", value: "National", sub: "tourism" },
      { label: "Key Initiative", value: "Visit Malaysia 2026", sub: "Tourism campaign" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1.2, 1.0, 1.1, 1.3, 1.5, 1.7],
      netIncome: [0.1, 0.08, 0.09, 0.11, 0.12, 0.14],
      grossMargin: [90, 91, 91, 92, 92, 92],
      operatingMargin: [86, 87, 87, 88, 88, 88],
      netMargin: [8.3, 8.0, 8.2, 8.5, 8.0, 8.2],
    },
    segments: {
      labels: ["Tourism", "Arts", "Culture", "Aviation Partners", "Others"],
      values: [45, 20, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MOTAC", "Singapore STB", "Indonesia Tourism", "Thailand TAT", "Philippines DOT"],
      revenue: [1.5, 2.2, 1.8, 1.5, 1.0],
      margin: [8.0, 15, 7.5, 8.2, 6.5],
    },
    swot: {
      strengths: ["Visit Malaysia brand", "Diverse attractions", "Culture heritage", "Aviation connectivity"],
      weaknesses: ["Post-COVID recovery", "Infrastructure gaps", "Service quality", "Marketing coordination"],
      opportunities: ["Visit Malaysia 2026", "Eco-tourism", "Digital tourism", "MICE growth"],
      threats: ["Regional competition", "Economic slowdown", "Safety perception", "Climate impact"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Tourism recovering post-COVID; Visit Malaysia 2026 campaign driving promotion." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on Visit Malaysia, digital tourism, and aviation partnerships." },
      { tag: "risk", tagLabel: "Risk", text: "Regional competition; Singapore and Thailand strong competitors." },
      { tag: "market", tagLabel: "Market", text: "Malaysia tourism key sector; MOTAC central to recovery and growth." },
    ],
    risks: [
      { name: "Competition", level: 55, color: "var(--cyan)" },
      { name: "Economic", level: 52, color: "var(--cyan)" },
      { name: "Recovery", level: 48, color: "var(--cyan)" },
      { name: "Infrastructure", level: 45, color: "var(--cyan)" },
      { name: "Safety", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Progressing",
      ratingColor: "var(--cyan)",
      text: "MOTAC driving tourism recovery; Visit Malaysia 2026 key initiative. Aviation and digital partnerships support growth; execution critical.",
    },
  },

  MOHE: {
    name: "Ministry of Higher Education (MOHE)",
    ticker: "MOHE",
    entityType: "government",
    sector: "Government",
    industry: "Higher Education",
    hq: "Putrajaya, Malaysia",
    employees: "8,000",
    founded: 2004,
    ceo: "Datuk Seri Zambry Abdul Kadir",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 15.5B",
    kpis: [
      { label: "Annual Budget", value: "MYR 15.5B", sub: "FY2024" },
      { label: "Staff Count", value: "8,000", sub: "ministry staff" },
      { label: "Programs Delivered", value: "20 public universities", sub: "higher education" },
      { label: "Digital Adoption Rate", value: "68%", sub: "e-learning" },
      { label: "Service Coverage", value: "National", sub: "universities" },
      { label: "Key Initiative", value: "TVET expansion", sub: "Skills development" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [12.5, 13.0, 13.8, 14.5, 15.5, 16.5],
      netIncome: [1.0, 1.05, 1.1, 1.15, 1.2, 1.25],
      grossMargin: [91, 92, 92, 93, 93, 93],
      operatingMargin: [87, 88, 88, 89, 89, 89],
      netMargin: [8.0, 8.1, 8.0, 7.9, 7.7, 7.6],
    },
    segments: {
      labels: ["Public Universities", "Polytechnics", "Community Colleges", "TVET", "Others"],
      values: [50, 20, 15, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MOHE", "Singapore MOE", "Indonesia MEC", "Thailand MHEC", "Philippines CHED"],
      revenue: [15.5, 18.5, 12.2, 8.5, 6.2],
      margin: [7.7, 12, 6.5, 7.2, 5.5],
    },
    swot: {
      strengths: ["Large university system", "TVET expansion", "Research focus", "International partnerships"],
      weaknesses: ["Employability gap", "Quality variance", "Funding constraints", "Brain drain"],
      opportunities: ["TVET expansion", "Digital learning", "Industry partnerships", "Research commercialization"],
      threats: ["Competition from private", "Global rankings", "Funding pressure", "Demographic shift"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Budget growth reflects education priority; TVET and digital learning expanding." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on employability, TVET, and industry alignment; research commercialization." },
      { tag: "risk", tagLabel: "Risk", text: "Employability and quality; competition from private and foreign universities." },
      { tag: "market", tagLabel: "Market", text: "Malaysia higher education key to talent; MOHE central to workforce development." },
    ],
    risks: [
      { name: "Employability", level: 55, color: "var(--cyan)" },
      { name: "Quality", level: 52, color: "var(--cyan)" },
      { name: "Funding", level: 48, color: "var(--cyan)" },
      { name: "Competition", level: 45, color: "var(--cyan)" },
      { name: "Brain Drain", level: 58, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Progressing",
      ratingColor: "var(--cyan)",
      text: "MOHE driving TVET and digital learning. Employability and industry alignment key; quality and funding remain challenges.",
    },
  },

  PDRM: {
    name: "Royal Malaysia Police (PDRM)",
    ticker: "PDRM",
    entityType: "government",
    sector: "Government",
    industry: "Law Enforcement",
    hq: "Kuala Lumpur, Malaysia",
    employees: "130,000",
    founded: 1807,
    ceo: "Tan Sri Razarudin Husain",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 12.0B",
    kpis: [
      { label: "Annual Budget", value: "MYR 12.0B", sub: "FY2024" },
      { label: "Staff Count", value: "130,000", sub: "personnel" },
      { label: "Programs Delivered", value: "Crime prevention", sub: "law enforcement" },
      { label: "Digital Adoption Rate", value: "60%", sub: "e-policing" },
      { label: "Service Coverage", value: "National", sub: "all states" },
      { label: "Key Initiative", value: "Community policing", sub: "SRS" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [10.5, 10.8, 11.2, 11.5, 12.0, 12.5],
      netIncome: [0.9, 0.95, 1.0, 1.05, 1.1, 1.15],
      grossMargin: [91, 92, 92, 93, 93, 93],
      operatingMargin: [87, 88, 88, 89, 89, 89],
      netMargin: [8.6, 8.8, 8.9, 9.1, 9.2, 9.2],
    },
    segments: {
      labels: ["Crime Investigation", "Traffic", "Narcotics", "Commercial", "Others"],
      values: [40, 25, 15, 12, 8],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["PDRM", "Singapore Police", "Indonesia Polri", "Thailand RTP", "Philippines PNP"],
      revenue: [12.0, 5.5, 8.2, 6.5, 4.2],
      margin: [9.2, 15, 7.5, 8.2, 5.5],
    },
    swot: {
      strengths: ["Large force", "National coverage", "Community policing", "Specialist units"],
      weaknesses: ["Resource constraints", "Legacy systems", "Public perception", "Training gaps"],
      opportunities: ["Digital policing", "Cyber crime", "Community engagement", "Modernization"],
      threats: ["Organized crime", "Cyber threats", "Resource pressure", "Public trust"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Budget growth reflects security priorities; digital and community policing expanding." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on crime prevention, digital policing, and community engagement." },
      { tag: "risk", tagLabel: "Risk", text: "Cyber crime and organized crime; resource and capacity constraints." },
      { tag: "market", tagLabel: "Market", text: "PDRM central to national security; modernization and trust key priorities." },
    ],
    risks: [
      { name: "Cyber Crime", level: 58, color: "var(--amber)" },
      { name: "Resources", level: 52, color: "var(--cyan)" },
      { name: "Public Trust", level: 48, color: "var(--cyan)" },
      { name: "Organized Crime", level: 55, color: "var(--cyan)" },
      { name: "Capacity", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "On Track",
      ratingColor: "var(--green)",
      text: "PDRM progressing on digital and community policing. Budget and modernization support capability; resource and trust remain key.",
    },
  },

  EPF: {
    name: "Employees Provident Fund of Malaysia",
    ticker: "EPF",
    entityType: "statutory",
    sector: "GLICs",
    industry: "Retirement Savings",
    hq: "Kuala Lumpur, Malaysia",
    employees: "4,500",
    founded: 1951,
    ceo: "Ahmad Zulqarnain Onn",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.1T",
    kpis: [
      { label: "AUM", value: "MYR 1.1T", sub: "total assets" },
      { label: "Members", value: "17M", sub: "active + inactive" },
      { label: "Dividend Rate", value: "5.50%", sub: "FY2024" },
      { label: "Investment Returns", value: "5.50%", sub: "FY2024" },
      { label: "Annual Contributions", value: "MYR 85B", sub: "gross" },
      { label: "Withdrawal Rate", value: "~15%", sub: "of contributions" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [0.93, 1.0, 1.05, 1.08, 1.1, 1.15],
      netIncome: [0.05, 0.055, 0.05, 0.055, 0.06, 0.062],
      grossMargin: [98, 98, 98, 98, 98, 98],
      operatingMargin: [95, 95, 95, 95, 95, 95],
      netMargin: [5.4, 5.5, 4.8, 5.1, 5.5, 5.4],
    },
    segments: {
      labels: ["Equities", "Fixed Income", "Real Estate", "Islamic", "Others"],
      values: [45, 35, 8, 7, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["EPF", "Singapore CPF", "Indonesia BPJS", "Thailand SSF", "Philippines SSS"],
      revenue: [1.1, 0.5, 0.4, 0.3, 0.25],
      margin: [5.5, 4.5, 3.5, 4.2, 3.8],
    },
    swot: {
      strengths: ["Largest asset manager", "Mandatory membership", "Strong governance", "Diversified portfolio"],
      weaknesses: ["Withdrawal pressure", "Equity concentration", "Demographic pressure", "Low returns vs inflation"],
      opportunities: ["ESG investing", "Digital services", "Shariah expansion", "International diversification"],
      threats: ["Special withdrawals", "Market volatility", "Economic downturn", "Regulatory changes"],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "AUM ~MYR 1.1T; dividend 5.50% for FY2024; contribution growth steady." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on sustainable returns, ESG, and digital member services." },
      { tag: "risk", tagLabel: "Risk", text: "Special withdrawal pressure; equity market volatility." },
      { tag: "market", tagLabel: "Market", text: "EPF key to Malaysia retirement; largest institutional investor." },
    ],
    risks: [
      { name: "Withdrawals", level: 55, color: "var(--cyan)" },
      { name: "Market Volatility", level: 52, color: "var(--cyan)" },
      { name: "Returns", level: 48, color: "var(--cyan)" },
      { name: "Demographics", level: 45, color: "var(--cyan)" },
      { name: "Regulation", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "On Track",
      ratingColor: "var(--green)",
      text: "EPF maintains strong AUM and governance. Dividend sustainability and withdrawal policy key; ESG and digital expansion support long-term outlook.",
    },
  },
});
