Object.assign(COMPANIES, {
  AIA: {
    name: "AIA Bhd",
    ticker: "AIA",
    entityType: "private",
    sector: "Insurance",
    industry: "Life Insurance",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,500",
    founded: 1948,
    ceo: "Ben Ng",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.2B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 8.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 1.1B", sub: "FY24" },
      { label: "Claims Ratio", value: "62.5%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 2.4B", sub: "FY24" },
      { label: "Policy Count", value: "2.1M", sub: "Active policies" },
      { label: "Combined Ratio", value: "94.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6200, 6500, 7200, 7800, 8200, 8700],
      netIncome: [780, 820, 920, 980, 1100, 1180],
      grossMargin: [68, 69, 70, 71, 72, 72],
      operatingMargin: [14, 14.5, 14.8, 15.2, 15.5, 15.8],
      netMargin: [12.6, 12.6, 12.8, 12.6, 13.4, 13.6],
    },
    segments: {
      labels: ["Life", "Health", "Retirement", "Investment-Linked", "Group"],
      values: [45, 22, 18, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["AIA", "Prudential", "Great Eastern", "Etiqa", "Allianz"],
      revenue: [8200, 7800, 6500, 5200, 3100],
      margin: [13.4, 12.8, 11.2, 9.5, 10.8],
    },
    swot: {
      strengths: [
        "Strong brand recognition from AIA Group's regional presence",
        "Leading market share in agency distribution channel",
        "Robust bancassurance partnerships",
        "Diversified product portfolio across life and health",
      ],
      weaknesses: [
        "Heavy reliance on traditional agency model",
        "Limited digital distribution compared to peers",
        "Higher expense ratio than some competitors",
      ],
      opportunities: [
        "Growing middle class and insurance penetration in Malaysia",
        "Digital transformation and InsurTech partnerships",
        "Expansion of health and critical illness products",
      ],
      threats: [
        "Intense competition from local and regional insurers",
        "Regulatory changes on capital requirements",
        "Economic volatility affecting investment returns",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "AIA Malaysia continues to grow premiums at mid-single digits, driven by agency force expansion and bancassurance growth. New business value improved 8% YoY in FY24." },
      { tag: "strategy", tagLabel: "Strategy", text: "Focus on agency-led distribution with digital enablement. Strengthening health and protection offerings to capture underserved segments." },
      { tag: "risk", tagLabel: "Risk", text: "Investment portfolio exposed to fixed income and equity market volatility. Claims experience stable but monitoring morbidity trends." },
      { tag: "market", tagLabel: "Market", text: "Top 3 life insurer in Malaysia by gross premiums. Market share ~18%. Benefiting from rising insurance awareness post-pandemic." },
    ],
    risks: [
      { name: "Investment Risk", level: 38, color: "var(--green)" },
      { name: "Claims Volatility", level: 42, color: "var(--cyan)" },
      { name: "Competition", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 45, color: "var(--cyan)" },
      { name: "Operational", level: 35, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "AIA Malaysia remains a core player in the life insurance market with solid fundamentals. Agency productivity and bancassurance partnerships support steady growth. Monitor digital adoption and expense management for margin improvement.",
    },
  },

  ALLIANZ_MY: {
    name: "Allianz Life Insurance Malaysia Bhd",
    ticker: "ALLIANZ_MY",
    entityType: "private",
    sector: "Insurance",
    industry: "Life & General Insurance",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,200",
    founded: 1980,
    ceo: "Sean Wang",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 3.1B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 3.1B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 335M", sub: "FY24" },
      { label: "Claims Ratio", value: "58.2%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 890M", sub: "FY24" },
      { label: "Policy Count", value: "850K", sub: "Active policies" },
      { label: "Combined Ratio", value: "92.8%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2400, 2550, 2750, 2900, 3100, 3300],
      netIncome: [245, 268, 285, 310, 335, 360],
      grossMargin: [65, 66, 67, 68, 68, 69],
      operatingMargin: [11.2, 11.5, 11.8, 12.0, 12.2, 12.5],
      netMargin: [10.2, 10.5, 10.4, 10.7, 10.8, 10.9],
    },
    segments: {
      labels: ["Life", "General", "Health", "Investment-Linked", "Takaful"],
      values: [40, 28, 18, 8, 6],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Allianz MY", "AIA", "Prudential", "Etiqa", "Great Eastern"],
      revenue: [3100, 8200, 7800, 5200, 6500],
      margin: [10.8, 13.4, 12.8, 9.5, 11.2],
    },
    swot: {
      strengths: [
        "Strong global Allianz brand and reinsurance support",
        "Dual life and general insurance capability",
        "Growing takaful presence",
        "Efficient claims handling reputation",
      ],
      weaknesses: [
        "Smaller scale vs top-tier life insurers",
        "Limited agency network compared to AIA/Prudential",
        "Lower brand awareness in retail segment",
      ],
      opportunities: [
        "Cross-sell between life and general portfolios",
        "Takaful market growth in Malaysia",
        "Corporate and SME insurance expansion",
      ],
      threats: [
        "Price competition in general insurance",
        "Regulatory alignment with IFRS 17",
        "Talent retention in competitive market",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Allianz Malaysia delivered 7% premium growth in FY24, with general insurance outperforming. Takaful segment growing double digits." },
      { tag: "strategy", tagLabel: "Strategy", text: "Leveraging Allianz global expertise in digital and ESG. Building integrated life-general proposition for corporate clients." },
      { tag: "risk", tagLabel: "Risk", text: "General insurance exposed to natural catastrophe and motor claims. Reinsurance program provides adequate protection." },
      { tag: "market", tagLabel: "Market", text: "Mid-tier player with ~7% combined market share. Strong in commercial lines and emerging in retail protection." },
    ],
    risks: [
      { name: "Catastrophe Risk", level: 48, color: "var(--cyan)" },
      { name: "Investment Risk", level: 40, color: "var(--green)" },
      { name: "Competition", level: 62, color: "var(--amber)" },
      { name: "Regulatory", level: 44, color: "var(--cyan)" },
      { name: "Scale", level: 55, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Allianz Malaysia benefits from parent support and diversified life-general mix. Steady execution but faces scale disadvantages. Takaful and digital initiatives could differentiate.",
    },
  },

  ETIQA: {
    name: "Etiqa",
    ticker: "ETIQA",
    entityType: "private",
    sector: "Insurance",
    industry: "Life & General Insurance / Takaful",
    hq: "Kuala Lumpur, Malaysia",
    employees: "3,800",
    founded: 2007,
    ceo: "Kamaludin Ahmad",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 5.2B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 5.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 495M", sub: "FY24" },
      { label: "Claims Ratio", value: "64.8%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 1.2B", sub: "FY24" },
      { label: "Policy Count", value: "3.2M", sub: "Active policies" },
      { label: "Combined Ratio", value: "95.1%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4200, 4450, 4750, 5000, 5200, 5500],
      netIncome: [380, 410, 445, 465, 495, 530],
      grossMargin: [64, 65, 65, 66, 66, 67],
      operatingMargin: [9.8, 9.9, 10.0, 10.2, 10.4, 10.6],
      netMargin: [9.0, 9.2, 9.4, 9.3, 9.5, 9.6],
    },
    segments: {
      labels: ["Family Takaful", "General Takaful", "Life", "General", "Investment-Linked"],
      values: [35, 25, 22, 12, 6],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Etiqa", "AIA", "Prudential", "Great Eastern", "Allianz"],
      revenue: [5200, 8200, 7800, 6500, 3100],
      margin: [9.5, 13.4, 12.8, 11.2, 10.8],
    },
    swot: {
      strengths: [
        "Maybank distribution network - largest bank in Malaysia",
        "Leading takaful operator with strong Islamic finance fit",
        "Integrated life and general under one brand",
        "Extensive branch and digital touchpoints",
      ],
      weaknesses: [
        "Lower margins than pure life players",
        "Complex dual conventional-takaful structure",
        "Heavy reliance on bancassurance",
      ],
      opportunities: [
        "Takaful market growth outpacing conventional",
        "Maybank customer base cross-sell potential",
        "Digital-first propositions for younger segment",
      ],
      threats: [
        "Bank distribution dependency",
        "Shariah compliance complexity",
        "Competition from dedicated takaful players",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Etiqa grew premiums 4% in FY24, with takaful contributing over 60%. Maybank channel remains core driver." },
      { tag: "strategy", tagLabel: "Strategy", text: "Bank-insurance model with Maybank. Expanding digital and mobile for policy servicing. Takaful-first for Islamic banking customers." },
      { tag: "risk", tagLabel: "Risk", text: "Concentration in bancassurance. Investment returns linked to Maybank group treasury. Claims experience stable." },
      { tag: "market", tagLabel: "Market", text: "Top takaful operator in Malaysia. Combined market share ~12%. Strong in family takaful and motor." },
    ],
    risks: [
      { name: "Distribution Concentration", level: 52, color: "var(--cyan)" },
      { name: "Investment Risk", level: 42, color: "var(--cyan)" },
      { name: "Margin Pressure", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 46, color: "var(--cyan)" },
      { name: "Operational", level: 38, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Etiqa's Maybank distribution is a key advantage. Takaful growth supports differentiation. Margin improvement depends on product mix and expense control.",
    },
  },

  GREATEASTERN: {
    name: "Great Eastern Life Assurance (Malaysia) Berhad",
    ticker: "GREATEASTERN",
    entityType: "private",
    sector: "Insurance",
    industry: "Life Insurance",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,100",
    founded: 1908,
    ceo: "Koh Yaw Hui",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 6.5B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 6.5B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 728M", sub: "FY24" },
      { label: "Claims Ratio", value: "61.2%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 1.9B", sub: "FY24" },
      { label: "Policy Count", value: "1.8M", sub: "Active policies" },
      { label: "Combined Ratio", value: "93.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [5200, 5600, 6000, 6200, 6500, 6900],
      netIncome: [580, 620, 665, 695, 728, 770],
      grossMargin: [66, 67, 68, 69, 69, 70],
      operatingMargin: [12.0, 12.2, 12.4, 12.6, 12.8, 13.0],
      netMargin: [11.2, 11.1, 11.1, 11.2, 11.2, 11.2],
    },
    segments: {
      labels: ["Life", "Health", "Retirement", "Investment-Linked", "Group"],
      values: [42, 24, 20, 9, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Great Eastern", "AIA", "Prudential", "Etiqa", "Allianz"],
      revenue: [6500, 8200, 7800, 5200, 3100],
      margin: [11.2, 13.4, 12.8, 9.5, 10.8],
    },
    swot: {
      strengths: [
        "OCBC Group backing and bancassurance via OCBC Malaysia",
        "Over 115 years of presence in Malaysia",
        "Strong agency force and bancassurance balance",
        "Solid brand among Chinese Malaysian community",
      ],
      weaknesses: [
        "Slower digital adoption than some peers",
        "Agency productivity below top performers",
        "Limited takaful presence",
      ],
      opportunities: [
        "OCBC customer base expansion",
        "Wealth management and retirement solutions",
        "Regional synergies with Great Eastern Singapore",
      ],
      threats: [
        "Competition from digital-first insurers",
        "Agency recruitment challenges",
        "Margin compression from product competition",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Great Eastern Malaysia grew 5% in FY24. New business value improved on better product mix. OCBC channel contributing ~35% of new business." },
      { tag: "strategy", tagLabel: "Strategy", text: "Dual distribution via agency and OCBC. Focus on protection and savings. Strengthening health and retirement propositions." },
      { tag: "risk", tagLabel: "Risk", text: "Investment portfolio well-diversified. Long-term liability matching sound. Monitoring persistency in competitive environment." },
      { tag: "market", tagLabel: "Market", text: "Top 4 life insurer with ~14% market share. Strong heritage brand. Benefiting from OCBC's retail expansion." },
    ],
    risks: [
      { name: "Investment Risk", level: 40, color: "var(--green)" },
      { name: "Distribution", level: 50, color: "var(--cyan)" },
      { name: "Competition", level: 60, color: "var(--amber)" },
      { name: "Persistency", level: 48, color: "var(--cyan)" },
      { name: "Regulatory", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Great Eastern Malaysia has stable fundamentals and OCBC support. Heritage and dual distribution are strengths. Needs to accelerate digital and agency productivity for outperformance.",
    },
  },

  LIBERTY_MY: {
    name: "Liberty General Insurance Berhad",
    ticker: "LIBERTY_MY",
    entityType: "private",
    sector: "Insurance",
    industry: "General Insurance",
    hq: "Kuala Lumpur, Malaysia",
    employees: "680",
    founded: 1995,
    ceo: "Mark O'Dell",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.8B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 1.8B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 162M", sub: "FY24" },
      { label: "Claims Ratio", value: "55.2%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 95M", sub: "FY24" },
      { label: "Policy Count", value: "1.1M", sub: "Active policies" },
      { label: "Combined Ratio", value: "91.0%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1500, 1580, 1650, 1720, 1800, 1880],
      netIncome: [125, 138, 145, 152, 162, 170],
      grossMargin: [62, 63, 63, 64, 64, 65],
      operatingMargin: [8.8, 9.0, 9.2, 9.4, 9.6, 9.8],
      netMargin: [8.3, 8.7, 8.8, 8.8, 9.0, 9.0],
    },
    segments: {
      labels: ["Motor", "Fire", "Marine", "Misc", "Engineering"],
      values: [45, 22, 15, 12, 6],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Liberty MY", "Allianz", "Etiqa", "MSIG", "Berjaya Sompo"],
      revenue: [1800, 3100, 5200, 1200, 950],
      margin: [9.0, 10.8, 9.5, 8.5, 7.8],
    },
    swot: {
      strengths: [
        "Liberty Mutual global brand and reinsurance capacity",
        "Strong motor and fire underwriting discipline",
        "Efficient claims handling",
        "Broker and direct distribution mix",
      ],
      weaknesses: [
        "Smaller scale vs integrated insurers",
        "Limited life insurance offering",
        "Dependent on motor segment",
      ],
      opportunities: [
        "Commercial lines expansion",
        "Digital distribution for SME",
        "Partnership with banks for cross-sell",
      ],
      threats: [
        "Motor claims inflation and fraud",
        "Natural catastrophe exposure",
        "Price competition in commoditized lines",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Liberty Malaysia grew 5% in FY24. Motor remains largest segment. Fire and marine showing better margins." },
      { tag: "strategy", tagLabel: "Strategy", text: "General insurance specialist. Underwriting discipline over volume. Broker relationships and digital for SME." },
      { tag: "risk", tagLabel: "Risk", text: "Motor claims ratio under pressure from repair cost inflation. Adequate reinsurance for catastrophe. Investment income supportive." },
      { tag: "market", tagLabel: "Market", text: "Mid-tier general insurer with ~5% market share. Known for underwriting quality. Competing with larger integrated players." },
    ],
    risks: [
      { name: "Motor Claims", level: 55, color: "var(--amber)" },
      { name: "Catastrophe", level: 45, color: "var(--cyan)" },
      { name: "Competition", level: 65, color: "var(--amber)" },
      { name: "Investment", level: 38, color: "var(--green)" },
      { name: "Regulatory", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Liberty Malaysia maintains underwriting discipline in a competitive general insurance market. Motor segment pressure is a concern. Commercial lines and digital could support growth.",
    },
  },

  PRUDENTIAL_MY: {
    name: "Prudential Assurance Malaysia Berhad",
    ticker: "PRUDENTIAL_MY",
    entityType: "private",
    sector: "Insurance",
    industry: "Life Insurance",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,800",
    founded: 1924,
    ceo: "Raymond Goh",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 7.8B",
    kpis: [
      { label: "Gross Premiums", value: "MYR 7.8B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 998M", sub: "FY24" },
      { label: "Claims Ratio", value: "63.1%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 2.2B", sub: "FY24" },
      { label: "Policy Count", value: "2.0M", sub: "Active policies" },
      { label: "Combined Ratio", value: "94.0%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6800, 7100, 7400, 7600, 7800, 8200],
      netIncome: [820, 865, 910, 955, 998, 1050],
      grossMargin: [67, 68, 69, 69, 70, 70],
      operatingMargin: [13.0, 13.2, 13.4, 13.5, 13.6, 13.8],
      netMargin: [12.1, 12.2, 12.3, 12.6, 12.8, 12.8],
    },
    segments: {
      labels: ["Life", "Health", "Retirement", "Investment-Linked", "Group"],
      values: [44, 23, 19, 9, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Prudential MY", "AIA", "Great Eastern", "Etiqa", "Allianz"],
      revenue: [7800, 8200, 6500, 5200, 3100],
      margin: [12.8, 13.4, 11.2, 9.5, 10.8],
    },
    swot: {
      strengths: [
        "Prudential plc global brand and expertise",
        "Largest agency force in Malaysia",
        "Strong health and protection franchise",
        "Pulse digital health platform differentiation",
      ],
      weaknesses: [
        "Agency productivity variability",
        "Expense ratio above some peers",
        "Limited bancassurance vs AIA/Great Eastern",
      ],
      opportunities: [
        "Health and wellness ecosystem expansion",
        "Agency digital tools and productivity",
        "Wealth and retirement solutions",
      ],
      threats: [
        "Agency recruitment and retention",
        "Competition from bancassurance-led players",
        "Regulatory capital and distribution rules",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Prudential Malaysia grew 3% in FY24. New business value stable. Pulse and health initiatives gaining traction." },
      { tag: "strategy", tagLabel: "Strategy", text: "Agency-centric with Pulse digital health. Protection-first positioning. Building health ecosystem beyond insurance." },
      { tag: "risk", tagLabel: "Risk", text: "Agency channel concentration. Investment returns adequate. IFRS 17 transition managed. Persistency within target." },
      { tag: "market", tagLabel: "Market", text: "Top 2 life insurer with ~17% market share. Largest agency network. Health leadership with Pulse." },
    ],
    risks: [
      { name: "Agency Risk", level: 52, color: "var(--cyan)" },
      { name: "Investment Risk", level: 40, color: "var(--green)" },
      { name: "Competition", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 46, color: "var(--cyan)" },
      { name: "Expense", level: 54, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Prudential Malaysia has scale and agency strength. Pulse differentiates in health. Agency productivity and expense management key to margin improvement.",
    },
  },

  AMMETLIFE: {
    name: "AmMet Life",
    ticker: "AMMETLIFE",
    entityType: "private",
    sector: "Insurance",
    industry: "Life Insurance / Takaful",
    hq: "Kuala Lumpur, Malaysia",
    employees: "420",
    founded: 2010,
    ceo: "Raja Teh Maimunah",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 680M",
    kpis: [
      { label: "Gross Premiums", value: "MYR 680M", sub: "FY24" },
      { label: "Net Profit", value: "MYR 48M", sub: "FY24" },
      { label: "Claims Ratio", value: "66.5%", sub: "FY24" },
      { label: "Investment Income", value: "MYR 125M", sub: "FY24" },
      { label: "Policy Count", value: "285K", sub: "Active policies" },
      { label: "Combined Ratio", value: "96.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [520, 560, 600, 640, 680, 730],
      netIncome: [32, 36, 40, 44, 48, 52],
      grossMargin: [60, 61, 62, 62, 63, 63],
      operatingMargin: [6.5, 6.8, 7.0, 7.2, 7.4, 7.6],
      netMargin: [6.2, 6.4, 6.7, 6.9, 7.1, 7.1],
    },
    segments: {
      labels: ["Family Takaful", "Life", "Investment-Linked", "Group", "Health"],
      values: [45, 22, 18, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["AmMet Life", "Etiqa", "AIA", "Prudential", "Great Eastern"],
      revenue: [680, 5200, 8200, 7800, 6500],
      margin: [7.1, 9.5, 13.4, 12.8, 11.2],
    },
    swot: {
      strengths: [
        "Joint venture with MetLife and AmBank",
        "Bancassurance via AmBank distribution",
        "Takaful focus with Islamic banking fit",
        "Agile and focused product set",
      ],
      weaknesses: [
        "Small scale vs major players",
        "Limited product breadth",
        "Heavy reliance on AmBank channel",
      ],
      opportunities: [
        "AmBank customer base penetration",
        "Takaful growth in Malaysia",
        "Niche segments underserved by large players",
      ],
      threats: [
        "Scale disadvantages in procurement and reinsurance",
        "AmBank growth dependency",
        "Competition from Etiqa and other takaful players",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "AmMet Life grew 6% in FY24. Takaful contributing ~45%. AmBank channel remains primary. New business value improving." },
      { tag: "strategy", tagLabel: "Strategy", text: "Bancassurance-focused with AmBank. Takaful-first for Islamic banking customers. Streamlined product portfolio." },
      { tag: "risk", tagLabel: "Risk", text: "Single bank distribution concentration. Investment returns adequate. Claims experience within expectations." },
      { tag: "market", tagLabel: "Market", text: "Niche player with ~2% life market share. Strong in AmBank ecosystem. Takaful positioning for growth." },
    ],
    risks: [
      { name: "Distribution Concentration", level: 62, color: "var(--amber)" },
      { name: "Scale", level: 58, color: "var(--amber)" },
      { name: "Investment Risk", level: 42, color: "var(--cyan)" },
      { name: "Competition", level: 68, color: "var(--amber)" },
      { name: "Regulatory", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "AmMet Life is a niche bancassurance player with takaful focus. Growth tied to AmBank. Scale limits margin potential but JV structure provides stability.",
    },
  },

  PETRONAS: {
    name: "Petroliam Nasional Berhad (Petronas)",
    ticker: "PETRONAS",
    entityType: "government",
    sector: "Oil, Gas & Energy",
    industry: "Integrated Oil & Gas",
    hq: "Kuala Lumpur, Malaysia",
    employees: "48,000",
    founded: 1974,
    ceo: "Tengku Muhammad Taufik",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 350.2B",
    kpis: [
      { label: "Revenue", value: "MYR 350.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 52.8B", sub: "FY24" },
      { label: "Production", value: "2.2M boepd", sub: "Oil & gas" },
      { label: "Reserves", value: "21.2B boe", sub: "Proven" },
      { label: "Refining Capacity", value: "1.2M bpd", sub: "Domestic" },
      { label: "Dividend to Govt", value: "MYR 32B", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [240000, 248000, 320000, 343000, 350200, 355000],
      netIncome: [16500, 30600, 101000, 80700, 52800, 48000],
      grossMargin: [32, 38, 42, 38, 35, 33],
      operatingMargin: [18, 24, 35, 28, 22, 20],
      netMargin: [6.9, 12.3, 31.6, 23.5, 15.1, 13.5],
    },
    segments: {
      labels: ["Upstream", "Gas", "Downstream", "Petrochemicals", "Others"],
      values: [42, 28, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Petronas", "Shell MY", "Chevron MY", "ExxonMobil", "TotalEnergies"],
      revenue: [350200, 28000, 8500, 22000, 0],
      margin: [15.1, 8.5, 7.2, 9.0, 0],
    },
    swot: {
      strengths: [
        "Full value chain from upstream to retail",
        "Strategic national asset with government backing",
        "Global footprint in 50+ countries",
        "Strong LNG and gas position in Asia",
      ],
      weaknesses: [
        "Mature domestic basins, declining production",
        "Heavy dividend obligations to government",
        "Downstream margin volatility",
      ],
      opportunities: [
        "Energy transition - renewables and hydrogen",
        "Petrochemical expansion in Pengerang",
        "Digital and technology investments",
      ],
      threats: [
        "Oil price volatility",
        "Energy transition pressure",
        "Geopolitical risks in international operations",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Petronas revenue reached MYR 350B in FY24. Net profit moderated from peak as oil prices normalized. Upstream remains core; energy transition investments growing." },
      { tag: "strategy", tagLabel: "Strategy", text: "Net Zero 2050 commitment. Expanding gas and LNG. Downstream integration in Pengerang. Ventures into renewables and hydrogen." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price sensitivity. Dividend commitment to government. Carbon transition. Geopolitical exposure in international assets." },
      { tag: "market", tagLabel: "Market", text: "Malaysia's national oil company. Top 20 global NOC by revenue. Dominant domestic position. Key contributor to government revenue." },
    ],
    risks: [
      { name: "Oil Price", level: 68, color: "var(--amber)" },
      { name: "Energy Transition", level: 55, color: "var(--amber)" },
      { name: "Geopolitical", level: 52, color: "var(--cyan)" },
      { name: "Dividend Pressure", level: 48, color: "var(--cyan)" },
      { name: "Operational", level: 38, color: "var(--green)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Petronas remains a critical national asset with strong fundamentals. Energy transition path is key. Dividend obligations and oil price volatility are headwinds. Gas and downstream provide stability.",
    },
  },

  PETROS: {
    name: "Petroleum Sarawak Berhad (Petros)",
    ticker: "PETROS",
    entityType: "government",
    sector: "Oil, Gas & Energy",
    industry: "Upstream Oil & Gas",
    hq: "Kuching, Malaysia",
    employees: "850",
    founded: 2017,
    ceo: "Janin Girie",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 4.2B",
    kpis: [
      { label: "Revenue", value: "MYR 4.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 680M", sub: "FY24" },
      { label: "Production", value: "85K boepd", sub: "Equity" },
      { label: "Reserves", value: "0.8B boe", sub: "Proven" },
      { label: "Gas Sales", value: "450 mmscfd", sub: "FY24" },
      { label: "JV Partners", value: "12", sub: "Active" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2800, 3200, 3800, 4000, 4200, 4500],
      netIncome: [420, 520, 620, 650, 680, 720],
      grossMargin: [28, 30, 32, 31, 30, 30],
      operatingMargin: [18, 20, 22, 21, 20, 20],
      netMargin: [15.0, 16.3, 16.3, 16.3, 16.2, 16.0],
    },
    segments: {
      labels: ["Upstream", "Gas", "Commercial", "Services", "Others"],
      values: [55, 25, 10, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Petros", "Petronas", "Shell MY", "Dialog", "Vestigo"],
      revenue: [4200, 350200, 28000, 4200, 1800],
      margin: [16.2, 15.1, 8.5, 12.5, 8.0],
    },
    swot: {
      strengths: [
        "Sarawak state oil rights under MA63",
        "Strategic position in Sarawak gas basin",
        "Government of Sarawak backing",
        "Growing JV portfolio",
      ],
      weaknesses: [
        "Relatively new entity, limited track record",
        "Dependent on Petronas and JV partnerships",
        "Smaller scale vs national players",
      ],
      opportunities: [
        "Sarawak gas development",
        "Carbon capture and storage in Sarawak",
        "Downstream integration in Bintulu",
      ],
      threats: [
        "Relationship with Petronas",
        "Oil and gas price volatility",
        "Regulatory evolution of state rights",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Petros revenue grew 5% in FY24. Gas sales and upstream equity production stable. Expanding role in Sarawak energy sector." },
      { tag: "strategy", tagLabel: "Strategy", text: "Sarawak state O&G champion. Upstream participation and gas commercialization. CCS potential in depleted fields." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price exposure. Partnership dynamics with Petronas. State-federal regulatory interface." },
      { tag: "market", tagLabel: "Market", text: "Sarawak's state oil company. Key player in Sarawak O&G. Growing from 2017 establishment. Gas focus in Bintulu area." },
    ],
    risks: [
      { name: "Oil Price", level: 62, color: "var(--amber)" },
      { name: "Partnership", level: 52, color: "var(--cyan)" },
      { name: "Regulatory", level: 55, color: "var(--amber)" },
      { name: "Scale", level: 48, color: "var(--cyan)" },
      { name: "Operational", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Petros is establishing itself as Sarawak's O&G entity. Gas and upstream participation are core. Relationship with Petronas and state rights evolution are key to watch.",
    },
  },

  PETRONM: {
    name: "Petron Malaysia Refining & Marketing Bhd",
    ticker: "PETRONM",
    entityType: "public",
    sector: "Oil, Gas & Energy",
    industry: "Downstream Oil - Refining & Marketing",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,200",
    founded: 1963,
    ceo: "Ramon Ang",
    price: 4.85,
    change: 0.12,
    changePct: 2.5,
    marketCap: "MYR 12.8B",
    peRatio: 8.2,
    divYield: "4.2%",
    beta: 1.15,
    revenue52w: "MYR 28.5B",
    kpis: [
      { label: "Revenue", value: "MYR 28.5B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 1.56B", sub: "FY24" },
      { label: "Refining Throughput", value: "135K bpd", sub: "Port Dickson" },
      { label: "Retail Stations", value: "680", sub: "Malaysia" },
      { label: "Market Share", value: "22%", sub: "Retail fuel" },
      { label: "Gross Margin", value: "8.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [18500, 22500, 28500, 29500, 28500, 27500],
      netIncome: [-280, 420, 1850, 1680, 1560, 1420],
      grossMargin: [2.5, 4.2, 9.5, 8.8, 8.2, 7.5],
      operatingMargin: [-2.0, 2.5, 8.2, 7.2, 6.5, 5.8],
      netMargin: [-1.5, 1.9, 6.5, 5.7, 5.5, 5.2],
    },
    segments: {
      labels: ["Refining", "Retail", "Commercial", "LPG", "Lubricants"],
      values: [45, 35, 12, 5, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Petron", "Shell", "Petronas", "BHP", "Caltex"],
      revenue: [28500, 28000, 45000, 5200, 8500],
      margin: [5.5, 8.5, 6.0, 4.2, 7.2],
    },
    swot: {
      strengths: [
        "Only private refiner in Malaysia",
        "Strong Petron brand and retail network",
        "Port Dickson refinery flexibility",
        "San Miguel Corp backing",
      ],
      weaknesses: [
        "Refining margin volatility",
        "Competition from Petronas and Shell",
        "Crude sourcing dependency",
      ],
      opportunities: [
        "Retail network expansion",
        "Non-fuel retail and convenience",
        "Export markets for refined products",
      ],
      threats: [
        "Crack spread compression",
        "EV transition impact on fuel demand",
        "Regulated fuel pricing",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Petron Malaysia revenue moderated in FY24 as crude prices eased. Refining margins off peak but still healthy. Retail volume stable." },
      { tag: "strategy", tagLabel: "Strategy", text: "Integrated refiner-marketer. Retail expansion and convenience offerings. Operational efficiency at Port Dickson." },
      { tag: "risk", tagLabel: "Risk", text: "Refining crack spread is key driver. Fuel price controls in Malaysia. Crude price and FX volatility." },
      { tag: "market", tagLabel: "Market", text: "Second largest retail fuel marketer. ~22% market share. Only private refiner. Listed on Bursa." },
    ],
    risks: [
      { name: "Refining Margin", level: 72, color: "var(--red)" },
      { name: "Crude Price", level: 65, color: "var(--amber)" },
      { name: "Competition", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 48, color: "var(--cyan)" },
      { name: "EV Transition", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Petron Malaysia benefits from integrated model. Refining margins have normalized from 2022 peak. Retail network and brand support. Crack spread volatility remains key risk.",
    },
  },

  BOUSTEAD_PETROL: {
    name: "Boustead Petroleum Marketing Sdn Bhd",
    ticker: "BOUSTEAD_PETROL",
    entityType: "private",
    sector: "Oil, Gas & Energy",
    industry: "Downstream Oil - Marketing",
    hq: "Kuala Lumpur, Malaysia",
    employees: "1,100",
    founded: 1975,
    ceo: "Izaddeen Daud",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 5.2B",
    kpis: [
      { label: "Revenue", value: "MYR 5.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 218M", sub: "FY24" },
      { label: "Retail Stations", value: "420", sub: "BHPetrol" },
      { label: "Market Share", value: "8%", sub: "Retail fuel" },
      { label: "Volume Sold", value: "2.1B litres", sub: "FY24" },
      { label: "Gross Margin", value: "5.8%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4200, 4800, 5600, 5200, 5200, 5100],
      netIncome: [95, 165, 245, 225, 218, 205],
      grossMargin: [4.2, 5.0, 6.2, 5.5, 5.8, 5.5],
      operatingMargin: [2.8, 3.8, 5.2, 4.8, 4.6, 4.4],
      netMargin: [2.3, 3.4, 4.4, 4.3, 4.2, 4.0],
    },
    segments: {
      labels: ["Retail", "Commercial", "Aviation", "Marine", "Lubricants"],
      values: [55, 25, 10, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["BHPetrol", "Petron", "Shell", "Petronas", "Caltex"],
      revenue: [5200, 28500, 28000, 45000, 8500],
      margin: [4.2, 5.5, 8.5, 6.0, 7.2],
    },
    swot: {
      strengths: [
        "Boustead Holdings legacy and government links",
        "BHPetrol brand recognition",
        "Strategic station locations",
        "Loyal customer base",
      ],
      weaknesses: [
        "No refining - pure marketer",
        "Smaller network vs Shell and Petron",
        "Margin pressure from competition",
      ],
      opportunities: [
        "Convenience store expansion",
        "Fleet and commercial segment",
        "Rural and underserved areas",
      ],
      threats: [
        "Fuel price controls",
        "Competition from larger players",
        "EV transition long-term",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "BHPetrol revenue flat in FY24. Volume stable. Margin pressure from regulated pricing. Convenience and non-fuel initiatives." },
      { tag: "strategy", tagLabel: "Strategy", text: "Retail-focused marketer. Station network quality over quantity. Convenience and loyalty programs." },
      { tag: "risk", tagLabel: "Risk", text: "No refining - exposed to wholesale product costs. Regulated retail pricing. Boustead group restructuring." },
      { tag: "market", tagLabel: "Market", text: "Fourth largest retail fuel marketer. ~8% market share. BHPetrol brand. Part of Boustead group." },
    ],
    risks: [
      { name: "Margin Compression", level: 62, color: "var(--amber)" },
      { name: "Regulatory", level: 55, color: "var(--amber)" },
      { name: "Competition", level: 65, color: "var(--amber)" },
      { name: "Group Restructuring", level: 52, color: "var(--cyan)" },
      { name: "Volume", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "BHPetrol operates in a competitive, regulated market. Pure marketer model limits margin flexibility. Boustead group dynamics and station network optimization are factors.",
    },
  },

  CHEVRON_MY: {
    name: "Chevron Malaysia Limited (Caltex)",
    ticker: "CHEVRON_MY",
    entityType: "private",
    sector: "Oil, Gas & Energy",
    industry: "Downstream Oil - Marketing / Upstream",
    hq: "Kuala Lumpur, Malaysia",
    employees: "950",
    founded: 1936,
    ceo: "Haresh Manohar",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 8.5B",
    kpis: [
      { label: "Revenue", value: "MYR 8.5B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 612M", sub: "FY24" },
      { label: "Retail Stations", value: "280", sub: "Caltex" },
      { label: "Upstream Production", value: "45K boepd", sub: "Malaysia" },
      { label: "Market Share", value: "6%", sub: "Retail fuel" },
      { label: "Gross Margin", value: "9.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [6200, 7200, 9200, 8800, 8500, 8200],
      netIncome: [280, 420, 780, 680, 612, 580],
      grossMargin: [6.5, 7.2, 11.5, 9.8, 9.5, 9.0],
      operatingMargin: [5.2, 6.0, 9.5, 8.2, 7.8, 7.5],
      netMargin: [4.5, 5.8, 8.5, 7.7, 7.2, 7.1],
    },
    segments: {
      labels: ["Upstream", "Retail", "Commercial", "Lubricants", "LPG"],
      values: [35, 40, 15, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Chevron MY", "Shell MY", "Petronas", "Petron", "ExxonMobil"],
      revenue: [8500, 28000, 350200, 28500, 22000],
      margin: [7.2, 8.5, 15.1, 5.5, 9.0],
    },
    swot: {
      strengths: [
        "Chevron global brand and technology",
        "Integrated upstream and downstream in Malaysia",
        "Caltex retail brand",
        "Offshore production assets",
      ],
      weaknesses: [
        "Smaller retail network vs Shell and Petron",
        "Upstream assets maturing",
        "Limited refining presence",
      ],
      opportunities: [
        "Lubricants and specialty products",
        "Commercial and industrial segment",
        "Caltex Star Mart convenience",
      ],
      threats: [
        "Competition from national players",
        "Upstream decline curve",
        "Energy transition",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Chevron Malaysia revenue eased 3% in FY24. Upstream production stable. Retail margin pressure. Lubricants performing well." },
      { tag: "strategy", tagLabel: "Strategy", text: "Integrated Malaysia presence. Upstream cash flow supports downstream. Caltex retail and Star Mart convenience." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price sensitivity. Upstream asset maturity. Regulated retail pricing. Chevron global portfolio decisions." },
      { tag: "market", tagLabel: "Market", text: "Mid-tier player. Upstream and downstream. Caltex brand. ~6% retail share. Part of Chevron global." },
    ],
    risks: [
      { name: "Oil Price", level: 65, color: "var(--amber)" },
      { name: "Upstream Decline", level: 55, color: "var(--amber)" },
      { name: "Competition", level: 58, color: "var(--amber)" },
      { name: "Regulatory", level: 48, color: "var(--cyan)" },
      { name: "Operational", level: 42, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Chevron Malaysia has integrated upstream-downstream presence. Upstream provides stability. Retail faces competition. Part of Chevron's Asia portfolio.",
    },
  },

  SHELL_MY: {
    name: "Shell Malaysia Trading Sdn Bhd",
    ticker: "SHELL_MY",
    entityType: "private",
    sector: "Oil, Gas & Energy",
    industry: "Downstream Oil - Marketing / Upstream",
    hq: "Kuala Lumpur, Malaysia",
    employees: "6,500",
    founded: 1891,
    ceo: "Siti Hurrairah Sulaiman",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 28.0B",
    kpis: [
      { label: "Revenue", value: "MYR 28.0B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 2.38B", sub: "FY24" },
      { label: "Retail Stations", value: "950", sub: "Malaysia" },
      { label: "Upstream Production", value: "180K boepd", sub: "Malaysia" },
      { label: "Market Share", value: "28%", sub: "Retail fuel" },
      { label: "Gross Margin", value: "12.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [22000, 24500, 32000, 29500, 28000, 27000],
      netIncome: [1200, 1850, 3200, 2680, 2380, 2160],
      grossMargin: [8.5, 9.2, 13.5, 11.8, 12.5, 11.5],
      operatingMargin: [6.5, 8.0, 11.5, 10.2, 9.5, 8.8],
      netMargin: [5.5, 7.6, 10.0, 9.1, 8.5, 8.0],
    },
    segments: {
      labels: ["Retail", "Upstream", "Commercial", "Lubricants", "Trading"],
      values: [40, 30, 15, 8, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Shell MY", "Petronas", "Petron", "Chevron", "BHPetrol"],
      revenue: [28000, 350200, 28500, 8500, 5200],
      margin: [8.5, 15.1, 5.5, 7.2, 4.2],
    },
    swot: {
      strengths: [
        "Largest retail network in Malaysia",
        "Shell global brand and technology",
        "Integrated upstream and downstream",
        "Strong lubricants and convenience",
      ],
      weaknesses: [
        "No domestic refining",
        "Energy transition pressure on parent",
        "Regulated fuel pricing",
      ],
      opportunities: [
        "EV charging network",
        "Convenience and non-fuel retail",
        "Low-carbon fuels",
      ],
      threats: [
        "Shell global energy transition strategy",
        "Competition from Petronas and Petron",
        "EV impact on fuel demand",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Shell Malaysia revenue eased 5% in FY24. Upstream production stable. Retail volume resilient. Largest retail marketer." },
      { tag: "strategy", tagLabel: "Strategy", text: "Market leader in retail. Upstream cash flow. Select convenience and EV charging. Aligned with Shell's energy transition." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price and crack spread. Shell global portfolio decisions. Regulated pricing. Energy transition capital allocation." },
      { tag: "market", tagLabel: "Market", text: "Largest retail fuel marketer. ~28% share. 950 stations. Integrated upstream. Over 130 years in Malaysia." },
    ],
    risks: [
      { name: "Oil Price", level: 62, color: "var(--amber)" },
      { name: "Energy Transition", level: 55, color: "var(--amber)" },
      { name: "Competition", level: 55, color: "var(--amber)" },
      { name: "Regulatory", level: 50, color: "var(--cyan)" },
      { name: "Parent Strategy", level: 48, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Shell Malaysia is the retail market leader with integrated upstream. Strong brand and network. Energy transition and Shell global strategy are key factors.",
    },
  },

  DIALOG: {
    name: "DIALOG Group Berhad",
    ticker: "DIALOG",
    entityType: "public",
    sector: "Oil, Gas & Energy",
    industry: "Oil & Gas Services - Tank Terminals & EPCC",
    hq: "Kuala Lumpur, Malaysia",
    employees: "3,200",
    founded: 1984,
    ceo: "Ngau Boon Keat",
    price: 2.42,
    change: 0.08,
    changePct: 3.4,
    marketCap: "MYR 25.2B",
    peRatio: 22.5,
    divYield: "2.8%",
    beta: 0.95,
    revenue52w: "MYR 4.2B",
    kpis: [
      { label: "Revenue", value: "MYR 4.2B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 525M", sub: "FY24" },
      { label: "Storage Capacity", value: "2.8M cbm", sub: "Pengerang" },
      { label: "EPCC Order Book", value: "MYR 8.5B", sub: "FY24" },
      { label: "Recurring Income %", value: "65%", sub: "Tank terminals" },
      { label: "Gross Margin", value: "28.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [3200, 3500, 3800, 4000, 4200, 4500],
      netIncome: [380, 420, 465, 495, 525, 560],
      grossMargin: [26, 27, 28, 28, 28.5, 29],
      operatingMargin: [14, 15, 16, 16, 16.5, 17],
      netMargin: [11.9, 12.0, 12.2, 12.4, 12.5, 12.4],
    },
    segments: {
      labels: ["Tank Terminals", "EPCC", "Plant Maintenance", "Specialty Chemicals", "Others"],
      values: [45, 30, 15, 6, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Dialog", "Sapura Energy", "MMC", "Serba Dinamik", "Bumi Armada"],
      revenue: [4200, 2800, 5200, 1800, 2200],
      margin: [12.5, -5.0, 8.5, 6.2, 4.5],
    },
    swot: {
      strengths: [
        "Leading independent tank terminal operator in Asia",
        "Pengerang integrated complex with Petronas",
        "Recurring income from tank storage",
        "Strong EPCC track record",
      ],
      weaknesses: [
        "EPCC cyclicality",
        "Concentration in Pengerang",
        "Capital intensive growth",
      ],
      opportunities: [
        "Tank terminal expansion",
        "Energy transition - hydrogen, ammonia",
        "Regional expansion",
      ],
      threats: [
        "Oil demand long-term",
        "EPCC competition",
        "Petronas project timing",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Dialog revenue grew 5% in FY24. Tank terminal utilization strong. EPCC order book healthy. Recurring income supports valuation." },
      { tag: "strategy", tagLabel: "Strategy", text: "Tank terminals as annuity. EPCC for growth. Pengerang hub. Exploring energy transition storage." },
      { tag: "risk", tagLabel: "Risk", text: "EPCC lumpiness. Petronas project dependency. Tank utilization and rates. FX on international projects." },
      { tag: "market", tagLabel: "Market", text: "Premier O&G services company. Largest independent tank terminal operator. ~MYR 25B market cap. Defensive within sector." },
    ],
    risks: [
      { name: "EPCC Cyclicality", level: 52, color: "var(--cyan)" },
      { name: "Utilization", level: 42, color: "var(--cyan)" },
      { name: "Competition", level: 55, color: "var(--amber)" },
      { name: "Petronas Dependency", level: 48, color: "var(--cyan)" },
      { name: "Valuation", level: 58, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Buy",
      ratingColor: "var(--green)",
      text: "Dialog offers defensive growth within O&G. Tank terminal recurring income provides stability. EPCC order book supports. Premium valuation justified by quality and recurring mix.",
    },
  },

  VESTIGO: {
    name: "Vestigo Petroleum Sdn Bhd",
    ticker: "VESTIGO",
    entityType: "private",
    sector: "Oil, Gas & Energy",
    industry: "Upstream Oil & Gas",
    hq: "Kuala Lumpur, Malaysia",
    employees: "320",
    founded: 2014,
    ceo: "Ahmad Zaki bin Zahid",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 1.8B",
    kpis: [
      { label: "Revenue", value: "MYR 1.8B", sub: "FY24" },
      { label: "Net Profit", value: "MYR 144M", sub: "FY24" },
      { label: "Production", value: "28K boepd", sub: "Equity" },
      { label: "Reserves", value: "0.25B boe", sub: "Proven" },
      { label: "Blocks", value: "6", sub: "Malaysia" },
      { label: "Gross Margin", value: "18.5%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [1200, 1400, 1800, 1750, 1800, 1750],
      netIncome: [45, 95, 165, 155, 144, 135],
      grossMargin: [12, 15, 20, 18, 18.5, 17],
      operatingMargin: [5.5, 8.5, 12.5, 11.5, 10.5, 9.5],
      netMargin: [3.8, 6.8, 9.2, 8.9, 8.0, 7.7],
    },
    segments: {
      labels: ["Oil Production", "Gas Production", "Development", "Exploration", "Others"],
      values: [42, 35, 12, 8, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Vestigo", "Petronas", "Shell MY", "Petros", "Hibiscus"],
      revenue: [1800, 350200, 28000, 4200, 1200],
      margin: [8.0, 15.1, 8.5, 16.2, 12.5],
    },
    swot: {
      strengths: [
        "Petronas subsidiary - strategic alignment",
        "Focus on mature asset management",
        "Technical expertise in marginal fields",
        "Access to Petronas infrastructure",
      ],
      weaknesses: [
        "Small scale vs major players",
        "Mature asset decline curve",
        "Limited exploration upside",
      ],
      opportunities: [
        "Asset transfers from Petronas",
        "Enhanced oil recovery",
        "Decommissioning services",
      ],
      threats: [
        "Oil price volatility",
        "Asset maturity",
        "Petronas strategy changes",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Vestigo revenue grew 3% in FY24. Production stable from mature assets. Oil price impact on margins. Petronas subsidiary." },
      { tag: "strategy", tagLabel: "Strategy", text: "Mature asset specialist. Petronas non-core asset manager. EOR and production optimization. Cost discipline." },
      { tag: "risk", tagLabel: "Risk", text: "Oil price sensitivity. Natural decline. Petronas asset allocation. Limited diversification." },
      { tag: "market", tagLabel: "Market", text: "Petronas upstream subsidiary. Manages mature Malaysian assets. ~28K boepd production. Niche player." },
    ],
    risks: [
      { name: "Oil Price", level: 72, color: "var(--red)" },
      { name: "Decline Curve", level: 58, color: "var(--amber)" },
      { name: "Petronas Dependency", level: 55, color: "var(--amber)" },
      { name: "Scale", level: 52, color: "var(--cyan)" },
      { name: "Operational", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Hold",
      ratingColor: "var(--cyan)",
      text: "Vestigo serves as Petronas' mature asset manager. Production and revenue tied to oil price. Strategic role within Petronas ecosystem. Limited standalone visibility.",
    },
  },

  VANTRIS: {
    name: "Vantris Energy Berhad",
    ticker: "VANTRIS",
    entityType: "public",
    sector: "Oil, Gas & Energy",
    industry: "Oil & Gas Services - EPC / Restructured",
    hq: "Kuala Lumpur, Malaysia",
    employees: "2,100",
    founded: 2024,
    ceo: "Mohd Anuar Taib",
    price: 0.18,
    change: -0.01,
    changePct: -5.3,
    marketCap: "MYR 1.2B",
    peRatio: 0,
    divYield: "N/A",
    beta: 1.45,
    revenue52w: "MYR 2.8B",
    kpis: [
      { label: "Revenue", value: "MYR 2.8B", sub: "FY24" },
      { label: "Net Profit", value: "-MYR 185M", sub: "FY24" },
      { label: "Order Book", value: "MYR 4.2B", sub: "EPC" },
      { label: "Net Debt", value: "MYR 2.1B", sub: "FY24" },
      { label: "Rig Count", value: "8", sub: "Drilling" },
      { label: "Gross Margin", value: "6.2%", sub: "FY24" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [5200, 4200, 3500, 3200, 2800, 3000],
      netIncome: [-1200, -850, -420, -280, -185, -80],
      grossMargin: [8.5, 5.2, 4.5, 5.0, 6.2, 7.0],
      operatingMargin: [-8.5, -6.2, -3.5, -2.2, -1.5, -0.5],
      netMargin: [-23.1, -20.2, -12.0, -8.8, -6.6, -2.7],
    },
    segments: {
      labels: ["EPC", "Drilling", "Fabrication", "Engineering", "Others"],
      values: [45, 25, 18, 8, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Vantris", "Dialog", "MMC", "Sapura OBS", "Bumi Armada"],
      revenue: [2800, 4200, 5200, 1500, 2200],
      margin: [-6.6, 12.5, 8.5, 2.5, 4.5],
    },
    swot: {
      strengths: [
        "Restructured from Sapura Energy - clean slate",
        "EPC and drilling capabilities",
        "Petronas vendor status",
        "Order book provides visibility",
      ],
      weaknesses: [
        "Legacy debt burden",
        "Loss-making history",
        "Competitive EPC market",
      ],
      opportunities: [
        "Recovery in O&G capex",
        "Petronas project awards",
        "Debt restructuring progress",
      ],
      threats: [
        "Debt servicing",
        "Project execution risks",
        "Energy transition reducing O&G capex",
      ],
    },
    insights: [
      { tag: "growth", tagLabel: "Growth", text: "Vantris (ex-Sapura Energy) revenue declined 13% in FY24. Restructuring ongoing. Losses narrowing. Order book supports recovery." },
      { tag: "strategy", tagLabel: "Strategy", text: "Post-restructuring entity. Focus on EPC and drilling. Debt reduction. Petronas relationship critical." },
      { tag: "risk", tagLabel: "Risk", text: "High debt. Execution on projects. Liquidity. Creditor support. Sector recovery timing." },
      { tag: "market", tagLabel: "Market", text: "Restructured from Sapura Energy. O&G services. Listed on Bursa. Recovery play. High risk." },
    ],
    risks: [
      { name: "Debt", level: 85, color: "var(--red)" },
      { name: "Liquidity", level: 75, color: "var(--red)" },
      { name: "Execution", level: 62, color: "var(--amber)" },
      { name: "Sector", level: 58, color: "var(--amber)" },
      { name: "Competition", level: 58, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Sell",
      ratingColor: "var(--red)",
      text: "Vantris is a high-risk recovery play. Restructuring from Sapura Energy. Debt burden significant. Recovery depends on project execution and sector upturn. Speculative.",
    },
  },
});
