Object.assign(COMPANIES, {
  LHDN: {
    name: "Lembaga Hasil Dalam Negeri",
    ticker: "LHDN",
    entityType: "government",
    sector: "Government",
    industry: "Tax Administration",
    hq: "Cyberjaya, Malaysia",
    employees: "12,000",
    founded: 1996,
    ceo: "Datuk Dr. Abu Tariq Jamaluddin",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 184.8B",
    kpis: [
      { label: "Tax Revenue", value: "MYR 184.8B", sub: "Record high in 2024" },
      { label: "Compliance Rate", value: "87%", sub: "e-Filing adoption" },
      { label: "e-Filing %", value: "95%", sub: "Digital submissions" },
      { label: "Taxpayers", value: "7.2M", sub: "Registered individuals" },
      { label: "Audit Cases", value: "45,000", sub: "Annual audits" },
      { label: "Staff", value: "12,000", sub: "Total employees" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [132, 140, 163, 183.3, 184.8, 197],
      netIncome: [0, 0, 0, 0, 0, 0],
      grossMargin: [0, 0, 0, 0, 0, 0],
      operatingMargin: [0, 0, 0, 0, 0, 0],
      netMargin: [0, 0, 0, 0, 0, 0],
    },
    segments: {
      labels: ["Direct Tax", "Indirect Tax", "Stamp Duty", "Others", "Refunds"],
      values: [65, 22, 5, 4, 4],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["LHDN", "Customs", "SST", "Local Gov", "Others"],
      revenue: [185, 45, 32, 8, 5],
      margin: [0, 0, 0, 0, 0],
    },
    swot: {
      strengths: [
        "Strong digital infrastructure with e-Filing",
        "High taxpayer compliance rate",
        "Comprehensive tax administration framework",
        "Skilled workforce in tax matters",
      ],
      weaknesses: [
        "Complex tax regulations",
        "Limited enforcement resources",
        "Dependency on manual processes for some cases",
        "Backlog in dispute resolution",
      ],
      opportunities: [
        "AI-driven tax analytics",
        "Expanded digital services",
        "Regional tax harmonization",
        "Enhanced voluntary compliance programs",
      ],
      threats: [
        "Tax evasion and avoidance",
        "Economic volatility affecting collections",
        "Regulatory changes",
        "Talent retention in specialized roles",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "Tax collections grew ~8% YoY driven by economic recovery and improved compliance.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Focus on digital transformation and voluntary compliance to reduce enforcement costs.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "Revenue volatility tied to economic cycles and policy changes.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Largest revenue collector for federal government; critical for fiscal sustainability.",
      },
    ],
    risks: [
      { name: "Collection Shortfall", level: 35, color: "var(--amber)" },
      { name: "Compliance Decline", level: 25, color: "var(--green)" },
      { name: "Cyber Security", level: 45, color: "var(--amber)" },
      { name: "Regulatory Change", level: 30, color: "var(--cyan)" },
      { name: "Talent Gap", level: 40, color: "var(--amber)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--green)",
      text: "Strong collection trajectory with robust digital infrastructure. Continued focus on compliance and efficiency.",
    },
  },

  STATE_SEL_PJ: {
    name: "State Ministries - Selangor and Putrajaya",
    ticker: "STATE_SEL_PJ",
    entityType: "government",
    sector: "Government",
    industry: "State Administration",
    hq: "Shah Alam / Putrajaya, Malaysia",
    employees: "35,000",
    founded: 1974,
    ceo: "Dato' Seri Amirudin Shari",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 2.53B",
    kpis: [
      { label: "State Budget", value: "MYR 2.53B", sub: "2024 allocation" },
      { label: "GDP Contribution", value: "RM432B", sub: "26.2% of national GDP" },
      { label: "Population", value: "6.8M", sub: "State population" },
      { label: "Industrial Zones", value: "45+", sub: "Manufacturing hubs" },
      { label: "Digital Initiatives", value: "Smart Selangor", sub: "Flagship program" },
      { label: "Smart Selangor", value: "Phase 2", sub: "Digital transformation" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.0, 2.1, 2.2, 2.3, 2.53, 2.7],
      netIncome: [0.15, 0.18, 0.2, 0.22, 0.25, 0.28],
      grossMargin: [0, 0, 0, 0, 0, 0],
      operatingMargin: [5, 6, 7, 7, 8, 8],
      netMargin: [5, 6, 7, 7, 8, 8],
    },
    segments: {
      labels: ["Land Revenue", "Federal Grants", "Investment", "Others", "Reserves"],
      values: [35, 40, 12, 8, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["Selangor", "Johor", "Penang", "Kedah", "Others"],
      revenue: [3.2, 2.1, 1.5, 1.2, 0.8],
      margin: [8, 6, 5, 4, 3],
    },
    swot: {
      strengths: [
        "Largest state economy in Malaysia",
        "Strategic location (KLIA, ports)",
        "Strong industrial base",
        "Smart Selangor digital initiatives",
      ],
      weaknesses: [
        "Urban-rural development gap",
        "Traffic congestion",
        "Water supply dependency",
        "Administrative complexity",
      ],
      opportunities: [
        "Smart city expansion",
        "EV and tech hub development",
        "Tourism and MICE growth",
        "Green economy initiatives",
      ],
      threats: [
        "Federal-state relations",
        "Climate and flood risks",
        "Cost of living pressures",
        "Competition from other states",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "State budget grew 6% driven by land revenue and federal grants.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Smart Selangor 2.0 focuses on digital government and citizen services.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "Revenue dependency on land and federal grants; diversification ongoing.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Key economic engine; contributes ~25% to national GDP.",
      },
    ],
    risks: [
      { name: "Revenue Volatility", level: 40, color: "var(--amber)" },
      { name: "Infrastructure", level: 35, color: "var(--cyan)" },
      { name: "Political", level: 45, color: "var(--amber)" },
      { name: "Flood Risk", level: 50, color: "var(--amber)" },
      { name: "Water Supply", level: 55, color: "var(--red)" },
    ],
    outlook: {
      rating: "Positive",
      ratingColor: "var(--green)",
      text: "Strong economic base and digital initiatives. Water and flood mitigation remain key priorities.",
    },
  },

  MOE: {
    name: "Ministry of Education Malaysia",
    ticker: "MOE",
    entityType: "government",
    sector: "Government",
    industry: "Education",
    hq: "Putrajaya, Malaysia",
    employees: "420,000",
    founded: 1955,
    ceo: "Fadhlina Sidek",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 58.7B",
    kpis: [
      { label: "Annual Budget", value: "MYR 58.7B", sub: "FY2024 — largest ministry" },
      { label: "Schools", value: "10,200", sub: "Primary & secondary" },
      { label: "Students", value: "5.2M", sub: "Enrolled" },
      { label: "Teachers", value: "420,000", sub: "Total workforce" },
      { label: "Digital Adoption", value: "78%", sub: "Smart school coverage" },
      { label: "Literacy Rate", value: "96%", sub: "Adult literacy" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [50.4, 52.6, 55.6, 55.2, 58.7, 64.1],
      netIncome: [0, 0, 0, 0, 0, 0],
      grossMargin: [0, 0, 0, 0, 0, 0],
      operatingMargin: [0, 0, 0, 0, 0, 0],
      netMargin: [0, 0, 0, 0, 0, 0],
    },
    segments: {
      labels: ["Primary", "Secondary", "Higher Ed", "Vocational", "Admin"],
      values: [35, 30, 20, 10, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["MOE", "Private", "International", "Religious", "Others"],
      revenue: [55, 8, 5, 3, 2],
      margin: [0, 15, 20, 5, 0],
    },
    swot: {
      strengths: [
        "Largest education system in Malaysia",
        "Comprehensive national curriculum",
        "Strong teacher workforce",
        "Free primary and secondary education",
      ],
      weaknesses: [
        "Rural-urban quality gap",
        "Teacher shortage in STEM",
        "Infrastructure backlog",
        "Bureaucratic processes",
      ],
      opportunities: [
        "Digital learning expansion",
        "TVET and skills alignment",
        "International partnerships",
        "Early childhood education",
      ],
      threats: [
        "Budget constraints",
        "Brain drain to private sector",
        "Pandemic learning loss",
        "Demographic shifts",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "Budget 2025 raised to RM64.1B, the highest allocation in Malaysia's history, with RM2B for school upgrades.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Malaysia Education Blueprint 2025-2035 drives reform and digitalization.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "Fiscal pressure may constrain capital and quality improvements.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Single largest federal ministry by budget; critical for human capital.",
      },
    ],
    risks: [
      { name: "Budget Cut", level: 45, color: "var(--amber)" },
      { name: "Quality Gap", level: 55, color: "var(--amber)" },
      { name: "Teacher Shortage", level: 50, color: "var(--amber)" },
      { name: "Digital Divide", level: 40, color: "var(--cyan)" },
      { name: "Reform Delay", level: 35, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--green)",
      text: "Strategic priority with sustained funding. Reform and digitalization key focus areas.",
    },
  },

  FGV: {
    name: "FGV Holdings Berhad",
    ticker: "FGV",
    entityType: "public",
    sector: "Plantation",
    industry: "Palm Oil & Sugar",
    hq: "Kuala Lumpur, Malaysia",
    employees: "25,000",
    founded: 2007,
    ceo: "Datuk Fakhrunniam Othman",
    price: 1.14,
    change: 0.03,
    changePct: 1.78,
    marketCap: "MYR 4.16B",
    peRatio: 15.1,
    divYield: "2.5%",
    beta: 1.15,
    revenue52w: "MYR 22.2B",
    kpis: [
      { label: "Revenue", value: "MYR 22.2B", sub: "+14% YoY FY24" },
      { label: "Net Income", value: "MYR 276M", sub: "+171% YoY PATAMI" },
      { label: "Planted Area", value: "439K ha", sub: "Malaysia & Indonesia" },
      { label: "CPO Production", value: "3.0M MT", sub: "Annual CPO output" },
      { label: "FFB Yield", value: "18.5 t/ha", sub: "Industry benchmark" },
      { label: "Market Share", value: "8%", sub: "Malaysia palm oil" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [15.1, 17.8, 21.8, 19.4, 22.2, 23.5],
      netIncome: [0.12, 0.35, 0.52, 0.10, 0.276, 0.35],
      grossMargin: [18, 20, 19, 12, 15, 17],
      operatingMargin: [8, 10, 9, 4, 6, 7],
      netMargin: [2.5, 2.7, 2.3, 1.1, 2.5, 2.6],
    },
    segments: {
      labels: ["Plantation", "Sugar", "Logistics", "Others", "Trading"],
      values: [55, 18, 12, 8, 7],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["FGV", "Sime Darby Plantation", "IOI", "KLK", "Wilmar"],
      revenue: [22.2, 15.2, 18.2, 25.0, 45],
      margin: [2.5, 8, 12, 10, 3],
    },
    swot: {
      strengths: [
        "Largest oil palm planted area in Malaysia",
        "Integrated plantation to downstream",
        "Sugar business diversification",
        "Government-linked backing",
      ],
      weaknesses: [
        "Labor dependency and cost",
        "Sustainability scrutiny",
        "Sugar segment volatility",
        "Legacy debt",
      ],
      opportunities: [
        "CPO price recovery",
        "Sustainability premium",
        "Downstream expansion",
        "Automation and mechanization",
      ],
      threats: [
        "EU deforestation regulations",
        "Labor shortage",
        "Commodity price volatility",
        "Climate and yield risks",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "FY2024 revenue surged 14% to RM22.2B; PATAMI up 171% to RM276M, driven by higher FFB yields and CPO prices averaging RM4,102/MT.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Focus on sustainability certification and downstream value-add.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "EUDR and labor issues pose structural challenges.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Key player in Malaysian palm oil; ~8% of national production.",
      },
    ],
    risks: [
      { name: "CPO Price", level: 65, color: "var(--red)" },
      { name: "Sustainability", level: 55, color: "var(--amber)" },
      { name: "Labor", level: 60, color: "var(--amber)" },
      { name: "EUDR", level: 50, color: "var(--amber)" },
      { name: "Debt", level: 45, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Neutral",
      ratingColor: "var(--amber)",
      text: "Challenged by commodity cycle and sustainability. Long-term value in scale and diversification.",
    },
  },

  AMBANK: {
    name: "AMMB Holdings Berhad",
    ticker: "AMBANK",
    entityType: "public",
    sector: "Banking & Finance",
    industry: "Commercial Banking",
    hq: "Kuala Lumpur, Malaysia",
    employees: "9,000",
    founded: 1975,
    ceo: "Jamie Ling",
    price: 5.49,
    change: 0.08,
    changePct: 1.48,
    marketCap: "MYR 21.3B",
    peRatio: 10.2,
    divYield: "4.7%",
    beta: 1.12,
    revenue52w: "MYR 4.65B",
    kpis: [
      { label: "Total Income", value: "MYR 4.65B", sub: "FY24 (Mar)" },
      { label: "Net Income", value: "MYR 1.87B", sub: "+9% YoY PATMI" },
      { label: "Total Assets", value: "MYR 196B", sub: "As at FY24" },
      { label: "NPL Ratio", value: "1.5%", sub: "Asset quality" },
      { label: "ROE", value: "10.0%", sub: "Return on equity" },
      { label: "CAR", value: "16.8%", sub: "Capital adequacy" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [4.2, 4.4, 4.5, 4.7, 4.65, 4.9],
      netIncome: [1.1, 1.3, 1.5, 1.72, 1.87, 2.0],
      grossMargin: [0, 0, 0, 0, 0, 0],
      operatingMargin: [28, 30, 31, 31, 32, 33],
      netMargin: [23, 25, 26, 27, 28, 28],
    },
    segments: {
      labels: ["Retail", "Wholesale", "Islamic", "Investment", "Others"],
      values: [35, 30, 22, 8, 5],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["AmBank", "Maybank", "CIMB", "Public Bank", "RHB"],
      revenue: [5.8, 55, 22, 24, 12],
      margin: [28, 35, 30, 38, 25],
    },
    swot: {
      strengths: [
        "Strong retail and SME franchise",
        "Growing Islamic banking segment",
        "Digital banking initiatives",
        "ANZ legacy expertise",
      ],
      weaknesses: [
        "Smaller scale vs top 4 banks",
        "Limited regional presence",
        "Cost-to-income ratio pressure",
        "Market share constraints",
      ],
      opportunities: [
        "Digital and fintech partnerships",
        "SME and consumer lending growth",
        "Wealth management expansion",
        "Sustainable finance",
      ],
      threats: [
        "Competition from digital banks",
        "Interest rate volatility",
        "Asset quality in economic downturn",
        "Regulatory tightening",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "PATMI grew 9% to RM1.87B in FY24; gross loans up 3% to RM134B; deposits up 9% to RM142B. NIM compressed to 1.79%.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Digital transformation and Islamic banking as growth pillars.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "NPL stable at 1.5%; well-capitalized with CAR 16.8%.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Fifth-largest banking group; focused on niche segments.",
      },
    ],
    risks: [
      { name: "Credit Risk", level: 40, color: "var(--amber)" },
      { name: "Interest Rate", level: 45, color: "var(--amber)" },
      { name: "Competition", level: 50, color: "var(--amber)" },
      { name: "Digital Disruption", level: 35, color: "var(--cyan)" },
      { name: "Regulatory", level: 30, color: "var(--green)" },
    ],
    outlook: {
      rating: "Positive",
      ratingColor: "var(--green)",
      text: "Solid fundamentals and improving efficiency. Attractive dividend yield.",
    },
  },

  KWAP: {
    name: "Kumpulan Wang Persaraan",
    ticker: "KWAP",
    entityType: "statutory",
    sector: "Government",
    industry: "Pension Fund",
    hq: "Kuala Lumpur, Malaysia",
    employees: "400",
    founded: 2007,
    ceo: "Hajah Nik Amlizan Mohamed",
    price: 0,
    change: 0,
    changePct: 0,
    marketCap: "N/A",
    peRatio: 0,
    divYield: "N/A",
    beta: 0,
    revenue52w: "MYR 18.0B",
    kpis: [
      { label: "AUM", value: "MYR 185.6B", sub: "+9.3% YoY fund size" },
      { label: "Total Return", value: "12.0%", sub: "Highest since inception" },
      { label: "Pensioners Served", value: "810K+", sub: "Pension recipients" },
      { label: "Dividend", value: "5.5%", sub: "Declared to govt" },
      { label: "Portfolio Allocation", value: "Equity 51.7%", sub: "Domestic 74.6%" },
      { label: "Staff", value: "400", sub: "Total employees" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [8.5, 10.2, 9.8, 11.5, 18.0, 14.0],
      netIncome: [8.0, 9.8, 9.2, 10.8, 12.9, 13.0],
      grossMargin: [0, 0, 0, 0, 0, 0],
      operatingMargin: [95, 96, 96, 96, 96, 96],
      netMargin: [95, 96, 96, 96, 96, 96],
    },
    segments: {
      labels: ["Equity", "Fixed Income", "Private Equity", "Real Estate", "Infrastructure"],
      values: [52, 32, 5, 5, 6],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["KWAP", "EPF", "PNB", "LTAT", "SOCSO"],
      revenue: [12, 65, 25, 8, 5],
      margin: [96, 98, 95, 90, 85],
    },
    swot: {
      strengths: [
        "Second-largest pension fund in Malaysia",
        "Long-term investment horizon",
        "Diversified portfolio",
        "Strong governance framework",
      ],
      weaknesses: [
        "Limited public visibility",
        "Concentration in domestic assets",
        "Liability-driven constraints",
        "Small team vs AUM",
      ],
      opportunities: [
        "Global diversification",
        "ESG and impact investing",
        "Private equity and alternatives",
        "Digital transformation",
      ],
      threats: [
        "Market volatility",
        "Low yield environment",
        "Liability growth",
        "Regulatory changes",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "Fund size grew 9.3% to RM185.6B; investment income hit RM18.0B, the highest since inception. Total return of 12.0% in 2024.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Balanced portfolio with increasing alternatives allocation.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "Market-sensitive returns; liability matching is key.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Major institutional investor; significant domestic market influence.",
      },
    ],
    risks: [
      { name: "Market Volatility", level: 55, color: "var(--amber)" },
      { name: "Liability Growth", level: 45, color: "var(--amber)" },
      { name: "Return Target", level: 40, color: "var(--cyan)" },
      { name: "Concentration", level: 35, color: "var(--cyan)" },
      { name: "Governance", level: 20, color: "var(--green)" },
    ],
    outlook: {
      rating: "Stable",
      ratingColor: "var(--green)",
      text: "Well-managed fund with solid returns. Continued diversification and ESG focus.",
    },
  },

  KPJ: {
    name: "KPJ Healthcare Berhad",
    ticker: "KPJ",
    entityType: "public",
    sector: "Healthcare",
    industry: "Private Hospital Operations",
    hq: "Kuala Lumpur, Malaysia",
    employees: "16,000",
    founded: 1981,
    ceo: "Ahmad Shahizam Mohd Shariff",
    price: 3.00,
    change: 0.05,
    changePct: 1.69,
    marketCap: "MYR 13.58B",
    peRatio: 33.4,
    divYield: "1.8%",
    beta: 0.85,
    revenue52w: "MYR 3.92B",
    kpis: [
      { label: "Revenue", value: "MYR 3.92B", sub: "+15% YoY FY24" },
      { label: "Net Income", value: "MYR 407M", sub: "+51% YoY" },
      { label: "Hospitals", value: "30", sub: "Network" },
      { label: "Beds", value: "4,500+", sub: "Total capacity" },
      { label: "Patients/Year", value: "3.39M", sub: "3M outpatient + 388K inpatient" },
      { label: "Occupancy Rate", value: "69%", sub: "+2pp YoY" },
    ],
    financials: {
      years: ["FY20", "FY21", "FY22", "FY23", "FY24", "FY25E"],
      revenue: [2.8, 3.0, 3.2, 3.42, 3.92, 4.26],
      netIncome: [0.14, 0.18, 0.22, 0.27, 0.407, 0.45],
      grossMargin: [32, 33, 34, 34, 35, 35],
      operatingMargin: [12, 13, 14, 14, 15, 15],
      netMargin: [5.6, 6.3, 6.8, 7.0, 7.4, 7.8],
    },
    segments: {
      labels: ["Hospital Ops", "Specialist", "Pharmacy", "Education", "Others"],
      values: [70, 15, 8, 4, 3],
      colors: ["#6366f1", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444"],
    },
    competitors: {
      labels: ["KPJ", "IHH", "Ramsay", "Columbia Asia", "Pantai"],
      revenue: [4.2, 18, 3.5, 1.2, 2.5],
      margin: [7.4, 12, 8, 6, 5],
    },
    swot: {
      strengths: [
        "Largest private hospital network in Malaysia",
        "Strong brand and geographic coverage",
        "Integrated healthcare ecosystem",
        "JCorp backing",
      ],
      weaknesses: [
        "Occupancy below optimal",
        "Margin pressure from costs",
        "Dependency on medical tourism",
        "Nurse shortage",
      ],
      opportunities: [
        "Medical tourism recovery",
        "Specialty and day care expansion",
        "Digital health services",
        "Aging population demand",
      ],
      threats: [
        "Public healthcare competition",
        "Cost inflation",
        "Regulatory changes",
        "Talent retention",
      ],
    },
    insights: [
      {
        tag: "growth",
        tagLabel: "Growth",
        text: "Revenue surged 15% to RM3.92B in FY24; net profit jumped 51% to RM407M. Inpatient admissions up 7% to 388K; outpatient visits over 3M.",
      },
      {
        tag: "strategy",
        tagLabel: "Strategy",
        text: "Expansion in day care, oncology, and digital health.",
      },
      {
        tag: "risk",
        tagLabel: "Risk",
        text: "Labor and supply cost pressures; medical tourism recovery key.",
      },
      {
        tag: "market",
        tagLabel: "Market",
        text: "Leading private healthcare provider; benefits from aging demographics.",
      },
    ],
    risks: [
      { name: "Cost Inflation", level: 55, color: "var(--amber)" },
      { name: "Occupancy", level: 45, color: "var(--cyan)" },
      { name: "Medical Tourism", level: 40, color: "var(--cyan)" },
      { name: "Talent", level: 50, color: "var(--amber)" },
      { name: "Regulatory", level: 35, color: "var(--cyan)" },
    ],
    outlook: {
      rating: "Positive",
      ratingColor: "var(--green)",
      text: "Structural growth from demographics and medical tourism. Margin improvement ongoing.",
    },
  },
});
